/* activities.c generated by valac 0.16.0, the Vala compiler
 * generated from activities.vala, do not modify */

/*
 * Copyright (c) 2012 Stefano Candori <scandori@gnome.org>
 *
 * Gnome Activity Journal is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2 of the License, or (at your
 * option) any later version.
 *
 * Gnome Documents is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with Gnome Documents; if not, write to the Free Software Foundation,
 * Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * Author: Stefano Candori <scandori@gnome.org>
 *
 */

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gdk-pixbuf/gdk-pixbuf.h>
#include <zeitgeist.h>
#include <gio/gio.h>
#include <gtk/gtk.h>
#include <gee.h>
#include <gd-main-view.h>


#define JOURNAL_TYPE_GENERIC_ACTIVITY (journal_generic_activity_get_type ())
#define JOURNAL_GENERIC_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_GENERIC_ACTIVITY, JournalGenericActivity))
#define JOURNAL_GENERIC_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_GENERIC_ACTIVITY, JournalGenericActivityClass))
#define JOURNAL_IS_GENERIC_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_GENERIC_ACTIVITY))
#define JOURNAL_IS_GENERIC_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_GENERIC_ACTIVITY))
#define JOURNAL_GENERIC_ACTIVITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_GENERIC_ACTIVITY, JournalGenericActivityClass))

typedef struct _JournalGenericActivity JournalGenericActivity;
typedef struct _JournalGenericActivityClass JournalGenericActivityClass;
typedef struct _JournalGenericActivityPrivate JournalGenericActivityPrivate;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_regex_unref0(var) ((var == NULL) ? NULL : (var = (g_regex_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
typedef struct _journal_generic_activity_updateActivityIconData journal_generic_activity_updateActivityIconData;
#define _gtk_icon_info_free0(var) ((var == NULL) ? NULL : (var = (gtk_icon_info_free (var), NULL)))
typedef struct _JournalGenericActivityGetThumbData JournalGenericActivityGetThumbData;

#define JOURNAL_TYPE_ACTIVITY_MODEL (journal_activity_model_get_type ())
#define JOURNAL_ACTIVITY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_ACTIVITY_MODEL, JournalActivityModel))
#define JOURNAL_ACTIVITY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_ACTIVITY_MODEL, JournalActivityModelClass))
#define JOURNAL_IS_ACTIVITY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_ACTIVITY_MODEL))
#define JOURNAL_IS_ACTIVITY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_ACTIVITY_MODEL))
#define JOURNAL_ACTIVITY_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_ACTIVITY_MODEL, JournalActivityModelClass))

typedef struct _JournalActivityModel JournalActivityModel;
typedef struct _JournalActivityModelClass JournalActivityModelClass;
typedef struct _JournalActivityModelPrivate JournalActivityModelPrivate;
typedef struct _Block1Data Block1Data;
typedef struct _Block2Data Block2Data;

struct _JournalGenericActivity {
	GObject parent_instance;
	JournalGenericActivityPrivate * priv;
};

struct _JournalGenericActivityClass {
	GObjectClass parent_class;
};

struct _JournalGenericActivityPrivate {
	gchar* _uri;
	gchar* _title;
	GdkPixbuf* _type_icon;
	GdkPixbuf* _thumb_icon;
	gchar* _display_uri;
	gint64 _time;
	gboolean _selected;
	gchar* _mimetype;
	ZeitgeistSubject* subject;
	gchar* thumb_path;
};

struct _journal_generic_activity_updateActivityIconData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	JournalGenericActivity* self;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	GFile* _tmp2_;
	GFile* file;
	GFile* _tmp3_;
	gboolean _tmp4_;
	GFileInfo* info;
	GFile* _tmp5_;
	GFileInfo* _tmp6_;
	GFileInfo* _tmp7_;
	GError* e;
	const gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	GError* _tmp13_;
	const gchar* _tmp14_;
	gchar* _tmp15_;
	gchar* _tmp16_;
	GFileInfo* _tmp17_;
	GFileInfo* _tmp18_;
	const gchar* _tmp19_;
	gchar* _tmp20_;
	const gchar* _tmp21_;
	GFile* _tmp22_;
	gboolean _tmp23_;
	gboolean thumbnailed;
	gboolean _tmp24_;
	GFile* _tmp25_;
	GFileInfo* _tmp26_;
	GFileInfo* _tmp27_;
	GError* _vala1_e;
	const gchar* _tmp28_;
	gchar* _tmp29_;
	gchar* _tmp30_;
	gchar* _tmp31_;
	gchar* _tmp32_;
	GError* _tmp33_;
	const gchar* _tmp34_;
	gchar* _tmp35_;
	gchar* _tmp36_;
	GFileInfo* _tmp37_;
	const gchar* _tmp38_;
	gchar* _tmp39_;
	const gchar* _tmp40_;
	GError * _inner_error_;
};

struct _JournalGenericActivityGetThumbData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	JournalGenericActivity* self;
	const gchar* _tmp0_;
	GFile* _tmp1_;
	GFile* file;
	GFile* _tmp2_;
	GFileInputStream* _tmp3_;
	GFileInputStream* stream;
	GFileInputStream* _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	GdkPixbuf* _tmp7_;
	GdkPixbuf* _tmp8_;
	GdkPixbuf* _tmp9_;
	GError* e;
	const gchar* _tmp10_;
	gchar* _tmp11_;
	gchar* _tmp12_;
	gchar* _tmp13_;
	gchar* _tmp14_;
	GError* _tmp15_;
	const gchar* _tmp16_;
	gchar* _tmp17_;
	gchar* _tmp18_;
	GError * _inner_error_;
};

struct _JournalActivityModel {
	GObject parent_instance;
	JournalActivityModelPrivate * priv;
};

struct _JournalActivityModelClass {
	GObjectClass parent_class;
};

struct _JournalActivityModelPrivate {
	GtkListStore* model;
	GeeArrayList* _activities;
};

struct _Block1Data {
	int _ref_count_;
	JournalActivityModel * self;
	JournalGenericActivity* activity;
};

struct _Block2Data {
	int _ref_count_;
	JournalActivityModel * self;
	JournalGenericActivity* activity;
};


static gpointer journal_generic_activity_parent_class = NULL;
static gpointer journal_activity_model_parent_class = NULL;

GType journal_generic_activity_get_type (void) G_GNUC_CONST;
#define JOURNAL_GENERIC_ACTIVITY_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JOURNAL_TYPE_GENERIC_ACTIVITY, JournalGenericActivityPrivate))
enum  {
	JOURNAL_GENERIC_ACTIVITY_DUMMY_PROPERTY,
	JOURNAL_GENERIC_ACTIVITY_URI,
	JOURNAL_GENERIC_ACTIVITY_TITLE,
	JOURNAL_GENERIC_ACTIVITY_TYPE_ICON,
	JOURNAL_GENERIC_ACTIVITY_THUMB_ICON,
	JOURNAL_GENERIC_ACTIVITY_DISPLAY_URI,
	JOURNAL_GENERIC_ACTIVITY_TIME,
	JOURNAL_GENERIC_ACTIVITY_SELECTED,
	JOURNAL_GENERIC_ACTIVITY_MIMETYPE
};
JournalGenericActivity* journal_generic_activity_new (ZeitgeistEvent* event);
JournalGenericActivity* journal_generic_activity_construct (GType object_type, ZeitgeistEvent* event);
static void journal_generic_activity_set_uri (JournalGenericActivity* self, const gchar* value);
static void journal_generic_activity_set_title (JournalGenericActivity* self, const gchar* value);
static void journal_generic_activity_set_type_icon (JournalGenericActivity* self, GdkPixbuf* value);
static void journal_generic_activity_set_thumb_icon (JournalGenericActivity* self, GdkPixbuf* value);
static gchar* journal_generic_activity_create_display_uri (JournalGenericActivity* self);
static void journal_generic_activity_set_display_uri (JournalGenericActivity* self, const gchar* value);
static void journal_generic_activity_set_time (JournalGenericActivity* self, gint64 value);
void journal_generic_activity_set_selected (JournalGenericActivity* self, gboolean value);
static void journal_generic_activity_set_mimetype (JournalGenericActivity* self, const gchar* value);
static void journal_generic_activity_updateActivityIcon (JournalGenericActivity* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void journal_generic_activity_updateActivityIcon_finish (JournalGenericActivity* self, GAsyncResult* _res_);
static void journal_generic_activity_updateActivityIcon_data_free (gpointer _data);
static gboolean journal_generic_activity_updateActivityIcon_co (journal_generic_activity_updateActivityIconData* _data_);
static void journal_generic_activity_get_thumb (JournalGenericActivity* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void journal_generic_activity_get_thumb_finish (JournalGenericActivity* self, GAsyncResult* _res_);
static void journal_generic_activity_updateTypeIcon (JournalGenericActivity* self);
const gchar* journal_generic_activity_get_uri (JournalGenericActivity* self);
static void journal_generic_activity_updateActivityIcon_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
void journal_utils_queue_thumbnail_job_for_file_async (GFile* file, GAsyncReadyCallback _callback_, gpointer _user_data_);
gboolean journal_utils_queue_thumbnail_job_for_file_finish (GAsyncResult* _res_);
const gchar* journal_generic_activity_get_mimetype (JournalGenericActivity* self);
gint journal_utils_getIconSize (void);
GdkPixbuf* journal_generic_activity_get_type_icon (JournalGenericActivity* self);
static void journal_generic_activity_get_thumb_data_free (gpointer _data);
static gboolean journal_generic_activity_get_thumb_co (JournalGenericActivityGetThumbData* _data_);
static void journal_generic_activity_get_thumb_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
const gchar* journal_generic_activity_get_title (JournalGenericActivity* self);
GdkPixbuf* journal_generic_activity_get_thumb_icon (JournalGenericActivity* self);
const gchar* journal_generic_activity_get_display_uri (JournalGenericActivity* self);
gint64 journal_generic_activity_get_time (JournalGenericActivity* self);
gboolean journal_generic_activity_get_selected (JournalGenericActivity* self);
static void journal_generic_activity_finalize (GObject* obj);
static void _vala_journal_generic_activity_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_journal_generic_activity_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType journal_activity_model_get_type (void) G_GNUC_CONST;
#define JOURNAL_ACTIVITY_MODEL_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JOURNAL_TYPE_ACTIVITY_MODEL, JournalActivityModelPrivate))
enum  {
	JOURNAL_ACTIVITY_MODEL_DUMMY_PROPERTY,
	JOURNAL_ACTIVITY_MODEL_ACTIVITIES
};
JournalActivityModel* journal_activity_model_new (void);
JournalActivityModel* journal_activity_model_construct (GType object_type);
void journal_activity_model_clear (JournalActivityModel* self);
void journal_activity_model_add_activity (JournalActivityModel* self, JournalGenericActivity* activity);
static void __lambda3_ (JournalActivityModel* self, JournalGenericActivity* activity);
static void journal_activity_model_update_icon_for_activity (JournalActivityModel* self, JournalGenericActivity* activity);
static void ___lambda3__journal_generic_activity_thumb_loaded (JournalGenericActivity* _sender, JournalGenericActivity* activity, gpointer self);
GeeArrayList* journal_activity_model_get_activities (JournalActivityModel* self);
void journal_activity_model_remove_activity (JournalActivityModel* self, JournalGenericActivity* activity);
static Block1Data* block1_data_ref (Block1Data* _data1_);
static void block1_data_unref (void * _userdata_);
static gboolean __lambda5_ (Block1Data* _data1_, GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter);
static gboolean ___lambda5__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self);
static Block2Data* block2_data_ref (Block2Data* _data2_);
static void block2_data_unref (void * _userdata_);
static gboolean __lambda4_ (Block2Data* _data2_, GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter);
static gboolean ___lambda4__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self);
GtkListStore* journal_activity_model_get_model (JournalActivityModel* self);
static void journal_activity_model_finalize (GObject* obj);
static void _vala_journal_activity_model_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);
static gint _vala_array_length (gpointer array);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


JournalGenericActivity* journal_generic_activity_construct (GType object_type, ZeitgeistEvent* event) {
	JournalGenericActivity * self = NULL;
	ZeitgeistEvent* _tmp0_;
	ZeitgeistSubject* _tmp1_ = NULL;
	ZeitgeistSubject* _tmp2_;
	ZeitgeistSubject* _tmp3_;
	const gchar* _tmp4_ = NULL;
	ZeitgeistSubject* _tmp5_;
	const gchar* _tmp6_ = NULL;
	gchar* _tmp7_ = NULL;
	gchar* _tmp8_;
	ZeitgeistEvent* _tmp9_;
	gint64 _tmp10_ = 0LL;
	ZeitgeistSubject* _tmp11_;
	const gchar* _tmp12_ = NULL;
	g_return_val_if_fail (event != NULL, NULL);
	self = (JournalGenericActivity*) g_object_new (object_type, NULL);
	_tmp0_ = event;
	_tmp1_ = zeitgeist_event_get_subject (_tmp0_, 0);
	_tmp2_ = _g_object_ref0 (_tmp1_);
	_g_object_unref0 (self->priv->subject);
	self->priv->subject = _tmp2_;
	_tmp3_ = self->priv->subject;
	_tmp4_ = zeitgeist_subject_get_uri (_tmp3_);
	journal_generic_activity_set_uri (self, _tmp4_);
	_tmp5_ = self->priv->subject;
	_tmp6_ = zeitgeist_subject_get_text (_tmp5_);
	journal_generic_activity_set_title (self, _tmp6_);
	journal_generic_activity_set_type_icon (self, NULL);
	journal_generic_activity_set_thumb_icon (self, NULL);
	_tmp7_ = journal_generic_activity_create_display_uri (self);
	_tmp8_ = _tmp7_;
	journal_generic_activity_set_display_uri (self, _tmp8_);
	_g_free0 (_tmp8_);
	_tmp9_ = event;
	_tmp10_ = zeitgeist_event_get_timestamp (_tmp9_);
	journal_generic_activity_set_time (self, _tmp10_);
	journal_generic_activity_set_selected (self, FALSE);
	_tmp11_ = self->priv->subject;
	_tmp12_ = zeitgeist_subject_get_mimetype (_tmp11_);
	journal_generic_activity_set_mimetype (self, _tmp12_);
	journal_generic_activity_updateActivityIcon (self, NULL, NULL);
	return self;
}


JournalGenericActivity* journal_generic_activity_new (ZeitgeistEvent* event) {
	return journal_generic_activity_construct (JOURNAL_TYPE_GENERIC_ACTIVITY, event);
}


static gchar* string_replace (const gchar* self, const gchar* old, const gchar* replacement) {
	gchar* result = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (old != NULL, NULL);
	g_return_val_if_fail (replacement != NULL, NULL);
	{
		const gchar* _tmp0_;
		gchar* _tmp1_ = NULL;
		gchar* _tmp2_;
		GRegex* _tmp3_;
		GRegex* _tmp4_;
		GRegex* regex;
		GRegex* _tmp5_;
		const gchar* _tmp6_;
		gchar* _tmp7_ = NULL;
		gchar* _tmp8_;
		_tmp0_ = old;
		_tmp1_ = g_regex_escape_string (_tmp0_, -1);
		_tmp2_ = _tmp1_;
		_tmp3_ = g_regex_new (_tmp2_, 0, 0, &_inner_error_);
		_tmp4_ = _tmp3_;
		_g_free0 (_tmp2_);
		regex = _tmp4_;
		if (_inner_error_ != NULL) {
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		_tmp5_ = regex;
		_tmp6_ = replacement;
		_tmp7_ = g_regex_replace_literal (_tmp5_, self, (gssize) (-1), 0, _tmp6_, 0, &_inner_error_);
		_tmp8_ = _tmp7_;
		if (_inner_error_ != NULL) {
			_g_regex_unref0 (regex);
			if (_inner_error_->domain == G_REGEX_ERROR) {
				goto __catch0_g_regex_error;
			}
			_g_regex_unref0 (regex);
			g_critical ("file %s: line %d: unexpected error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
		result = _tmp8_;
		_g_regex_unref0 (regex);
		return result;
	}
	goto __finally0;
	__catch0_g_regex_error:
	{
		GError* e = NULL;
		e = _inner_error_;
		_inner_error_ = NULL;
		g_assert_not_reached ();
		_g_error_free0 (e);
	}
	__finally0:
	if (_inner_error_ != NULL) {
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return NULL;
	}
}


static gchar* journal_generic_activity_create_display_uri (JournalGenericActivity* self) {
	gchar* result = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_;
	gchar* home;
	ZeitgeistSubject* _tmp2_;
	const gchar* _tmp3_ = NULL;
	gchar** _tmp4_;
	gchar** _tmp5_ = NULL;
	gchar** _tmp6_;
	gint _tmp6__length1;
	const gchar* _tmp7_;
	gchar* _tmp8_;
	gchar* _tmp9_;
	gchar* uri;
	gchar* _tmp10_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_get_home_dir ();
	_tmp1_ = g_strdup (_tmp0_);
	home = _tmp1_;
	_tmp2_ = self->priv->subject;
	_tmp3_ = zeitgeist_subject_get_origin (_tmp2_);
	_tmp5_ = _tmp4_ = g_strsplit (_tmp3_, "://", 0);
	_tmp6_ = _tmp5_;
	_tmp6__length1 = _vala_array_length (_tmp4_);
	_tmp7_ = _tmp6_[1];
	_tmp8_ = g_strdup (_tmp7_);
	_tmp9_ = _tmp8_;
	_tmp6_ = (_vala_array_free (_tmp6_, _tmp6__length1, (GDestroyNotify) g_free), NULL);
	uri = _tmp9_;
	_tmp10_ = string_replace (uri, home, "~");
	result = _tmp10_;
	_g_free0 (uri);
	_g_free0 (home);
	return result;
}


static void journal_generic_activity_updateActivityIcon_data_free (gpointer _data) {
	journal_generic_activity_updateActivityIconData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (journal_generic_activity_updateActivityIconData, _data_);
}


static void journal_generic_activity_updateActivityIcon (JournalGenericActivity* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	journal_generic_activity_updateActivityIconData* _data_;
	JournalGenericActivity* _tmp0_;
	_data_ = g_slice_new0 (journal_generic_activity_updateActivityIconData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, journal_generic_activity_updateActivityIcon);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, journal_generic_activity_updateActivityIcon_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	journal_generic_activity_updateActivityIcon_co (_data_);
}


static void journal_generic_activity_updateActivityIcon_finish (JournalGenericActivity* self, GAsyncResult* _res_) {
	journal_generic_activity_updateActivityIconData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void journal_generic_activity_updateActivityIcon_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	journal_generic_activity_updateActivityIconData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	journal_generic_activity_updateActivityIcon_co (_data_);
}


static gboolean journal_generic_activity_updateActivityIcon_co (journal_generic_activity_updateActivityIconData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		case 2:
		goto _state_2;
		case 3:
		goto _state_3;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->thumb_path;
	if (_data_->_tmp0_ != NULL) {
		journal_generic_activity_get_thumb (_data_->self, NULL, NULL);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	journal_generic_activity_updateTypeIcon (_data_->self);
	_data_->_tmp1_ = _data_->self->priv->_uri;
	_data_->_tmp2_ = NULL;
	_data_->_tmp2_ = g_file_new_for_uri (_data_->_tmp1_);
	_data_->file = _data_->_tmp2_;
	_data_->_tmp3_ = _data_->file;
	_data_->_tmp4_ = FALSE;
	_data_->_tmp4_ = g_file_query_exists (_data_->_tmp3_, NULL);
	if (!_data_->_tmp4_) {
		_g_object_unref0 (_data_->file);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_data_->info = NULL;
	{
		_data_->_tmp5_ = _data_->file;
		_data_->_state_ = 1;
		g_file_query_info_async (_data_->_tmp5_, G_FILE_ATTRIBUTE_THUMBNAIL_PATH, 0, 0, NULL, journal_generic_activity_updateActivityIcon_ready, _data_);
		return FALSE;
		_state_1:
		_data_->_tmp6_ = NULL;
		_data_->_tmp6_ = g_file_query_info_finish (_data_->_tmp5_, _data_->_res_, &_data_->_inner_error_);
		_data_->_tmp7_ = _data_->_tmp6_;
		if (_data_->_inner_error_ != NULL) {
			goto __catch1_g_error;
		}
		_g_object_unref0 (_data_->info);
		_data_->info = _data_->_tmp7_;
	}
	goto __finally1;
	__catch1_g_error:
	{
		_data_->e = _data_->_inner_error_;
		_data_->_inner_error_ = NULL;
		_data_->_tmp8_ = _data_->self->priv->_uri;
		_data_->_tmp9_ = g_strconcat ("Unable to query info for file at ", _data_->_tmp8_, NULL);
		_data_->_tmp10_ = _data_->_tmp9_;
		_data_->_tmp11_ = g_strconcat (_data_->_tmp10_, ": ", NULL);
		_data_->_tmp12_ = _data_->_tmp11_;
		_data_->_tmp13_ = _data_->e;
		_data_->_tmp14_ = _data_->_tmp13_->message;
		_data_->_tmp15_ = g_strconcat (_data_->_tmp12_, _data_->_tmp14_, NULL);
		_data_->_tmp16_ = _data_->_tmp15_;
		g_warning ("activities.vala:106: %s", _data_->_tmp16_);
		_g_free0 (_data_->_tmp16_);
		_g_free0 (_data_->_tmp12_);
		_g_free0 (_data_->_tmp10_);
		_g_error_free0 (_data_->e);
	}
	__finally1:
	if (_data_->_inner_error_ != NULL) {
		_g_object_unref0 (_data_->info);
		_g_object_unref0 (_data_->file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
		g_clear_error (&_data_->_inner_error_);
		return FALSE;
	}
	_data_->_tmp17_ = _data_->info;
	if (_data_->_tmp17_ != NULL) {
		_data_->_tmp18_ = _data_->info;
		_data_->_tmp19_ = NULL;
		_data_->_tmp19_ = g_file_info_get_attribute_byte_string (_data_->_tmp18_, G_FILE_ATTRIBUTE_THUMBNAIL_PATH);
		_data_->_tmp20_ = g_strdup (_data_->_tmp19_);
		_g_free0 (_data_->self->priv->thumb_path);
		_data_->self->priv->thumb_path = _data_->_tmp20_;
		_data_->_tmp21_ = _data_->self->priv->thumb_path;
		if (_data_->_tmp21_ != NULL) {
			journal_generic_activity_get_thumb (_data_->self, NULL, NULL);
		}
	}
	_data_->_tmp22_ = _data_->file;
	_data_->_state_ = 2;
	journal_utils_queue_thumbnail_job_for_file_async (_data_->_tmp22_, journal_generic_activity_updateActivityIcon_ready, _data_);
	return FALSE;
	_state_2:
	_data_->_tmp23_ = FALSE;
	_data_->_tmp23_ = journal_utils_queue_thumbnail_job_for_file_finish (_data_->_res_);
	_data_->thumbnailed = _data_->_tmp23_;
	_data_->_tmp24_ = _data_->thumbnailed;
	if (!_data_->_tmp24_) {
		_g_object_unref0 (_data_->info);
		_g_object_unref0 (_data_->file);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	_g_object_unref0 (_data_->info);
	_data_->info = NULL;
	{
		_data_->_tmp25_ = _data_->file;
		_data_->_state_ = 3;
		g_file_query_info_async (_data_->_tmp25_, G_FILE_ATTRIBUTE_THUMBNAIL_PATH, 0, 0, NULL, journal_generic_activity_updateActivityIcon_ready, _data_);
		return FALSE;
		_state_3:
		_data_->_tmp26_ = NULL;
		_data_->_tmp26_ = g_file_query_info_finish (_data_->_tmp25_, _data_->_res_, &_data_->_inner_error_);
		_data_->_tmp27_ = _data_->_tmp26_;
		if (_data_->_inner_error_ != NULL) {
			goto __catch2_g_error;
		}
		_g_object_unref0 (_data_->info);
		_data_->info = _data_->_tmp27_;
	}
	goto __finally2;
	__catch2_g_error:
	{
		_data_->_vala1_e = _data_->_inner_error_;
		_data_->_inner_error_ = NULL;
		_data_->_tmp28_ = _data_->self->priv->_uri;
		_data_->_tmp29_ = g_strconcat ("Unable to query info for file at ", _data_->_tmp28_, NULL);
		_data_->_tmp30_ = _data_->_tmp29_;
		_data_->_tmp31_ = g_strconcat (_data_->_tmp30_, ": ", NULL);
		_data_->_tmp32_ = _data_->_tmp31_;
		_data_->_tmp33_ = _data_->_vala1_e;
		_data_->_tmp34_ = _data_->_tmp33_->message;
		_data_->_tmp35_ = g_strconcat (_data_->_tmp32_, _data_->_tmp34_, NULL);
		_data_->_tmp36_ = _data_->_tmp35_;
		g_warning ("activities.vala:126: %s", _data_->_tmp36_);
		_g_free0 (_data_->_tmp36_);
		_g_free0 (_data_->_tmp32_);
		_g_free0 (_data_->_tmp30_);
		_g_error_free0 (_data_->_vala1_e);
		_g_object_unref0 (_data_->info);
		_g_object_unref0 (_data_->file);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	__finally2:
	if (_data_->_inner_error_ != NULL) {
		_g_object_unref0 (_data_->info);
		_g_object_unref0 (_data_->file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
		g_clear_error (&_data_->_inner_error_);
		return FALSE;
	}
	_data_->_tmp37_ = _data_->info;
	_data_->_tmp38_ = NULL;
	_data_->_tmp38_ = g_file_info_get_attribute_byte_string (_data_->_tmp37_, G_FILE_ATTRIBUTE_THUMBNAIL_PATH);
	_data_->_tmp39_ = g_strdup (_data_->_tmp38_);
	_g_free0 (_data_->self->priv->thumb_path);
	_data_->self->priv->thumb_path = _data_->_tmp39_;
	_data_->_tmp40_ = _data_->self->priv->thumb_path;
	if (_data_->_tmp40_ != NULL) {
		journal_generic_activity_get_thumb (_data_->self, NULL, NULL);
	}
	_g_object_unref0 (_data_->info);
	_g_object_unref0 (_data_->file);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void journal_generic_activity_updateTypeIcon (JournalGenericActivity* self) {
	GIcon* _icon;
	GtkIconInfo* icon_info;
	const gchar* _tmp0_;
	GIcon* _tmp3_;
	GtkIconInfo* _tmp8_;
	GError * _inner_error_ = NULL;
	g_return_if_fail (self != NULL);
	_icon = NULL;
	icon_info = NULL;
	_tmp0_ = self->priv->_mimetype;
	if (_tmp0_ != NULL) {
		const gchar* _tmp1_;
		GIcon* _tmp2_ = NULL;
		_tmp1_ = self->priv->_mimetype;
		_tmp2_ = g_content_type_get_icon (_tmp1_);
		_g_object_unref0 (_icon);
		_icon = _tmp2_;
	}
	_tmp3_ = _icon;
	if (_tmp3_ != NULL) {
		GtkIconTheme* _tmp4_ = NULL;
		GIcon* _tmp5_;
		gint _tmp6_ = 0;
		GtkIconInfo* _tmp7_ = NULL;
		_tmp4_ = gtk_icon_theme_get_default ();
		_tmp5_ = _icon;
		_tmp6_ = journal_utils_getIconSize ();
		_tmp7_ = gtk_icon_theme_lookup_by_gicon (_tmp4_, _tmp5_, _tmp6_, GTK_ICON_LOOKUP_FORCE_SVG);
		_gtk_icon_info_free0 (icon_info);
		icon_info = _tmp7_;
	}
	_tmp8_ = icon_info;
	if (_tmp8_ != NULL) {
		{
			GtkIconInfo* _tmp9_;
			GdkPixbuf* _tmp10_ = NULL;
			GdkPixbuf* _tmp11_;
			GdkPixbuf* _tmp12_;
			GdkPixbuf* _tmp13_;
			_tmp9_ = icon_info;
			_tmp10_ = gtk_icon_info_load_icon (_tmp9_, &_inner_error_);
			_tmp11_ = _tmp10_;
			if (_inner_error_ != NULL) {
				goto __catch3_g_error;
			}
			_tmp12_ = _tmp11_;
			journal_generic_activity_set_type_icon (self, _tmp12_);
			_g_object_unref0 (_tmp12_);
			_tmp13_ = self->priv->_type_icon;
			journal_generic_activity_set_thumb_icon (self, _tmp13_);
		}
		goto __finally3;
		__catch3_g_error:
		{
			GError* e = NULL;
			GError* _tmp14_;
			const gchar* _tmp15_;
			gchar* _tmp16_;
			gchar* _tmp17_;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp14_ = e;
			_tmp15_ = _tmp14_->message;
			_tmp16_ = g_strconcat ("Unable to load pixbuf: ", _tmp15_, NULL);
			_tmp17_ = _tmp16_;
			g_warning ("activities.vala:151: %s", _tmp17_);
			_g_free0 (_tmp17_);
			_g_error_free0 (e);
		}
		__finally3:
		if (_inner_error_ != NULL) {
			_gtk_icon_info_free0 (icon_info);
			_g_object_unref0 (_icon);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return;
		}
	}
	_gtk_icon_info_free0 (icon_info);
	_g_object_unref0 (_icon);
}


static void journal_generic_activity_get_thumb_data_free (gpointer _data) {
	JournalGenericActivityGetThumbData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (JournalGenericActivityGetThumbData, _data_);
}


static void journal_generic_activity_get_thumb (JournalGenericActivity* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	JournalGenericActivityGetThumbData* _data_;
	JournalGenericActivity* _tmp0_;
	_data_ = g_slice_new0 (JournalGenericActivityGetThumbData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, journal_generic_activity_get_thumb);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, journal_generic_activity_get_thumb_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	journal_generic_activity_get_thumb_co (_data_);
}


static void journal_generic_activity_get_thumb_finish (JournalGenericActivity* self, GAsyncResult* _res_) {
	JournalGenericActivityGetThumbData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static void journal_generic_activity_get_thumb_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	JournalGenericActivityGetThumbData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	journal_generic_activity_get_thumb_co (_data_);
}


static gboolean journal_generic_activity_get_thumb_co (JournalGenericActivityGetThumbData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		case 2:
		goto _state_2;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	_data_->_tmp0_ = _data_->self->priv->thumb_path;
	_data_->_tmp1_ = NULL;
	_data_->_tmp1_ = g_file_new_for_path (_data_->_tmp0_);
	_data_->file = _data_->_tmp1_;
	{
		_data_->_tmp2_ = _data_->file;
		_data_->_state_ = 1;
		g_file_read_async (_data_->_tmp2_, G_PRIORITY_DEFAULT, NULL, journal_generic_activity_get_thumb_ready, _data_);
		return FALSE;
		_state_1:
		_data_->_tmp3_ = NULL;
		_data_->_tmp3_ = g_file_read_finish (_data_->_tmp2_, _data_->_res_, &_data_->_inner_error_);
		_data_->stream = _data_->_tmp3_;
		if (_data_->_inner_error_ != NULL) {
			goto __catch4_g_error;
		}
		_data_->_tmp4_ = _data_->stream;
		_data_->_tmp5_ = 0;
		_data_->_tmp5_ = journal_utils_getIconSize ();
		_data_->_tmp6_ = 0;
		_data_->_tmp6_ = journal_utils_getIconSize ();
		_data_->_state_ = 2;
		gdk_pixbuf_new_from_stream_at_scale_async ((GInputStream*) _data_->_tmp4_, _data_->_tmp5_, _data_->_tmp6_, TRUE, NULL, journal_generic_activity_get_thumb_ready, _data_);
		return FALSE;
		_state_2:
		_data_->_tmp7_ = NULL;
		_data_->_tmp7_ = gdk_pixbuf_new_from_stream_finish (_data_->_res_, &_data_->_inner_error_);
		_data_->_tmp8_ = _data_->_tmp7_;
		if (_data_->_inner_error_ != NULL) {
			_g_object_unref0 (_data_->stream);
			goto __catch4_g_error;
		}
		_data_->_tmp9_ = _data_->_tmp8_;
		journal_generic_activity_set_thumb_icon (_data_->self, _data_->_tmp9_);
		_g_object_unref0 (_data_->_tmp9_);
		g_signal_emit_by_name (_data_->self, "thumb-loaded", _data_->self);
		_g_object_unref0 (_data_->stream);
	}
	goto __finally4;
	__catch4_g_error:
	{
		_data_->e = _data_->_inner_error_;
		_data_->_inner_error_ = NULL;
		_data_->_tmp10_ = _data_->self->priv->_uri;
		_data_->_tmp11_ = g_strconcat ("Unable to load pixbuf of", _data_->_tmp10_, NULL);
		_data_->_tmp12_ = _data_->_tmp11_;
		_data_->_tmp13_ = g_strconcat (_data_->_tmp12_, " : ", NULL);
		_data_->_tmp14_ = _data_->_tmp13_;
		_data_->_tmp15_ = _data_->e;
		_data_->_tmp16_ = _data_->_tmp15_->message;
		_data_->_tmp17_ = g_strconcat (_data_->_tmp14_, _data_->_tmp16_, NULL);
		_data_->_tmp18_ = _data_->_tmp17_;
		g_warning ("activities.vala:167: %s", _data_->_tmp18_);
		_g_free0 (_data_->_tmp18_);
		_g_free0 (_data_->_tmp14_);
		_g_free0 (_data_->_tmp12_);
		_g_error_free0 (_data_->e);
	}
	__finally4:
	if (_data_->_inner_error_ != NULL) {
		_g_object_unref0 (_data_->file);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
		g_clear_error (&_data_->_inner_error_);
		return FALSE;
	}
	_g_object_unref0 (_data_->file);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


const gchar* journal_generic_activity_get_uri (JournalGenericActivity* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_uri;
	result = _tmp0_;
	return result;
}


static void journal_generic_activity_set_uri (JournalGenericActivity* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_uri);
	self->priv->_uri = _tmp1_;
	g_object_notify ((GObject *) self, "uri");
}


const gchar* journal_generic_activity_get_title (JournalGenericActivity* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_title;
	result = _tmp0_;
	return result;
}


static void journal_generic_activity_set_title (JournalGenericActivity* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_title);
	self->priv->_title = _tmp1_;
	g_object_notify ((GObject *) self, "title");
}


GdkPixbuf* journal_generic_activity_get_type_icon (JournalGenericActivity* self) {
	GdkPixbuf* result;
	GdkPixbuf* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_type_icon;
	result = _tmp0_;
	return result;
}


static void journal_generic_activity_set_type_icon (JournalGenericActivity* self, GdkPixbuf* value) {
	GdkPixbuf* _tmp0_;
	GdkPixbuf* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_type_icon);
	self->priv->_type_icon = _tmp1_;
	g_object_notify ((GObject *) self, "type-icon");
}


GdkPixbuf* journal_generic_activity_get_thumb_icon (JournalGenericActivity* self) {
	GdkPixbuf* result;
	GdkPixbuf* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_thumb_icon;
	result = _tmp0_;
	return result;
}


static void journal_generic_activity_set_thumb_icon (JournalGenericActivity* self, GdkPixbuf* value) {
	GdkPixbuf* _tmp0_;
	GdkPixbuf* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->_thumb_icon);
	self->priv->_thumb_icon = _tmp1_;
	g_object_notify ((GObject *) self, "thumb-icon");
}


const gchar* journal_generic_activity_get_display_uri (JournalGenericActivity* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_display_uri;
	result = _tmp0_;
	return result;
}


static void journal_generic_activity_set_display_uri (JournalGenericActivity* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_display_uri);
	self->priv->_display_uri = _tmp1_;
	g_object_notify ((GObject *) self, "display-uri");
}


gint64 journal_generic_activity_get_time (JournalGenericActivity* self) {
	gint64 result;
	gint64 _tmp0_;
	g_return_val_if_fail (self != NULL, 0LL);
	_tmp0_ = self->priv->_time;
	result = _tmp0_;
	return result;
}


static void journal_generic_activity_set_time (JournalGenericActivity* self, gint64 value) {
	gint64 _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_time = _tmp0_;
	g_object_notify ((GObject *) self, "time");
}


gboolean journal_generic_activity_get_selected (JournalGenericActivity* self) {
	gboolean result;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_selected;
	result = _tmp0_;
	return result;
}


void journal_generic_activity_set_selected (JournalGenericActivity* self, gboolean value) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_selected = _tmp0_;
	g_object_notify ((GObject *) self, "selected");
}


const gchar* journal_generic_activity_get_mimetype (JournalGenericActivity* self) {
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_mimetype;
	result = _tmp0_;
	return result;
}


static void journal_generic_activity_set_mimetype (JournalGenericActivity* self, const gchar* value) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_mimetype);
	self->priv->_mimetype = _tmp1_;
	g_object_notify ((GObject *) self, "mimetype");
}


static void journal_generic_activity_class_init (JournalGenericActivityClass * klass) {
	journal_generic_activity_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (JournalGenericActivityPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_journal_generic_activity_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_journal_generic_activity_set_property;
	G_OBJECT_CLASS (klass)->finalize = journal_generic_activity_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_GENERIC_ACTIVITY_URI, g_param_spec_string ("uri", "uri", "uri", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_GENERIC_ACTIVITY_TITLE, g_param_spec_string ("title", "title", "title", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_GENERIC_ACTIVITY_TYPE_ICON, g_param_spec_object ("type-icon", "type-icon", "type-icon", GDK_TYPE_PIXBUF, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_GENERIC_ACTIVITY_THUMB_ICON, g_param_spec_object ("thumb-icon", "thumb-icon", "thumb-icon", GDK_TYPE_PIXBUF, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_GENERIC_ACTIVITY_DISPLAY_URI, g_param_spec_string ("display-uri", "display-uri", "display-uri", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_GENERIC_ACTIVITY_TIME, g_param_spec_int64 ("time", "time", "time", G_MININT64, G_MAXINT64, 0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_GENERIC_ACTIVITY_SELECTED, g_param_spec_boolean ("selected", "selected", "selected", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_GENERIC_ACTIVITY_MIMETYPE, g_param_spec_string ("mimetype", "mimetype", "mimetype", NULL, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("thumb_loaded", JOURNAL_TYPE_GENERIC_ACTIVITY, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__OBJECT, G_TYPE_NONE, 1, JOURNAL_TYPE_GENERIC_ACTIVITY);
}


static void journal_generic_activity_instance_init (JournalGenericActivity * self) {
	self->priv = JOURNAL_GENERIC_ACTIVITY_GET_PRIVATE (self);
}


static void journal_generic_activity_finalize (GObject* obj) {
	JournalGenericActivity * self;
	self = JOURNAL_GENERIC_ACTIVITY (obj);
	_g_free0 (self->priv->_uri);
	_g_free0 (self->priv->_title);
	_g_object_unref0 (self->priv->_type_icon);
	_g_object_unref0 (self->priv->_thumb_icon);
	_g_free0 (self->priv->_display_uri);
	_g_free0 (self->priv->_mimetype);
	_g_object_unref0 (self->priv->subject);
	_g_free0 (self->priv->thumb_path);
	G_OBJECT_CLASS (journal_generic_activity_parent_class)->finalize (obj);
}


GType journal_generic_activity_get_type (void) {
	static volatile gsize journal_generic_activity_type_id__volatile = 0;
	if (g_once_init_enter (&journal_generic_activity_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JournalGenericActivityClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) journal_generic_activity_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JournalGenericActivity), 0, (GInstanceInitFunc) journal_generic_activity_instance_init, NULL };
		GType journal_generic_activity_type_id;
		journal_generic_activity_type_id = g_type_register_static (G_TYPE_OBJECT, "JournalGenericActivity", &g_define_type_info, 0);
		g_once_init_leave (&journal_generic_activity_type_id__volatile, journal_generic_activity_type_id);
	}
	return journal_generic_activity_type_id__volatile;
}


static void _vala_journal_generic_activity_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	JournalGenericActivity * self;
	self = JOURNAL_GENERIC_ACTIVITY (object);
	switch (property_id) {
		case JOURNAL_GENERIC_ACTIVITY_URI:
		g_value_set_string (value, journal_generic_activity_get_uri (self));
		break;
		case JOURNAL_GENERIC_ACTIVITY_TITLE:
		g_value_set_string (value, journal_generic_activity_get_title (self));
		break;
		case JOURNAL_GENERIC_ACTIVITY_TYPE_ICON:
		g_value_set_object (value, journal_generic_activity_get_type_icon (self));
		break;
		case JOURNAL_GENERIC_ACTIVITY_THUMB_ICON:
		g_value_set_object (value, journal_generic_activity_get_thumb_icon (self));
		break;
		case JOURNAL_GENERIC_ACTIVITY_DISPLAY_URI:
		g_value_set_string (value, journal_generic_activity_get_display_uri (self));
		break;
		case JOURNAL_GENERIC_ACTIVITY_TIME:
		g_value_set_int64 (value, journal_generic_activity_get_time (self));
		break;
		case JOURNAL_GENERIC_ACTIVITY_SELECTED:
		g_value_set_boolean (value, journal_generic_activity_get_selected (self));
		break;
		case JOURNAL_GENERIC_ACTIVITY_MIMETYPE:
		g_value_set_string (value, journal_generic_activity_get_mimetype (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_journal_generic_activity_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	JournalGenericActivity * self;
	self = JOURNAL_GENERIC_ACTIVITY (object);
	switch (property_id) {
		case JOURNAL_GENERIC_ACTIVITY_URI:
		journal_generic_activity_set_uri (self, g_value_get_string (value));
		break;
		case JOURNAL_GENERIC_ACTIVITY_TITLE:
		journal_generic_activity_set_title (self, g_value_get_string (value));
		break;
		case JOURNAL_GENERIC_ACTIVITY_TYPE_ICON:
		journal_generic_activity_set_type_icon (self, g_value_get_object (value));
		break;
		case JOURNAL_GENERIC_ACTIVITY_THUMB_ICON:
		journal_generic_activity_set_thumb_icon (self, g_value_get_object (value));
		break;
		case JOURNAL_GENERIC_ACTIVITY_DISPLAY_URI:
		journal_generic_activity_set_display_uri (self, g_value_get_string (value));
		break;
		case JOURNAL_GENERIC_ACTIVITY_TIME:
		journal_generic_activity_set_time (self, g_value_get_int64 (value));
		break;
		case JOURNAL_GENERIC_ACTIVITY_SELECTED:
		journal_generic_activity_set_selected (self, g_value_get_boolean (value));
		break;
		case JOURNAL_GENERIC_ACTIVITY_MIMETYPE:
		journal_generic_activity_set_mimetype (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


JournalActivityModel* journal_activity_model_construct (GType object_type) {
	JournalActivityModel * self = NULL;
	GeeArrayList* _tmp0_;
	GtkListStore* _tmp1_;
	GtkListStore* _tmp2_;
	self = (JournalActivityModel*) g_object_new (object_type, NULL);
	_tmp0_ = gee_array_list_new (JOURNAL_TYPE_GENERIC_ACTIVITY, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->_activities);
	self->priv->_activities = _tmp0_;
	_tmp1_ = gtk_list_store_new (6, G_TYPE_STRING, G_TYPE_STRING, GDK_TYPE_PIXBUF, G_TYPE_STRING, G_TYPE_INT64, G_TYPE_BOOLEAN);
	_g_object_unref0 (self->priv->model);
	self->priv->model = _tmp1_;
	_tmp2_ = self->priv->model;
	gtk_tree_sortable_set_sort_column_id ((GtkTreeSortable*) _tmp2_, (gint) GD_MAIN_COLUMN_TIME, GTK_SORT_DESCENDING);
	return self;
}


JournalActivityModel* journal_activity_model_new (void) {
	return journal_activity_model_construct (JOURNAL_TYPE_ACTIVITY_MODEL);
}


void journal_activity_model_clear (JournalActivityModel* self) {
	GtkListStore* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->model;
	gtk_list_store_clear (_tmp0_);
}


static void __lambda3_ (JournalActivityModel* self, JournalGenericActivity* activity) {
	JournalGenericActivity* _tmp0_;
	g_return_if_fail (activity != NULL);
	_tmp0_ = activity;
	journal_activity_model_update_icon_for_activity (self, _tmp0_);
}


static void ___lambda3__journal_generic_activity_thumb_loaded (JournalGenericActivity* _sender, JournalGenericActivity* activity, gpointer self) {
	__lambda3_ (self, activity);
}


void journal_activity_model_add_activity (JournalActivityModel* self, JournalGenericActivity* activity) {
	GtkTreeIter iter = {0};
	GtkListStore* _tmp0_;
	GtkTreeIter _tmp1_ = {0};
	GtkListStore* _tmp2_;
	GtkTreeIter _tmp3_;
	JournalGenericActivity* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	JournalGenericActivity* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	JournalGenericActivity* _tmp10_;
	GdkPixbuf* _tmp11_;
	GdkPixbuf* _tmp12_;
	JournalGenericActivity* _tmp13_;
	const gchar* _tmp14_;
	const gchar* _tmp15_;
	JournalGenericActivity* _tmp16_;
	gint64 _tmp17_;
	gint64 _tmp18_;
	JournalGenericActivity* _tmp19_;
	gboolean _tmp20_;
	gboolean _tmp21_;
	JournalGenericActivity* _tmp22_;
	GeeArrayList* _tmp23_;
	GeeArrayList* _tmp24_;
	JournalGenericActivity* _tmp25_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (activity != NULL);
	_tmp0_ = self->priv->model;
	gtk_list_store_append (_tmp0_, &_tmp1_);
	iter = _tmp1_;
	_tmp2_ = self->priv->model;
	_tmp3_ = iter;
	_tmp4_ = activity;
	_tmp5_ = journal_generic_activity_get_uri (_tmp4_);
	_tmp6_ = _tmp5_;
	_tmp7_ = activity;
	_tmp8_ = journal_generic_activity_get_title (_tmp7_);
	_tmp9_ = _tmp8_;
	_tmp10_ = activity;
	_tmp11_ = journal_generic_activity_get_thumb_icon (_tmp10_);
	_tmp12_ = _tmp11_;
	_tmp13_ = activity;
	_tmp14_ = journal_generic_activity_get_display_uri (_tmp13_);
	_tmp15_ = _tmp14_;
	_tmp16_ = activity;
	_tmp17_ = journal_generic_activity_get_time (_tmp16_);
	_tmp18_ = _tmp17_;
	_tmp19_ = activity;
	_tmp20_ = journal_generic_activity_get_selected (_tmp19_);
	_tmp21_ = _tmp20_;
	gtk_list_store_set (_tmp2_, &_tmp3_, 0, _tmp6_, 1, _tmp9_, 2, _tmp12_, 3, _tmp15_, 4, _tmp18_, 5, _tmp21_, -1);
	_tmp22_ = activity;
	g_signal_connect_object (_tmp22_, "thumb-loaded", (GCallback) ___lambda3__journal_generic_activity_thumb_loaded, self, 0);
	_tmp23_ = journal_activity_model_get_activities (self);
	_tmp24_ = _tmp23_;
	_tmp25_ = activity;
	gee_abstract_collection_add ((GeeAbstractCollection*) _tmp24_, _tmp25_);
}


static Block1Data* block1_data_ref (Block1Data* _data1_) {
	g_atomic_int_inc (&_data1_->_ref_count_);
	return _data1_;
}


static void block1_data_unref (void * _userdata_) {
	Block1Data* _data1_;
	_data1_ = (Block1Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data1_->_ref_count_)) {
		JournalActivityModel * self;
		self = _data1_->self;
		_g_object_unref0 (_data1_->activity);
		_g_object_unref0 (self);
		g_slice_free (Block1Data, _data1_);
	}
}


static gboolean __lambda5_ (Block1Data* _data1_, GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter) {
	JournalActivityModel * self;
	gboolean result = FALSE;
	GValue uri = {0};
	GtkListStore* _tmp0_;
	GtkTreeIter _tmp1_;
	GValue _tmp2_ = {0};
	const gchar* _tmp3_ = NULL;
	JournalGenericActivity* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	self = _data1_->self;
	g_return_val_if_fail (model != NULL, FALSE);
	g_return_val_if_fail (path != NULL, FALSE);
	g_return_val_if_fail (iter != NULL, FALSE);
	_tmp0_ = self->priv->model;
	_tmp1_ = *iter;
	gtk_tree_model_get_value ((GtkTreeModel*) _tmp0_, &_tmp1_, 0, &_tmp2_);
	G_IS_VALUE (&uri) ? (g_value_unset (&uri), NULL) : NULL;
	uri = _tmp2_;
	_tmp3_ = g_value_get_string (&uri);
	_tmp4_ = _data1_->activity;
	_tmp5_ = journal_generic_activity_get_uri (_tmp4_);
	_tmp6_ = _tmp5_;
	if (g_strcmp0 (_tmp3_, _tmp6_) == 0) {
		GtkListStore* _tmp7_;
		GtkTreeIter _tmp8_;
		_tmp7_ = self->priv->model;
		_tmp8_ = *iter;
		gtk_list_store_remove (_tmp7_, &_tmp8_);
		result = TRUE;
		G_IS_VALUE (&uri) ? (g_value_unset (&uri), NULL) : NULL;
		return result;
	}
	result = FALSE;
	G_IS_VALUE (&uri) ? (g_value_unset (&uri), NULL) : NULL;
	return result;
}


static gboolean ___lambda5__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self) {
	gboolean result;
	result = __lambda5_ (self, model, path, iter);
	return result;
}


void journal_activity_model_remove_activity (JournalActivityModel* self, JournalGenericActivity* activity) {
	Block1Data* _data1_;
	JournalGenericActivity* _tmp0_;
	JournalGenericActivity* _tmp1_;
	GtkListStore* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (activity != NULL);
	_data1_ = g_slice_new0 (Block1Data);
	_data1_->_ref_count_ = 1;
	_data1_->self = g_object_ref (self);
	_tmp0_ = activity;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_data1_->activity = _tmp1_;
	_tmp2_ = self->priv->model;
	gtk_tree_model_foreach ((GtkTreeModel*) _tmp2_, ___lambda5__gtk_tree_model_foreach_func, _data1_);
	block1_data_unref (_data1_);
	_data1_ = NULL;
}


static Block2Data* block2_data_ref (Block2Data* _data2_) {
	g_atomic_int_inc (&_data2_->_ref_count_);
	return _data2_;
}


static void block2_data_unref (void * _userdata_) {
	Block2Data* _data2_;
	_data2_ = (Block2Data*) _userdata_;
	if (g_atomic_int_dec_and_test (&_data2_->_ref_count_)) {
		JournalActivityModel * self;
		self = _data2_->self;
		_g_object_unref0 (_data2_->activity);
		_g_object_unref0 (self);
		g_slice_free (Block2Data, _data2_);
	}
}


static gboolean __lambda4_ (Block2Data* _data2_, GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter) {
	JournalActivityModel * self;
	gboolean result = FALSE;
	GValue uri = {0};
	GtkListStore* _tmp0_;
	GtkTreeIter _tmp1_;
	GValue _tmp2_ = {0};
	const gchar* _tmp3_ = NULL;
	JournalGenericActivity* _tmp4_;
	const gchar* _tmp5_;
	const gchar* _tmp6_;
	self = _data2_->self;
	g_return_val_if_fail (model != NULL, FALSE);
	g_return_val_if_fail (path != NULL, FALSE);
	g_return_val_if_fail (iter != NULL, FALSE);
	_tmp0_ = self->priv->model;
	_tmp1_ = *iter;
	gtk_tree_model_get_value ((GtkTreeModel*) _tmp0_, &_tmp1_, 0, &_tmp2_);
	G_IS_VALUE (&uri) ? (g_value_unset (&uri), NULL) : NULL;
	uri = _tmp2_;
	_tmp3_ = g_value_get_string (&uri);
	_tmp4_ = _data2_->activity;
	_tmp5_ = journal_generic_activity_get_uri (_tmp4_);
	_tmp6_ = _tmp5_;
	if (g_strcmp0 (_tmp3_, _tmp6_) == 0) {
		GtkListStore* _tmp7_;
		GtkTreeIter _tmp8_;
		JournalGenericActivity* _tmp9_;
		GdkPixbuf* _tmp10_;
		GdkPixbuf* _tmp11_;
		GValue _tmp12_ = {0};
		_tmp7_ = self->priv->model;
		_tmp8_ = *iter;
		_tmp9_ = _data2_->activity;
		_tmp10_ = journal_generic_activity_get_thumb_icon (_tmp9_);
		_tmp11_ = _tmp10_;
		g_value_init (&_tmp12_, GDK_TYPE_PIXBUF);
		g_value_set_object (&_tmp12_, _tmp11_);
		gtk_list_store_set_value (_tmp7_, &_tmp8_, 2, &_tmp12_);
		G_IS_VALUE (&_tmp12_) ? (g_value_unset (&_tmp12_), NULL) : NULL;
		result = TRUE;
		G_IS_VALUE (&uri) ? (g_value_unset (&uri), NULL) : NULL;
		return result;
	}
	result = FALSE;
	G_IS_VALUE (&uri) ? (g_value_unset (&uri), NULL) : NULL;
	return result;
}


static gboolean ___lambda4__gtk_tree_model_foreach_func (GtkTreeModel* model, GtkTreePath* path, GtkTreeIter* iter, gpointer self) {
	gboolean result;
	result = __lambda4_ (self, model, path, iter);
	return result;
}


static void journal_activity_model_update_icon_for_activity (JournalActivityModel* self, JournalGenericActivity* activity) {
	Block2Data* _data2_;
	JournalGenericActivity* _tmp0_;
	JournalGenericActivity* _tmp1_;
	GtkListStore* _tmp2_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (activity != NULL);
	_data2_ = g_slice_new0 (Block2Data);
	_data2_->_ref_count_ = 1;
	_data2_->self = g_object_ref (self);
	_tmp0_ = activity;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_data2_->activity = _tmp1_;
	_tmp2_ = self->priv->model;
	gtk_tree_model_foreach ((GtkTreeModel*) _tmp2_, ___lambda4__gtk_tree_model_foreach_func, _data2_);
	block2_data_unref (_data2_);
	_data2_ = NULL;
}


GtkListStore* journal_activity_model_get_model (JournalActivityModel* self) {
	GtkListStore* result = NULL;
	GtkListStore* _tmp0_;
	GtkListStore* _tmp1_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->model;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	result = _tmp1_;
	return result;
}


GeeArrayList* journal_activity_model_get_activities (JournalActivityModel* self) {
	GeeArrayList* result;
	GeeArrayList* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_activities;
	result = _tmp0_;
	return result;
}


static void journal_activity_model_class_init (JournalActivityModelClass * klass) {
	journal_activity_model_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (JournalActivityModelPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_journal_activity_model_get_property;
	G_OBJECT_CLASS (klass)->finalize = journal_activity_model_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_ACTIVITY_MODEL_ACTIVITIES, g_param_spec_object ("activities", "activities", "activities", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void journal_activity_model_instance_init (JournalActivityModel * self) {
	self->priv = JOURNAL_ACTIVITY_MODEL_GET_PRIVATE (self);
}


static void journal_activity_model_finalize (GObject* obj) {
	JournalActivityModel * self;
	self = JOURNAL_ACTIVITY_MODEL (obj);
	_g_object_unref0 (self->priv->model);
	_g_object_unref0 (self->priv->_activities);
	G_OBJECT_CLASS (journal_activity_model_parent_class)->finalize (obj);
}


GType journal_activity_model_get_type (void) {
	static volatile gsize journal_activity_model_type_id__volatile = 0;
	if (g_once_init_enter (&journal_activity_model_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JournalActivityModelClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) journal_activity_model_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JournalActivityModel), 0, (GInstanceInitFunc) journal_activity_model_instance_init, NULL };
		GType journal_activity_model_type_id;
		journal_activity_model_type_id = g_type_register_static (G_TYPE_OBJECT, "JournalActivityModel", &g_define_type_info, 0);
		g_once_init_leave (&journal_activity_model_type_id__volatile, journal_activity_model_type_id);
	}
	return journal_activity_model_type_id__volatile;
}


static void _vala_journal_activity_model_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	JournalActivityModel * self;
	self = JOURNAL_ACTIVITY_MODEL (object);
	switch (property_id) {
		case JOURNAL_ACTIVITY_MODEL_ACTIVITIES:
		g_value_set_object (value, journal_activity_model_get_activities (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}


static gint _vala_array_length (gpointer array) {
	int length;
	length = 0;
	if (array) {
		while (((gpointer*) array)[length]) {
			length++;
		}
	}
	return length;
}



