/* app.c generated by valac 0.16.0, the Vala compiler
 * generated from app.vala, do not modify */

/* This file is part of GNOME Activity Journal.*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <clutter-gtk/clutter-gtk.h>
#include <clutter/clutter.h>
#include <gio/gio.h>
#include <gd-main-toolbar.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <config.h>
#include <gdk/gdk.h>


#define JOURNAL_TYPE_APP (journal_app_get_type ())
#define JOURNAL_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_APP, JournalApp))
#define JOURNAL_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_APP, JournalAppClass))
#define JOURNAL_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_APP))
#define JOURNAL_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_APP))
#define JOURNAL_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_APP, JournalAppClass))

typedef struct _JournalApp JournalApp;
typedef struct _JournalAppClass JournalAppClass;
typedef struct _JournalAppPrivate JournalAppPrivate;

#define JOURNAL_TYPE_LOADING_ACTOR (journal_loading_actor_get_type ())
#define JOURNAL_LOADING_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_LOADING_ACTOR, JournalLoadingActor))
#define JOURNAL_LOADING_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_LOADING_ACTOR, JournalLoadingActorClass))
#define JOURNAL_IS_LOADING_ACTOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_LOADING_ACTOR))
#define JOURNAL_IS_LOADING_ACTOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_LOADING_ACTOR))
#define JOURNAL_LOADING_ACTOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_LOADING_ACTOR, JournalLoadingActorClass))

typedef struct _JournalLoadingActor JournalLoadingActor;
typedef struct _JournalLoadingActorClass JournalLoadingActorClass;

#define JOURNAL_TYPE_DAY_VIEW (journal_day_view_get_type ())
#define JOURNAL_DAY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_DAY_VIEW, JournalDayView))
#define JOURNAL_DAY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_DAY_VIEW, JournalDayViewClass))
#define JOURNAL_IS_DAY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_DAY_VIEW))
#define JOURNAL_IS_DAY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_DAY_VIEW))
#define JOURNAL_DAY_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_DAY_VIEW, JournalDayViewClass))

typedef struct _JournalDayView JournalDayView;
typedef struct _JournalDayViewClass JournalDayViewClass;

#define JOURNAL_TYPE_CLUTTER_ROUND_BOX_VIEW (journal_clutter_round_box_view_get_type ())
#define JOURNAL_CLUTTER_ROUND_BOX_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_CLUTTER_ROUND_BOX_VIEW, JournalClutterRoundBoxView))
#define JOURNAL_CLUTTER_ROUND_BOX_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_CLUTTER_ROUND_BOX_VIEW, JournalClutterRoundBoxViewClass))
#define JOURNAL_IS_CLUTTER_ROUND_BOX_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_CLUTTER_ROUND_BOX_VIEW))
#define JOURNAL_IS_CLUTTER_ROUND_BOX_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_CLUTTER_ROUND_BOX_VIEW))
#define JOURNAL_CLUTTER_ROUND_BOX_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_CLUTTER_ROUND_BOX_VIEW, JournalClutterRoundBoxViewClass))

typedef struct _JournalClutterRoundBoxView JournalClutterRoundBoxView;
typedef struct _JournalClutterRoundBoxViewClass JournalClutterRoundBoxViewClass;

#define JOURNAL_TYPE_GTK_ROUND_BOX_VIEW (journal_gtk_round_box_view_get_type ())
#define JOURNAL_GTK_ROUND_BOX_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_GTK_ROUND_BOX_VIEW, JournalGtkRoundBoxView))
#define JOURNAL_GTK_ROUND_BOX_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_GTK_ROUND_BOX_VIEW, JournalGtkRoundBoxViewClass))
#define JOURNAL_IS_GTK_ROUND_BOX_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_GTK_ROUND_BOX_VIEW))
#define JOURNAL_IS_GTK_ROUND_BOX_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_GTK_ROUND_BOX_VIEW))
#define JOURNAL_GTK_ROUND_BOX_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_GTK_ROUND_BOX_VIEW, JournalGtkRoundBoxViewClass))

typedef struct _JournalGtkRoundBoxView JournalGtkRoundBoxView;
typedef struct _JournalGtkRoundBoxViewClass JournalGtkRoundBoxViewClass;

#define JOURNAL_TYPE_REMINDER_VIEW (journal_reminder_view_get_type ())
#define JOURNAL_REMINDER_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_REMINDER_VIEW, JournalReminderView))
#define JOURNAL_REMINDER_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_REMINDER_VIEW, JournalReminderViewClass))
#define JOURNAL_IS_REMINDER_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_REMINDER_VIEW))
#define JOURNAL_IS_REMINDER_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_REMINDER_VIEW))
#define JOURNAL_REMINDER_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_REMINDER_VIEW, JournalReminderViewClass))

typedef struct _JournalReminderView JournalReminderView;
typedef struct _JournalReminderViewClass JournalReminderViewClass;

#define JOURNAL_TYPE_REVEALER (journal_revealer_get_type ())
#define JOURNAL_REVEALER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_REVEALER, JournalRevealer))
#define JOURNAL_REVEALER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_REVEALER, JournalRevealerClass))
#define JOURNAL_IS_REVEALER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_REVEALER))
#define JOURNAL_IS_REVEALER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_REVEALER))
#define JOURNAL_REVEALER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_REVEALER, JournalRevealerClass))

typedef struct _JournalRevealer JournalRevealer;
typedef struct _JournalRevealerClass JournalRevealerClass;

#define JOURNAL_TYPE_ZEITGEIST_BACKEND (journal_zeitgeist_backend_get_type ())
#define JOURNAL_ZEITGEIST_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackend))
#define JOURNAL_ZEITGEIST_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackendClass))
#define JOURNAL_IS_ZEITGEIST_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND))
#define JOURNAL_IS_ZEITGEIST_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_ZEITGEIST_BACKEND))
#define JOURNAL_ZEITGEIST_BACKEND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackendClass))

typedef struct _JournalZeitgeistBackend JournalZeitgeistBackend;
typedef struct _JournalZeitgeistBackendClass JournalZeitgeistBackendClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_variant_unref0(var) ((var == NULL) ? NULL : (var = (g_variant_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

struct _JournalApp {
	GObject parent_instance;
	JournalAppPrivate * priv;
	GtkApplicationWindow* window;
	GtkNotebook* notebook;
	GtkBox* main_box;
	GtkClutterEmbed* embed;
	ClutterStage* stage;
	ClutterActor* box;
	GSimpleAction* action_fullscreen;
	guint duration;
};

struct _JournalAppClass {
	GObjectClass parent_class;
};

struct _JournalAppPrivate {
	GtkApplication* application;
	ClutterBoxLayout* box_table;
	JournalLoadingActor* loading_actor;
	JournalDayView* day_view;
	JournalClutterRoundBoxView* crv;
	JournalGtkRoundBoxView* grv;
	JournalReminderView* reminder_view;
	JournalRevealer* revealer;
	GdMainToolbar* main_toolbar;
	JournalZeitgeistBackend* _backend;
};


static gpointer journal_app_parent_class = NULL;
extern GSettings* journal_utils_settings;

GType journal_app_get_type (void) G_GNUC_CONST;
GType journal_loading_actor_get_type (void) G_GNUC_CONST;
GType journal_day_view_get_type (void) G_GNUC_CONST;
GType journal_clutter_round_box_view_get_type (void) G_GNUC_CONST;
GType journal_gtk_round_box_view_get_type (void) G_GNUC_CONST;
GType journal_reminder_view_get_type (void) G_GNUC_CONST;
GType journal_revealer_get_type (void) G_GNUC_CONST;
GType journal_zeitgeist_backend_get_type (void) G_GNUC_CONST;
#define JOURNAL_APP_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JOURNAL_TYPE_APP, JournalAppPrivate))
enum  {
	JOURNAL_APP_DUMMY_PROPERTY,
	JOURNAL_APP_ACTOR,
	JOURNAL_APP_FULLSCREEN,
	JOURNAL_APP_BACKEND
};
JournalApp* journal_app_new (void);
JournalApp* journal_app_construct (GType object_type);
JournalZeitgeistBackend* journal_zeitgeist_backend_new (void);
JournalZeitgeistBackend* journal_zeitgeist_backend_construct (GType object_type);
static void __lambda16_ (JournalApp* self);
gboolean journal_app_quit (JournalApp* self);
static void ___lambda16__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda17_ (JournalApp* self);
void journal_app_set_fullscreen (JournalApp* self, gboolean value);
static void ___lambda17__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda18_ (JournalApp* self);
static void ___lambda18__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self);
static void __lambda19_ (JournalApp* self, GApplication* app);
static void journal_app_setup_ui (JournalApp* self);
static void ___lambda19__g_application_startup (GApplication* _sender, gpointer self);
static void __lambda23_ (JournalApp* self, GApplication* app);
static void ___lambda23__g_application_activate (GApplication* _sender, gpointer self);
gint journal_app_run (JournalApp* self);
static void journal_app_save_window_geometry (JournalApp* self);
static gboolean journal_app_get_maximized (JournalApp* self);
static GVariant* _variant_new1 (gint* value, gint value_length1);
static GVariant* _variant_new2 (gint* value, gint value_length1);
static gint _variant_get3 (GVariant* value);
static gint _variant_get4 (GVariant* value);
static gint _variant_get5 (GVariant* value);
static gint _variant_get6 (GVariant* value);
static gboolean __lambda20_ (JournalApp* self);
gboolean journal_app_get_fullscreen (JournalApp* self);
static gboolean ___lambda20__gtk_widget_window_state_event (GtkWidget* _sender, GdkEventWindowState* event, gpointer self);
static void __lambda21_ (JournalApp* self, gboolean mode);
void journal_day_view_set_selection_mode (JournalDayView* self, gboolean mode);
static void ___lambda21__gd_main_toolbar_selection_mode_request (GdMainToolbar* _sender, gboolean object, gpointer self);
JournalDayView* journal_day_view_new (JournalApp* app, gint num_days);
JournalDayView* journal_day_view_construct (GType object_type, JournalApp* app, gint num_days);
void journal_utils_gdk_rgba_to_clutter_color (GdkRGBA* gdk_rgba, ClutterColor* result);
void journal_utils_get_journal_bg_color (GdkRGBA* result);
static gboolean __lambda22_ (JournalApp* self);
static gboolean ___lambda22__gtk_widget_delete_event (GtkWidget* _sender, GdkEventAny* event, gpointer self);
static gboolean journal_app_on_key_pressed (JournalApp* self, GtkWidget* widget, GdkEventKey* event);
static gboolean _journal_app_on_key_pressed_gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self);
JournalClutterRoundBoxView* journal_clutter_round_box_view_new (JournalApp* app);
JournalClutterRoundBoxView* journal_clutter_round_box_view_construct (GType object_type, JournalApp* app);
JournalGtkRoundBoxView* journal_gtk_round_box_view_new (JournalApp* app);
JournalGtkRoundBoxView* journal_gtk_round_box_view_construct (GType object_type, JournalApp* app);
JournalLoadingActor* journal_loading_actor_new (JournalApp* app);
JournalLoadingActor* journal_loading_actor_construct (GType object_type, JournalApp* app);
void journal_loading_actor_start (JournalLoadingActor* self);
#define JOURNAL_UTILS_F11_KEY ((guint) 0xffc8)
ClutterActor* journal_app_get_actor (JournalApp* self);
JournalZeitgeistBackend* journal_app_get_backend (JournalApp* self);
static void journal_app_finalize (GObject* obj);
static void _vala_journal_app_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_journal_app_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static void __lambda16_ (JournalApp* self) {
	journal_app_quit (self);
}


static void ___lambda16__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda16_ (self);
}


static void __lambda17_ (JournalApp* self) {
	journal_app_set_fullscreen (self, TRUE);
}


static void ___lambda17__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda17_ (self);
}


static void __lambda18_ (JournalApp* self) {
	gchar* _tmp0_;
	gchar** _tmp1_ = NULL;
	gchar** authors;
	gint authors_length1;
	gint _authors_size_;
	gchar* _tmp2_;
	gchar** _tmp3_ = NULL;
	gchar** artists;
	gint artists_length1;
	gint _artists_size_;
	GtkApplicationWindow* _tmp4_;
	const gchar* _tmp5_ = NULL;
	const gchar* _tmp6_ = NULL;
	_tmp0_ = g_strdup ("Stefano Candori <scandori@gnome.org>");
	_tmp1_ = g_new0 (gchar*, 1 + 1);
	_tmp1_[0] = _tmp0_;
	authors = _tmp1_;
	authors_length1 = 1;
	_authors_size_ = authors_length1;
	_tmp2_ = g_strdup ("Stefano Candori <scandori@gnome.org>");
	_tmp3_ = g_new0 (gchar*, 1 + 1);
	_tmp3_[0] = _tmp2_;
	artists = _tmp3_;
	artists_length1 = 1;
	_artists_size_ = artists_length1;
	_tmp4_ = self->window;
	_tmp5_ = _ ("translator-credits");
	_tmp6_ = _ ("A simple GNOME 3 journal application ");
	gtk_show_about_dialog ((GtkWindow*) _tmp4_, "artists", artists, "authors", authors, "translator-credits", _tmp5_, "comments", _tmp6_, "copyright", "Copyright 2012 Stefano Candori", "license-type", GTK_LICENSE_LGPL_2_1, "logo-icon-name", "gnome-activity-journal", "version", PACKAGE_VERSION, "website", "http://live.gnome.org/GnomeActivityJournal", "wrap-license", TRUE, NULL);
	artists = (_vala_array_free (artists, artists_length1, (GDestroyNotify) g_free), NULL);
	authors = (_vala_array_free (authors, authors_length1, (GDestroyNotify) g_free), NULL);
}


static void ___lambda18__g_simple_action_activate (GSimpleAction* _sender, GVariant* parameter, gpointer self) {
	__lambda18_ (self);
}


static void __lambda19_ (JournalApp* self, GApplication* app) {
	GMenu* _tmp0_;
	GMenu* menu;
	const gchar* _tmp1_ = NULL;
	GMenu* _tmp2_;
	GMenu* display_section;
	const gchar* _tmp3_ = NULL;
	const gchar* _tmp4_ = NULL;
	const gchar* _tmp5_ = NULL;
	GtkApplication* _tmp6_;
	GSettings* _tmp7_;
	gint _tmp8_ = 0;
	g_return_if_fail (app != NULL);
	_tmp0_ = g_menu_new ();
	menu = _tmp0_;
	_tmp1_ = _ ("New");
	g_menu_append (menu, _tmp1_, "app.new");
	_tmp2_ = g_menu_new ();
	display_section = _tmp2_;
	_tmp3_ = _ ("Fullscreen");
	g_menu_append (display_section, _tmp3_, "app.display.fullscreen");
	g_menu_append_section (menu, NULL, (GMenuModel*) display_section);
	_tmp4_ = _ ("About Activity Journal");
	g_menu_append (menu, _tmp4_, "app.about");
	_tmp5_ = _ ("Quit");
	g_menu_append (menu, _tmp5_, "app.quit");
	_tmp6_ = self->priv->application;
	gtk_application_set_app_menu (_tmp6_, (GMenuModel*) menu);
	_tmp7_ = journal_utils_settings;
	_tmp8_ = g_settings_get_int (_tmp7_, "animation-duration");
	self->duration = (guint) _tmp8_;
	journal_app_setup_ui (self);
	_g_object_unref0 (display_section);
	_g_object_unref0 (menu);
}


static void ___lambda19__g_application_startup (GApplication* _sender, gpointer self) {
	__lambda19_ (self, _sender);
}


static void __lambda23_ (JournalApp* self, GApplication* app) {
	GtkApplicationWindow* _tmp0_;
	g_return_if_fail (app != NULL);
	_tmp0_ = self->window;
	gtk_window_present ((GtkWindow*) _tmp0_);
}


static void ___lambda23__g_application_activate (GApplication* _sender, gpointer self) {
	__lambda23_ (self, _sender);
}


JournalApp* journal_app_construct (GType object_type) {
	JournalApp * self = NULL;
	GtkApplication* _tmp0_;
	JournalZeitgeistBackend* _tmp1_;
	GSimpleAction* _tmp2_;
	GSimpleAction* action;
	GSimpleAction* _tmp3_;
	GtkApplication* _tmp4_;
	GSimpleAction* _tmp5_;
	GSimpleAction* _tmp6_;
	GSimpleAction* _tmp7_;
	GtkApplication* _tmp8_;
	GSimpleAction* _tmp9_;
	GSimpleAction* _tmp10_;
	GSimpleAction* _tmp11_;
	GtkApplication* _tmp12_;
	GSimpleAction* _tmp13_;
	GtkApplication* _tmp14_;
	GtkApplication* _tmp15_;
	self = (JournalApp*) g_object_new (object_type, NULL);
	_tmp0_ = gtk_application_new ("org.gnome.activity-journal", 0);
	_g_object_unref0 (self->priv->application);
	self->priv->application = _tmp0_;
	_tmp1_ = journal_zeitgeist_backend_new ();
	_g_object_unref0 (self->priv->_backend);
	self->priv->_backend = _tmp1_;
	_tmp2_ = g_simple_action_new ("quit", NULL);
	action = _tmp2_;
	_tmp3_ = action;
	g_signal_connect_object (_tmp3_, "activate", (GCallback) ___lambda16__g_simple_action_activate, self, 0);
	_tmp4_ = self->priv->application;
	_tmp5_ = action;
	g_action_map_add_action ((GActionMap*) _tmp4_, (GAction*) _tmp5_);
	_tmp6_ = g_simple_action_new ("display.fullscreen", NULL);
	_g_object_unref0 (self->action_fullscreen);
	self->action_fullscreen = _tmp6_;
	_tmp7_ = self->action_fullscreen;
	g_signal_connect_object (_tmp7_, "activate", (GCallback) ___lambda17__g_simple_action_activate, self, 0);
	_tmp8_ = self->priv->application;
	_tmp9_ = self->action_fullscreen;
	g_action_map_add_action ((GActionMap*) _tmp8_, (GAction*) _tmp9_);
	_tmp10_ = g_simple_action_new ("about", NULL);
	_g_object_unref0 (action);
	action = _tmp10_;
	_tmp11_ = action;
	g_signal_connect_object (_tmp11_, "activate", (GCallback) ___lambda18__g_simple_action_activate, self, 0);
	_tmp12_ = self->priv->application;
	_tmp13_ = action;
	g_action_map_add_action ((GActionMap*) _tmp12_, (GAction*) _tmp13_);
	_tmp14_ = self->priv->application;
	g_signal_connect_object ((GApplication*) _tmp14_, "startup", (GCallback) ___lambda19__g_application_startup, self, G_CONNECT_AFTER);
	_tmp15_ = self->priv->application;
	g_signal_connect_object ((GApplication*) _tmp15_, "activate", (GCallback) ___lambda23__g_application_activate, self, G_CONNECT_AFTER);
	_g_object_unref0 (action);
	return self;
}


JournalApp* journal_app_new (void) {
	return journal_app_construct (JOURNAL_TYPE_APP);
}


gint journal_app_run (JournalApp* self) {
	gint result = 0;
	GtkApplication* _tmp0_;
	gint _tmp1_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->application;
	_tmp1_ = g_application_run ((GApplication*) _tmp0_, 0, NULL);
	result = _tmp1_;
	return result;
}


static GVariant* _variant_new1 (gint* value, gint value_length1) {
	gint* _tmp10_;
	GVariantBuilder _tmp11_;
	int _tmp12_;
	_tmp10_ = value;
	g_variant_builder_init (&_tmp11_, G_VARIANT_TYPE ("ai"));
	for (_tmp12_ = 0; _tmp12_ < value_length1; _tmp12_++) {
		g_variant_builder_add_value (&_tmp11_, g_variant_new_int32 (*_tmp10_));
		_tmp10_++;
	}
	return g_variant_ref_sink (g_variant_builder_end (&_tmp11_));
}


static GVariant* _variant_new2 (gint* value, gint value_length1) {
	gint* _tmp22_;
	GVariantBuilder _tmp23_;
	int _tmp24_;
	_tmp22_ = value;
	g_variant_builder_init (&_tmp23_, G_VARIANT_TYPE ("ai"));
	for (_tmp24_ = 0; _tmp24_ < value_length1; _tmp24_++) {
		g_variant_builder_add_value (&_tmp23_, g_variant_new_int32 (*_tmp22_));
		_tmp22_++;
	}
	return g_variant_ref_sink (g_variant_builder_end (&_tmp23_));
}


static void journal_app_save_window_geometry (JournalApp* self) {
	gint width = 0;
	gint height = 0;
	gint x = 0;
	gint y = 0;
	gboolean _tmp0_;
	gboolean _tmp1_;
	GtkApplicationWindow* _tmp2_;
	gint _tmp3_ = 0;
	gint _tmp4_ = 0;
	GSettings* _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	gint* _tmp8_ = NULL;
	gint* _tmp9_;
	gint _tmp9__length1;
	GVariant* _tmp13_;
	GtkApplicationWindow* _tmp14_;
	gint _tmp15_ = 0;
	gint _tmp16_ = 0;
	GSettings* _tmp17_;
	gint _tmp18_;
	gint _tmp19_;
	gint* _tmp20_ = NULL;
	gint* _tmp21_;
	gint _tmp21__length1;
	GVariant* _tmp25_;
	g_return_if_fail (self != NULL);
	_tmp0_ = journal_app_get_maximized (self);
	_tmp1_ = _tmp0_;
	if (_tmp1_) {
		return;
	}
	_tmp2_ = self->window;
	gtk_window_get_size ((GtkWindow*) _tmp2_, &_tmp3_, &_tmp4_);
	width = _tmp3_;
	height = _tmp4_;
	_tmp5_ = journal_utils_settings;
	_tmp6_ = width;
	_tmp7_ = height;
	_tmp8_ = g_new0 (gint, 2);
	_tmp8_[0] = _tmp6_;
	_tmp8_[1] = _tmp7_;
	_tmp9_ = _tmp8_;
	_tmp9__length1 = 2;
	_tmp13_ = _variant_new1 (_tmp9_, 2);
	g_settings_set_value (_tmp5_, "window-size", _tmp13_);
	_tmp9_ = (g_free (_tmp9_), NULL);
	_tmp14_ = self->window;
	gtk_window_get_position ((GtkWindow*) _tmp14_, &_tmp15_, &_tmp16_);
	x = _tmp15_;
	y = _tmp16_;
	_tmp17_ = journal_utils_settings;
	_tmp18_ = x;
	_tmp19_ = y;
	_tmp20_ = g_new0 (gint, 2);
	_tmp20_[0] = _tmp18_;
	_tmp20_[1] = _tmp19_;
	_tmp21_ = _tmp20_;
	_tmp21__length1 = 2;
	_tmp25_ = _variant_new2 (_tmp21_, 2);
	g_settings_set_value (_tmp17_, "window-position", _tmp25_);
	_tmp21_ = (g_free (_tmp21_), NULL);
}


static gint _variant_get3 (GVariant* value) {
	return g_variant_get_int32 (value);
}


static gint _variant_get4 (GVariant* value) {
	return g_variant_get_int32 (value);
}


static gint _variant_get5 (GVariant* value) {
	return g_variant_get_int32 (value);
}


static gint _variant_get6 (GVariant* value) {
	return g_variant_get_int32 (value);
}


static gboolean __lambda20_ (JournalApp* self) {
	gboolean result = FALSE;
	gboolean _tmp0_;
	gboolean _tmp1_;
	GSettings* _tmp2_;
	gboolean _tmp3_;
	gboolean _tmp4_;
	_tmp0_ = journal_app_get_fullscreen (self);
	_tmp1_ = _tmp0_;
	if (_tmp1_) {
		result = FALSE;
		return result;
	}
	_tmp2_ = journal_utils_settings;
	_tmp3_ = journal_app_get_maximized (self);
	_tmp4_ = _tmp3_;
	g_settings_set_boolean (_tmp2_, "window-maximized", _tmp4_);
	result = FALSE;
	return result;
}


static gboolean ___lambda20__gtk_widget_window_state_event (GtkWidget* _sender, GdkEventWindowState* event, gpointer self) {
	gboolean result;
	result = __lambda20_ (self);
	return result;
}


static void __lambda21_ (JournalApp* self, gboolean mode) {
	JournalDayView* _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp2_;
	_tmp0_ = self->priv->day_view;
	_tmp1_ = mode;
	journal_day_view_set_selection_mode (_tmp0_, _tmp1_);
	_tmp2_ = mode;
	if (_tmp2_) {
		GdMainToolbar* _tmp3_;
		GdMainToolbar* _tmp4_;
		const gchar* _tmp5_ = NULL;
		_tmp3_ = self->priv->main_toolbar;
		gd_main_toolbar_set_mode (_tmp3_, GD_MAIN_TOOLBAR_MODE_SELECTION);
		_tmp4_ = self->priv->main_toolbar;
		_tmp5_ = _ ("(Click on items to select them)");
		gd_main_toolbar_set_labels (_tmp4_, NULL, _tmp5_);
	} else {
		GdMainToolbar* _tmp6_;
		gint num_days;
		gint _tmp7_;
		gchar* _tmp8_ = NULL;
		gchar* _tmp9_;
		gchar* _tmp10_ = NULL;
		gchar* _tmp11_;
		const gchar* _tmp12_ = NULL;
		gchar* _tmp13_;
		gchar* _tmp14_;
		gchar* label;
		GdMainToolbar* _tmp15_;
		const gchar* _tmp16_ = NULL;
		const gchar* _tmp17_;
		_tmp6_ = self->priv->main_toolbar;
		gd_main_toolbar_set_mode (_tmp6_, GD_MAIN_TOOLBAR_MODE_OVERVIEW);
		num_days = 3;
		_tmp7_ = num_days;
		_tmp8_ = g_strdup_printf ("%i", _tmp7_);
		_tmp9_ = _tmp8_;
		_tmp10_ = g_strconcat ("Last ", _tmp9_, " days", NULL);
		_tmp11_ = _tmp10_;
		_tmp12_ = _ (_tmp11_);
		_tmp13_ = g_strdup (_tmp12_);
		_tmp14_ = _tmp13_;
		_g_free0 (_tmp11_);
		_g_free0 (_tmp9_);
		label = _tmp14_;
		_tmp15_ = self->priv->main_toolbar;
		_tmp16_ = _ ("Timeline");
		_tmp17_ = label;
		gd_main_toolbar_set_labels (_tmp15_, _tmp16_, _tmp17_);
		_g_free0 (label);
	}
}


static void ___lambda21__gd_main_toolbar_selection_mode_request (GdMainToolbar* _sender, gboolean object, gpointer self) {
	__lambda21_ (self, object);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static gboolean __lambda22_ (JournalApp* self) {
	gboolean result = FALSE;
	gboolean _tmp0_ = FALSE;
	_tmp0_ = journal_app_quit (self);
	result = _tmp0_;
	return result;
}


static gboolean ___lambda22__gtk_widget_delete_event (GtkWidget* _sender, GdkEventAny* event, gpointer self) {
	gboolean result;
	result = __lambda22_ (self);
	return result;
}


static gboolean _journal_app_on_key_pressed_gtk_widget_key_press_event (GtkWidget* _sender, GdkEventKey* event, gpointer self) {
	gboolean result;
	result = journal_app_on_key_pressed (self, _sender, event);
	return result;
}


static void journal_app_setup_ui (JournalApp* self) {
	GtkApplication* _tmp0_;
	GtkApplicationWindow* _tmp1_;
	GtkApplicationWindow* _tmp2_;
	GtkApplicationWindow* _tmp3_;
	GtkApplicationWindow* _tmp4_;
	GSettings* _tmp5_;
	GVariant* _tmp6_ = NULL;
	GVariant* size;
	GVariant* _tmp7_;
	gsize _tmp8_ = 0UL;
	GSettings* _tmp22_;
	gboolean _tmp23_ = FALSE;
	GSettings* _tmp25_;
	GVariant* _tmp26_ = NULL;
	GVariant* position;
	GVariant* _tmp27_;
	gsize _tmp28_ = 0UL;
	GtkApplicationWindow* _tmp42_;
	GtkBox* _tmp43_;
	GtkBox* _tmp44_;
	GtkApplicationWindow* _tmp45_;
	GtkBox* _tmp46_;
	GdMainToolbar* _tmp47_;
	GdMainToolbar* _tmp48_;
	GdMainToolbar* _tmp49_;
	GdMainToolbar* _tmp50_;
	GdMainToolbar* _tmp51_;
	GtkNotebook* _tmp52_;
	GtkNotebook* _tmp53_;
	GtkNotebook* _tmp54_;
	GtkBox* _tmp55_;
	GdMainToolbar* _tmp56_;
	GtkBox* _tmp57_;
	GtkNotebook* _tmp58_;
	gint num_days;
	JournalDayView* _tmp59_;
	JournalDayView* _tmp60_;
	GtkGrid* _tmp61_;
	GtkGrid* _tmp62_;
	GtkGrid* grid;
	JournalDayView* _tmp63_;
	GtkNotebook* _tmp64_;
	gchar* _tmp65_ = NULL;
	gchar* _tmp66_;
	gchar* _tmp67_ = NULL;
	gchar* _tmp68_;
	const gchar* _tmp69_ = NULL;
	gchar* _tmp70_;
	gchar* _tmp71_;
	gchar* label;
	GdMainToolbar* _tmp72_;
	const gchar* _tmp73_ = NULL;
	GtkClutterEmbed* _tmp74_;
	GtkClutterEmbed* _tmp75_;
	GtkNotebook* _tmp76_;
	GtkClutterEmbed* _tmp77_;
	GtkClutterEmbed* _tmp78_;
	ClutterActor* _tmp79_ = NULL;
	ClutterStage* _tmp80_;
	ClutterStage* _tmp81_;
	GdkRGBA _tmp82_ = {0};
	ClutterColor _tmp83_ = {0};
	GtkApplicationWindow* _tmp84_;
	GtkApplicationWindow* _tmp85_;
	JournalClutterRoundBoxView* _tmp86_;
	JournalClutterRoundBoxView* _tmp87_;
	JournalGtkRoundBoxView* _tmp88_;
	JournalGtkRoundBoxView* _tmp89_;
	GtkScrolledWindow* _tmp90_;
	GtkScrolledWindow* _tmp91_;
	GtkScrolledWindow* sw;
	JournalGtkRoundBoxView* _tmp92_;
	GtkNotebook* _tmp93_;
	JournalLoadingActor* _tmp94_;
	JournalLoadingActor* _tmp95_;
	GtkBox* _tmp96_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->application;
	_tmp1_ = (GtkApplicationWindow*) gtk_application_window_new (_tmp0_);
	_tmp2_ = g_object_ref_sink (_tmp1_);
	_g_object_unref0 (self->window);
	self->window = _tmp2_;
	_tmp3_ = self->window;
	gtk_application_window_set_show_menubar (_tmp3_, FALSE);
	_tmp4_ = self->window;
	gtk_window_set_hide_titlebar_when_maximized ((GtkWindow*) _tmp4_, TRUE);
	_tmp5_ = journal_utils_settings;
	_tmp6_ = g_settings_get_value (_tmp5_, "window-size");
	size = _tmp6_;
	_tmp7_ = size;
	_tmp8_ = g_variant_n_children (_tmp7_);
	if (_tmp8_ == ((gsize) 2)) {
		GVariant* _tmp9_;
		GVariant* _tmp10_ = NULL;
		GVariant* _tmp11_;
		gint _tmp12_;
		gint _tmp13_;
		gint width;
		GVariant* _tmp14_;
		GVariant* _tmp15_ = NULL;
		GVariant* _tmp16_;
		gint _tmp17_;
		gint _tmp18_;
		gint height;
		GtkApplicationWindow* _tmp19_;
		gint _tmp20_;
		gint _tmp21_;
		_tmp9_ = size;
		_tmp10_ = g_variant_get_child_value (_tmp9_, (gsize) 0);
		_tmp11_ = _tmp10_;
		_tmp12_ = _variant_get3 (_tmp11_);
		_tmp13_ = _tmp12_;
		_g_variant_unref0 (_tmp11_);
		width = _tmp13_;
		_tmp14_ = size;
		_tmp15_ = g_variant_get_child_value (_tmp14_, (gsize) 1);
		_tmp16_ = _tmp15_;
		_tmp17_ = _variant_get4 (_tmp16_);
		_tmp18_ = _tmp17_;
		_g_variant_unref0 (_tmp16_);
		height = _tmp18_;
		_tmp19_ = self->window;
		_tmp20_ = width;
		_tmp21_ = height;
		gtk_window_set_default_size ((GtkWindow*) _tmp19_, _tmp20_, _tmp21_);
	}
	_tmp22_ = journal_utils_settings;
	_tmp23_ = g_settings_get_boolean (_tmp22_, "window-maximized");
	if (_tmp23_) {
		GtkApplicationWindow* _tmp24_;
		_tmp24_ = self->window;
		gtk_window_maximize ((GtkWindow*) _tmp24_);
	}
	_tmp25_ = journal_utils_settings;
	_tmp26_ = g_settings_get_value (_tmp25_, "window-position");
	position = _tmp26_;
	_tmp27_ = position;
	_tmp28_ = g_variant_n_children (_tmp27_);
	if (_tmp28_ == ((gsize) 2)) {
		GVariant* _tmp29_;
		GVariant* _tmp30_ = NULL;
		GVariant* _tmp31_;
		gint _tmp32_;
		gint _tmp33_;
		gint x;
		GVariant* _tmp34_;
		GVariant* _tmp35_ = NULL;
		GVariant* _tmp36_;
		gint _tmp37_;
		gint _tmp38_;
		gint y;
		GtkApplicationWindow* _tmp39_;
		gint _tmp40_;
		gint _tmp41_;
		_tmp29_ = position;
		_tmp30_ = g_variant_get_child_value (_tmp29_, (gsize) 0);
		_tmp31_ = _tmp30_;
		_tmp32_ = _variant_get5 (_tmp31_);
		_tmp33_ = _tmp32_;
		_g_variant_unref0 (_tmp31_);
		x = _tmp33_;
		_tmp34_ = position;
		_tmp35_ = g_variant_get_child_value (_tmp34_, (gsize) 1);
		_tmp36_ = _tmp35_;
		_tmp37_ = _variant_get6 (_tmp36_);
		_tmp38_ = _tmp37_;
		_g_variant_unref0 (_tmp36_);
		y = _tmp38_;
		_tmp39_ = self->window;
		_tmp40_ = x;
		_tmp41_ = y;
		gtk_window_move ((GtkWindow*) _tmp39_, _tmp40_, _tmp41_);
	}
	_tmp42_ = self->window;
	g_signal_connect_object ((GtkWidget*) _tmp42_, "window-state-event", (GCallback) ___lambda20__gtk_widget_window_state_event, self, 0);
	_tmp43_ = (GtkBox*) gtk_box_new (GTK_ORIENTATION_VERTICAL, 0);
	_tmp44_ = g_object_ref_sink (_tmp43_);
	_g_object_unref0 (self->main_box);
	self->main_box = _tmp44_;
	_tmp45_ = self->window;
	_tmp46_ = self->main_box;
	gtk_container_add ((GtkContainer*) _tmp45_, (GtkWidget*) _tmp46_);
	_tmp47_ = (GdMainToolbar*) gd_main_toolbar_new ();
	_tmp48_ = g_object_ref_sink (_tmp47_);
	_g_object_unref0 (self->priv->main_toolbar);
	self->priv->main_toolbar = _tmp48_;
	_tmp49_ = self->priv->main_toolbar;
	gtk_toolbar_set_icon_size ((GtkToolbar*) _tmp49_, (gint) GTK_ICON_SIZE_MENU);
	_tmp50_ = self->priv->main_toolbar;
	gd_main_toolbar_set_mode (_tmp50_, GD_MAIN_TOOLBAR_MODE_OVERVIEW);
	_tmp51_ = self->priv->main_toolbar;
	g_signal_connect_object (_tmp51_, "selection-mode-request", (GCallback) ___lambda21__gd_main_toolbar_selection_mode_request, self, 0);
	_tmp52_ = (GtkNotebook*) gtk_notebook_new ();
	_tmp53_ = g_object_ref_sink (_tmp52_);
	_g_object_unref0 (self->notebook);
	self->notebook = _tmp53_;
	_tmp54_ = self->notebook;
	gtk_notebook_set_show_border (_tmp54_, FALSE);
	_tmp55_ = self->main_box;
	_tmp56_ = self->priv->main_toolbar;
	gtk_box_pack_start (_tmp55_, (GtkWidget*) _tmp56_, FALSE, FALSE, (guint) 0);
	_tmp57_ = self->main_box;
	_tmp58_ = self->notebook;
	gtk_box_pack_start (_tmp57_, (GtkWidget*) _tmp58_, TRUE, TRUE, (guint) 0);
	num_days = 3;
	_tmp59_ = journal_day_view_new (self, num_days);
	_tmp60_ = g_object_ref_sink (_tmp59_);
	_g_object_unref0 (self->priv->day_view);
	self->priv->day_view = _tmp60_;
	_tmp61_ = (GtkGrid*) gtk_grid_new ();
	_tmp62_ = g_object_ref_sink (_tmp61_);
	grid = _tmp62_;
	gtk_orientable_set_orientation ((GtkOrientable*) grid, GTK_ORIENTATION_HORIZONTAL);
	_tmp63_ = self->priv->day_view;
	gtk_container_add ((GtkContainer*) grid, (GtkWidget*) _tmp63_);
	_tmp64_ = self->notebook;
	gtk_notebook_append_page (_tmp64_, (GtkWidget*) grid, NULL);
	_tmp65_ = g_strdup_printf ("%i", num_days);
	_tmp66_ = _tmp65_;
	_tmp67_ = g_strconcat ("Last ", _tmp66_, " days", NULL);
	_tmp68_ = _tmp67_;
	_tmp69_ = _ (_tmp68_);
	_tmp70_ = g_strdup (_tmp69_);
	_tmp71_ = _tmp70_;
	_g_free0 (_tmp68_);
	_g_free0 (_tmp66_);
	label = _tmp71_;
	_tmp72_ = self->priv->main_toolbar;
	_tmp73_ = _ ("Timeline");
	gd_main_toolbar_set_labels (_tmp72_, _tmp73_, label);
	_tmp74_ = (GtkClutterEmbed*) gtk_clutter_embed_new ();
	_tmp75_ = g_object_ref_sink (_tmp74_);
	_g_object_unref0 (self->embed);
	self->embed = _tmp75_;
	_tmp76_ = self->notebook;
	_tmp77_ = self->embed;
	gtk_notebook_append_page (_tmp76_, (GtkWidget*) _tmp77_, NULL);
	_tmp78_ = self->embed;
	_tmp79_ = gtk_clutter_embed_get_stage (_tmp78_);
	_tmp80_ = _g_object_ref0 (CLUTTER_IS_STAGE (_tmp79_) ? ((ClutterStage*) _tmp79_) : NULL);
	_g_object_unref0 (self->stage);
	self->stage = _tmp80_;
	_tmp81_ = self->stage;
	journal_utils_get_journal_bg_color (&_tmp82_);
	journal_utils_gdk_rgba_to_clutter_color (&_tmp82_, &_tmp83_);
	clutter_stage_set_color (_tmp81_, &_tmp83_);
	_tmp84_ = self->window;
	g_signal_connect_object ((GtkWidget*) _tmp84_, "delete-event", (GCallback) ___lambda22__gtk_widget_delete_event, self, 0);
	_tmp85_ = self->window;
	g_signal_connect_object ((GtkWidget*) _tmp85_, "key-press-event", (GCallback) _journal_app_on_key_pressed_gtk_widget_key_press_event, self, 0);
	_tmp86_ = journal_clutter_round_box_view_new (self);
	_tmp87_ = g_object_ref_sink (_tmp86_);
	_g_object_unref0 (self->priv->crv);
	self->priv->crv = _tmp87_;
	_tmp88_ = journal_gtk_round_box_view_new (self);
	_tmp89_ = g_object_ref_sink (_tmp88_);
	_g_object_unref0 (self->priv->grv);
	self->priv->grv = _tmp89_;
	_tmp90_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	_tmp91_ = g_object_ref_sink (_tmp90_);
	sw = _tmp91_;
	gtk_scrolled_window_set_policy (sw, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	_tmp92_ = self->priv->grv;
	gtk_scrolled_window_add_with_viewport (sw, (GtkWidget*) _tmp92_);
	_tmp93_ = self->notebook;
	gtk_notebook_append_page (_tmp93_, (GtkWidget*) sw, NULL);
	_tmp94_ = journal_loading_actor_new (self);
	_g_object_unref0 (self->priv->loading_actor);
	self->priv->loading_actor = _tmp94_;
	_tmp95_ = self->priv->loading_actor;
	journal_loading_actor_start (_tmp95_);
	_tmp96_ = self->main_box;
	gtk_widget_show_all ((GtkWidget*) _tmp96_);
	_g_object_unref0 (sw);
	_g_free0 (label);
	_g_object_unref0 (grid);
	_g_variant_unref0 (position);
	_g_variant_unref0 (size);
}


gboolean journal_app_quit (JournalApp* self) {
	gboolean result = FALSE;
	GtkApplicationWindow* _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	journal_app_save_window_geometry (self);
	_tmp0_ = self->window;
	gtk_widget_destroy ((GtkWidget*) _tmp0_);
	result = FALSE;
	return result;
}


static gboolean journal_app_on_key_pressed (JournalApp* self, GtkWidget* widget, GdkEventKey* event) {
	gboolean result = FALSE;
	GdkEventKey _tmp0_;
	guint _tmp1_;
	g_return_val_if_fail (self != NULL, FALSE);
	g_return_val_if_fail (widget != NULL, FALSE);
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = *event;
	_tmp1_ = _tmp0_.keyval;
	if (_tmp1_ == JOURNAL_UTILS_F11_KEY) {
		gboolean _tmp2_;
		gboolean _tmp3_;
		_tmp2_ = journal_app_get_fullscreen (self);
		_tmp3_ = _tmp2_;
		journal_app_set_fullscreen (self, !_tmp3_);
		result = TRUE;
		return result;
	}
	result = FALSE;
	return result;
}


ClutterActor* journal_app_get_actor (JournalApp* self) {
	ClutterActor* result;
	ClutterStage* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->stage;
	result = (ClutterActor*) _tmp0_;
	return result;
}


gboolean journal_app_get_fullscreen (JournalApp* self) {
	gboolean result;
	GtkApplicationWindow* _tmp0_;
	GdkWindow* _tmp1_ = NULL;
	GdkWindowState _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->window;
	_tmp1_ = gtk_widget_get_window ((GtkWidget*) _tmp0_);
	_tmp2_ = gdk_window_get_state (_tmp1_);
	result = (_tmp2_ & GDK_WINDOW_STATE_FULLSCREEN) == GDK_WINDOW_STATE_FULLSCREEN;
	return result;
}


void journal_app_set_fullscreen (JournalApp* self, gboolean value) {
	gboolean _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	if (_tmp0_) {
		GtkApplicationWindow* _tmp1_;
		_tmp1_ = self->window;
		gtk_window_fullscreen ((GtkWindow*) _tmp1_);
	} else {
		GtkApplicationWindow* _tmp2_;
		_tmp2_ = self->window;
		gtk_window_unfullscreen ((GtkWindow*) _tmp2_);
	}
	g_object_notify ((GObject *) self, "fullscreen");
}


static gboolean journal_app_get_maximized (JournalApp* self) {
	gboolean result;
	GtkApplicationWindow* _tmp0_;
	GdkWindow* _tmp1_ = NULL;
	GdkWindowState _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->window;
	_tmp1_ = gtk_widget_get_window ((GtkWidget*) _tmp0_);
	_tmp2_ = gdk_window_get_state (_tmp1_);
	result = (_tmp2_ & GDK_WINDOW_STATE_MAXIMIZED) == GDK_WINDOW_STATE_MAXIMIZED;
	return result;
}


JournalZeitgeistBackend* journal_app_get_backend (JournalApp* self) {
	JournalZeitgeistBackend* result;
	JournalZeitgeistBackend* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_backend;
	result = _tmp0_;
	return result;
}


static void journal_app_class_init (JournalAppClass * klass) {
	journal_app_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (JournalAppPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_journal_app_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_journal_app_set_property;
	G_OBJECT_CLASS (klass)->finalize = journal_app_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_APP_ACTOR, g_param_spec_object ("actor", "actor", "actor", clutter_actor_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_APP_FULLSCREEN, g_param_spec_boolean ("fullscreen", "fullscreen", "fullscreen", FALSE, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE | G_PARAM_WRITABLE));
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_APP_BACKEND, g_param_spec_object ("backend", "backend", "backend", JOURNAL_TYPE_ZEITGEIST_BACKEND, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void journal_app_instance_init (JournalApp * self) {
	self->priv = JOURNAL_APP_GET_PRIVATE (self);
}


static void journal_app_finalize (GObject* obj) {
	JournalApp * self;
	self = JOURNAL_APP (obj);
	_g_object_unref0 (self->window);
	_g_object_unref0 (self->notebook);
	_g_object_unref0 (self->main_box);
	_g_object_unref0 (self->embed);
	_g_object_unref0 (self->stage);
	_g_object_unref0 (self->box);
	_g_object_unref0 (self->action_fullscreen);
	_g_object_unref0 (self->priv->application);
	_g_object_unref0 (self->priv->box_table);
	_g_object_unref0 (self->priv->loading_actor);
	_g_object_unref0 (self->priv->day_view);
	_g_object_unref0 (self->priv->crv);
	_g_object_unref0 (self->priv->grv);
	_g_object_unref0 (self->priv->reminder_view);
	_g_object_unref0 (self->priv->revealer);
	_g_object_unref0 (self->priv->main_toolbar);
	_g_object_unref0 (self->priv->_backend);
	G_OBJECT_CLASS (journal_app_parent_class)->finalize (obj);
}


GType journal_app_get_type (void) {
	static volatile gsize journal_app_type_id__volatile = 0;
	if (g_once_init_enter (&journal_app_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JournalAppClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) journal_app_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JournalApp), 0, (GInstanceInitFunc) journal_app_instance_init, NULL };
		GType journal_app_type_id;
		journal_app_type_id = g_type_register_static (G_TYPE_OBJECT, "JournalApp", &g_define_type_info, 0);
		g_once_init_leave (&journal_app_type_id__volatile, journal_app_type_id);
	}
	return journal_app_type_id__volatile;
}


static void _vala_journal_app_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	JournalApp * self;
	self = JOURNAL_APP (object);
	switch (property_id) {
		case JOURNAL_APP_ACTOR:
		g_value_set_object (value, journal_app_get_actor (self));
		break;
		case JOURNAL_APP_FULLSCREEN:
		g_value_set_boolean (value, journal_app_get_fullscreen (self));
		break;
		case JOURNAL_APP_BACKEND:
		g_value_set_object (value, journal_app_get_backend (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_journal_app_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	JournalApp * self;
	self = JOURNAL_APP (object);
	switch (property_id) {
		case JOURNAL_APP_FULLSCREEN:
		journal_app_set_fullscreen (self, g_value_get_boolean (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



