/* dayview.c generated by valac 0.16.0, the Vala compiler
 * generated from dayview.vala, do not modify */

/* This file is part of GNOME Activity Journal.*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gd-main-view.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>
#include <zeitgeist.h>
#include <glib/gi18n-lib.h>


#define JOURNAL_TYPE_SINGLE_DAY_VIEW (journal_single_day_view_get_type ())
#define JOURNAL_SINGLE_DAY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_SINGLE_DAY_VIEW, JournalSingleDayView))
#define JOURNAL_SINGLE_DAY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_SINGLE_DAY_VIEW, JournalSingleDayViewClass))
#define JOURNAL_IS_SINGLE_DAY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_SINGLE_DAY_VIEW))
#define JOURNAL_IS_SINGLE_DAY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_SINGLE_DAY_VIEW))
#define JOURNAL_SINGLE_DAY_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_SINGLE_DAY_VIEW, JournalSingleDayViewClass))

typedef struct _JournalSingleDayView JournalSingleDayView;
typedef struct _JournalSingleDayViewClass JournalSingleDayViewClass;
typedef struct _JournalSingleDayViewPrivate JournalSingleDayViewPrivate;

#define JOURNAL_TYPE_APP (journal_app_get_type ())
#define JOURNAL_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_APP, JournalApp))
#define JOURNAL_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_APP, JournalAppClass))
#define JOURNAL_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_APP))
#define JOURNAL_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_APP))
#define JOURNAL_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_APP, JournalAppClass))

typedef struct _JournalApp JournalApp;
typedef struct _JournalAppClass JournalAppClass;

#define JOURNAL_TYPE_ACTIVITY_MODEL (journal_activity_model_get_type ())
#define JOURNAL_ACTIVITY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_ACTIVITY_MODEL, JournalActivityModel))
#define JOURNAL_ACTIVITY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_ACTIVITY_MODEL, JournalActivityModelClass))
#define JOURNAL_IS_ACTIVITY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_ACTIVITY_MODEL))
#define JOURNAL_IS_ACTIVITY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_ACTIVITY_MODEL))
#define JOURNAL_ACTIVITY_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_ACTIVITY_MODEL, JournalActivityModelClass))

typedef struct _JournalActivityModel JournalActivityModel;
typedef struct _JournalActivityModelClass JournalActivityModelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))

#define JOURNAL_TYPE_GENERIC_ACTIVITY (journal_generic_activity_get_type ())
#define JOURNAL_GENERIC_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_GENERIC_ACTIVITY, JournalGenericActivity))
#define JOURNAL_GENERIC_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_GENERIC_ACTIVITY, JournalGenericActivityClass))
#define JOURNAL_IS_GENERIC_ACTIVITY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_GENERIC_ACTIVITY))
#define JOURNAL_IS_GENERIC_ACTIVITY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_GENERIC_ACTIVITY))
#define JOURNAL_GENERIC_ACTIVITY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_GENERIC_ACTIVITY, JournalGenericActivityClass))

typedef struct _JournalGenericActivity JournalGenericActivity;
typedef struct _JournalGenericActivityClass JournalGenericActivityClass;

#define JOURNAL_TYPE_DAY_VIEW (journal_day_view_get_type ())
#define JOURNAL_DAY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_DAY_VIEW, JournalDayView))
#define JOURNAL_DAY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_DAY_VIEW, JournalDayViewClass))
#define JOURNAL_IS_DAY_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_DAY_VIEW))
#define JOURNAL_IS_DAY_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_DAY_VIEW))
#define JOURNAL_DAY_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_DAY_VIEW, JournalDayViewClass))

typedef struct _JournalDayView JournalDayView;
typedef struct _JournalDayViewClass JournalDayViewClass;
typedef struct _JournalDayViewPrivate JournalDayViewPrivate;

#define JOURNAL_TYPE_ZEITGEIST_BACKEND (journal_zeitgeist_backend_get_type ())
#define JOURNAL_ZEITGEIST_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackend))
#define JOURNAL_ZEITGEIST_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackendClass))
#define JOURNAL_IS_ZEITGEIST_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND))
#define JOURNAL_IS_ZEITGEIST_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_ZEITGEIST_BACKEND))
#define JOURNAL_ZEITGEIST_BACKEND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackendClass))

typedef struct _JournalZeitgeistBackend JournalZeitgeistBackend;
typedef struct _JournalZeitgeistBackendClass JournalZeitgeistBackendClass;

struct _JournalSingleDayView {
	GtkBox parent_instance;
	JournalSingleDayViewPrivate * priv;
};

struct _JournalSingleDayViewClass {
	GtkBoxClass parent_class;
};

struct _JournalSingleDayViewPrivate {
	JournalApp* app;
	GdMainView* view;
	JournalActivityModel* model;
	GtkScrolledWindow* scrolled_window;
	GDateTime* _day;
};

struct _JournalDayView {
	GtkBox parent_instance;
	JournalDayViewPrivate * priv;
};

struct _JournalDayViewClass {
	GtkBoxClass parent_class;
};

struct _JournalDayViewPrivate {
	JournalApp* app;
	JournalSingleDayView** day_views;
	gint day_views_length1;
	gint _day_views_size_;
	gint num_days;
};


static gpointer journal_single_day_view_parent_class = NULL;
static gpointer journal_day_view_parent_class = NULL;

GType journal_single_day_view_get_type (void) G_GNUC_CONST;
GType journal_app_get_type (void) G_GNUC_CONST;
GType journal_activity_model_get_type (void) G_GNUC_CONST;
#define JOURNAL_SINGLE_DAY_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JOURNAL_TYPE_SINGLE_DAY_VIEW, JournalSingleDayViewPrivate))
enum  {
	JOURNAL_SINGLE_DAY_VIEW_DUMMY_PROPERTY,
	JOURNAL_SINGLE_DAY_VIEW_DAY
};
JournalSingleDayView* journal_single_day_view_new (JournalApp* app, GDateTime* day);
JournalSingleDayView* journal_single_day_view_construct (GType object_type, JournalApp* app, GDateTime* day);
static void journal_single_day_view_set_day (JournalSingleDayView* self, GDateTime* value);
JournalActivityModel* journal_activity_model_new (void);
JournalActivityModel* journal_activity_model_construct (GType object_type);
static gchar* journal_single_day_view_get_day_title (JournalSingleDayView* self);
void journal_single_day_view_load_events (JournalSingleDayView* self, GeeArrayList* events);
JournalGenericActivity* journal_generic_activity_new (ZeitgeistEvent* event);
JournalGenericActivity* journal_generic_activity_construct (GType object_type, ZeitgeistEvent* event);
GType journal_generic_activity_get_type (void) G_GNUC_CONST;
void journal_activity_model_add_activity (JournalActivityModel* self, JournalGenericActivity* activity);
GtkListStore* journal_activity_model_get_model (JournalActivityModel* self);
gchar* journal_single_day_view_get_day_string (JournalSingleDayView* self);
GDateTime* journal_single_day_view_get_day (JournalSingleDayView* self);
void journal_single_day_view_set_selection_mode (JournalSingleDayView* self, gboolean mode);
static void journal_single_day_view_finalize (GObject* obj);
static void _vala_journal_single_day_view_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_journal_single_day_view_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);
GType journal_day_view_get_type (void) G_GNUC_CONST;
#define JOURNAL_DAY_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JOURNAL_TYPE_DAY_VIEW, JournalDayViewPrivate))
enum  {
	JOURNAL_DAY_VIEW_DUMMY_PROPERTY
};
JournalDayView* journal_day_view_new (JournalApp* app, gint num_days);
JournalDayView* journal_day_view_construct (GType object_type, JournalApp* app, gint num_days);
static void journal_day_view_setup_ui (JournalDayView* self);
GType journal_zeitgeist_backend_get_type (void) G_GNUC_CONST;
JournalZeitgeistBackend* journal_app_get_backend (JournalApp* self);
static void __lambda7_ (JournalDayView* self);
void journal_day_view_load_events (JournalDayView* self);
static void ___lambda7__journal_zeitgeist_backend_events_loaded (JournalZeitgeistBackend* _sender, gpointer self);
GeeArrayList* journal_zeitgeist_backend_get_events_for_day (JournalZeitgeistBackend* self, const gchar* ymd);
void journal_day_view_set_selection_mode (JournalDayView* self, gboolean mode);
static void journal_day_view_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


JournalSingleDayView* journal_single_day_view_construct (GType object_type, JournalApp* app, GDateTime* day) {
	JournalSingleDayView * self = NULL;
	JournalApp* _tmp0_;
	JournalApp* _tmp1_;
	GDateTime* _tmp2_;
	GdMainView* _tmp3_;
	GdMainView* _tmp4_;
	JournalActivityModel* _tmp5_;
	GtkScrolledWindow* _tmp6_;
	GtkScrolledWindow* _tmp7_;
	GtkScrolledWindow* _tmp8_;
	GtkScrolledWindow* _tmp9_;
	GdMainView* _tmp10_;
	gchar* _tmp11_ = NULL;
	gchar* _tmp12_;
	GtkButton* _tmp13_;
	GtkButton* _tmp14_;
	GtkButton* _tmp15_;
	GtkButton* box;
	GtkStyleContext* _tmp16_ = NULL;
	GtkWidget* _tmp17_ = NULL;
	GtkScrolledWindow* _tmp18_;
	g_return_val_if_fail (app != NULL, NULL);
	g_return_val_if_fail (day != NULL, NULL);
	self = (JournalSingleDayView*) g_object_new (object_type, "orientation", GTK_ORIENTATION_VERTICAL, "spacing", 0, NULL);
	_tmp0_ = app;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->app);
	self->priv->app = _tmp1_;
	_tmp2_ = day;
	journal_single_day_view_set_day (self, _tmp2_);
	_tmp3_ = gd_main_view_new (GD_MAIN_VIEW_LIST);
	_tmp4_ = g_object_ref_sink (_tmp3_);
	_g_object_unref0 (self->priv->view);
	self->priv->view = _tmp4_;
	_tmp5_ = journal_activity_model_new ();
	_g_object_unref0 (self->priv->model);
	self->priv->model = _tmp5_;
	_tmp6_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	_tmp7_ = g_object_ref_sink (_tmp6_);
	_g_object_unref0 (self->priv->scrolled_window);
	self->priv->scrolled_window = _tmp7_;
	_tmp8_ = self->priv->scrolled_window;
	gtk_scrolled_window_set_policy (_tmp8_, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	_tmp9_ = self->priv->scrolled_window;
	_tmp10_ = self->priv->view;
	gtk_scrolled_window_add_with_viewport (_tmp9_, (GtkWidget*) _tmp10_);
	_tmp11_ = journal_single_day_view_get_day_title (self);
	_tmp12_ = _tmp11_;
	_tmp13_ = (GtkButton*) gtk_button_new_with_label (_tmp12_);
	_tmp14_ = g_object_ref_sink (_tmp13_);
	_tmp15_ = _tmp14_;
	_g_free0 (_tmp12_);
	box = _tmp15_;
	gtk_widget_set_sensitive ((GtkWidget*) box, FALSE);
	_tmp16_ = gtk_widget_get_style_context ((GtkWidget*) box);
	gtk_style_context_add_class (_tmp16_, "dayview");
	_tmp17_ = gtk_bin_get_child ((GtkBin*) box);
	gtk_widget_set_name (_tmp17_, "dayview-label");
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) box, FALSE, FALSE, (guint) 0);
	_tmp18_ = self->priv->scrolled_window;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp18_, TRUE, TRUE, (guint) 0);
	_g_object_unref0 (box);
	return self;
}


JournalSingleDayView* journal_single_day_view_new (JournalApp* app, GDateTime* day) {
	return journal_single_day_view_construct (JOURNAL_TYPE_SINGLE_DAY_VIEW, app, day);
}


void journal_single_day_view_load_events (JournalSingleDayView* self, GeeArrayList* events) {
	GeeArrayList* _tmp0_;
	GdMainView* _tmp16_;
	JournalActivityModel* _tmp17_;
	GtkListStore* _tmp18_ = NULL;
	GtkListStore* _tmp19_;
	g_return_if_fail (self != NULL);
	_tmp0_ = events;
	if (_tmp0_ == NULL) {
		return;
	}
	{
		GeeArrayList* _tmp1_;
		GeeArrayList* _tmp2_;
		GeeArrayList* _e_list;
		GeeArrayList* _tmp3_;
		gint _tmp4_;
		gint _tmp5_;
		gint _e_size;
		gint _e_index;
		_tmp1_ = events;
		_tmp2_ = _g_object_ref0 (_tmp1_);
		_e_list = _tmp2_;
		_tmp3_ = _e_list;
		_tmp4_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp3_);
		_tmp5_ = _tmp4_;
		_e_size = _tmp5_;
		_e_index = -1;
		while (TRUE) {
			gint _tmp6_;
			gint _tmp7_;
			gint _tmp8_;
			GeeArrayList* _tmp9_;
			gint _tmp10_;
			gpointer _tmp11_ = NULL;
			ZeitgeistEvent* e;
			ZeitgeistEvent* _tmp12_;
			JournalGenericActivity* _tmp13_;
			JournalGenericActivity* activity;
			JournalActivityModel* _tmp14_;
			JournalGenericActivity* _tmp15_;
			_tmp6_ = _e_index;
			_e_index = _tmp6_ + 1;
			_tmp7_ = _e_index;
			_tmp8_ = _e_size;
			if (!(_tmp7_ < _tmp8_)) {
				break;
			}
			_tmp9_ = _e_list;
			_tmp10_ = _e_index;
			_tmp11_ = gee_abstract_list_get ((GeeAbstractList*) _tmp9_, _tmp10_);
			e = (ZeitgeistEvent*) _tmp11_;
			_tmp12_ = e;
			_tmp13_ = journal_generic_activity_new (_tmp12_);
			activity = _tmp13_;
			_tmp14_ = self->priv->model;
			_tmp15_ = activity;
			journal_activity_model_add_activity (_tmp14_, _tmp15_);
			_g_object_unref0 (activity);
			_g_object_unref0 (e);
		}
		_g_object_unref0 (_e_list);
	}
	_tmp16_ = self->priv->view;
	_tmp17_ = self->priv->model;
	_tmp18_ = journal_activity_model_get_model (_tmp17_);
	_tmp19_ = _tmp18_;
	gd_main_view_set_model (_tmp16_, (GtkTreeModel*) _tmp19_);
	_g_object_unref0 (_tmp19_);
}


gchar* journal_single_day_view_get_day_string (JournalSingleDayView* self) {
	gchar* result = NULL;
	GDateTime* _tmp0_;
	gchar* _tmp1_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_day;
	_tmp1_ = g_date_time_format (_tmp0_, "%Y-%m-%d");
	result = _tmp1_;
	return result;
}


void journal_single_day_view_set_selection_mode (JournalSingleDayView* self, gboolean mode) {
	GdMainView* _tmp0_;
	gboolean _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->view;
	_tmp1_ = mode;
	gd_main_view_set_selection_mode (_tmp0_, _tmp1_);
}


static gchar* journal_single_day_view_get_day_title (JournalSingleDayView* self) {
	gchar* result = NULL;
	GDateTime* _tmp0_;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_day;
	_tmp1_ = _ ("%A, %x");
	_tmp2_ = g_date_time_format (_tmp0_, _tmp1_);
	result = _tmp2_;
	return result;
}


GDateTime* journal_single_day_view_get_day (JournalSingleDayView* self) {
	GDateTime* result;
	GDateTime* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_day;
	result = _tmp0_;
	return result;
}


static gpointer _g_date_time_ref0 (gpointer self) {
	return self ? g_date_time_ref (self) : NULL;
}


static void journal_single_day_view_set_day (JournalSingleDayView* self, GDateTime* value) {
	GDateTime* _tmp0_;
	GDateTime* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = _g_date_time_ref0 (_tmp0_);
	_g_date_time_unref0 (self->priv->_day);
	self->priv->_day = _tmp1_;
	g_object_notify ((GObject *) self, "day");
}


static void journal_single_day_view_class_init (JournalSingleDayViewClass * klass) {
	journal_single_day_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (JournalSingleDayViewPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_journal_single_day_view_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_journal_single_day_view_set_property;
	G_OBJECT_CLASS (klass)->finalize = journal_single_day_view_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_SINGLE_DAY_VIEW_DAY, g_param_spec_boxed ("day", "day", "day", G_TYPE_DATE_TIME, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void journal_single_day_view_instance_init (JournalSingleDayView * self) {
	self->priv = JOURNAL_SINGLE_DAY_VIEW_GET_PRIVATE (self);
}


static void journal_single_day_view_finalize (GObject* obj) {
	JournalSingleDayView * self;
	self = JOURNAL_SINGLE_DAY_VIEW (obj);
	_g_object_unref0 (self->priv->app);
	_g_object_unref0 (self->priv->view);
	_g_object_unref0 (self->priv->model);
	_g_object_unref0 (self->priv->scrolled_window);
	_g_date_time_unref0 (self->priv->_day);
	G_OBJECT_CLASS (journal_single_day_view_parent_class)->finalize (obj);
}


GType journal_single_day_view_get_type (void) {
	static volatile gsize journal_single_day_view_type_id__volatile = 0;
	if (g_once_init_enter (&journal_single_day_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JournalSingleDayViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) journal_single_day_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JournalSingleDayView), 0, (GInstanceInitFunc) journal_single_day_view_instance_init, NULL };
		GType journal_single_day_view_type_id;
		journal_single_day_view_type_id = g_type_register_static (GTK_TYPE_BOX, "JournalSingleDayView", &g_define_type_info, 0);
		g_once_init_leave (&journal_single_day_view_type_id__volatile, journal_single_day_view_type_id);
	}
	return journal_single_day_view_type_id__volatile;
}


static void _vala_journal_single_day_view_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	JournalSingleDayView * self;
	self = JOURNAL_SINGLE_DAY_VIEW (object);
	switch (property_id) {
		case JOURNAL_SINGLE_DAY_VIEW_DAY:
		g_value_set_boxed (value, journal_single_day_view_get_day (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_journal_single_day_view_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	JournalSingleDayView * self;
	self = JOURNAL_SINGLE_DAY_VIEW (object);
	switch (property_id) {
		case JOURNAL_SINGLE_DAY_VIEW_DAY:
		journal_single_day_view_set_day (self, g_value_get_boxed (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void __lambda7_ (JournalDayView* self) {
	journal_day_view_load_events (self);
}


static void ___lambda7__journal_zeitgeist_backend_events_loaded (JournalZeitgeistBackend* _sender, gpointer self) {
	__lambda7_ (self);
}


JournalDayView* journal_day_view_construct (GType object_type, JournalApp* app, gint num_days) {
	JournalDayView * self = NULL;
	JournalApp* _tmp0_;
	JournalApp* _tmp1_;
	gint _tmp2_;
	JournalSingleDayView** _tmp3_ = NULL;
	gint _tmp4_;
	JournalApp* _tmp5_;
	JournalZeitgeistBackend* _tmp6_;
	JournalZeitgeistBackend* _tmp7_;
	g_return_val_if_fail (app != NULL, NULL);
	self = (JournalDayView*) g_object_new (object_type, "orientation", GTK_ORIENTATION_HORIZONTAL, "spacing", 0, NULL);
	_tmp0_ = app;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->app);
	self->priv->app = _tmp1_;
	_tmp2_ = num_days;
	_tmp3_ = g_new0 (JournalSingleDayView*, _tmp2_ + 1);
	self->priv->day_views = (_vala_array_free (self->priv->day_views, self->priv->day_views_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->day_views = _tmp3_;
	self->priv->day_views_length1 = _tmp2_;
	self->priv->_day_views_size_ = self->priv->day_views_length1;
	_tmp4_ = num_days;
	self->priv->num_days = _tmp4_;
	journal_day_view_setup_ui (self);
	_tmp5_ = app;
	_tmp6_ = journal_app_get_backend (_tmp5_);
	_tmp7_ = _tmp6_;
	g_signal_connect_object (_tmp7_, "events-loaded", (GCallback) ___lambda7__journal_zeitgeist_backend_events_loaded, self, 0);
	return self;
}


JournalDayView* journal_day_view_new (JournalApp* app, gint num_days) {
	return journal_day_view_construct (JOURNAL_TYPE_DAY_VIEW, app, num_days);
}


static void journal_day_view_setup_ui (JournalDayView* self) {
	GDateTime* _tmp0_;
	GDateTime* day;
	JournalSingleDayView** _tmp1_;
	gint _tmp1__length1;
	JournalApp* _tmp2_;
	GDateTime* _tmp3_;
	JournalSingleDayView* _tmp4_;
	JournalSingleDayView* _tmp5_;
	JournalSingleDayView* _tmp6_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_date_time_new_now_local ();
	day = _tmp0_;
	_tmp1_ = self->priv->day_views;
	_tmp1__length1 = self->priv->day_views_length1;
	_tmp2_ = self->priv->app;
	_tmp3_ = day;
	_tmp4_ = journal_single_day_view_new (_tmp2_, _tmp3_);
	_tmp5_ = g_object_ref_sink (_tmp4_);
	_g_object_unref0 (_tmp1_[0]);
	_tmp1_[0] = _tmp5_;
	_tmp6_ = _tmp1_[0];
	{
		gint i;
		i = 1;
		{
			gboolean _tmp7_;
			_tmp7_ = TRUE;
			while (TRUE) {
				gboolean _tmp8_;
				gint _tmp10_;
				gint _tmp11_;
				GDateTime* _tmp12_;
				GDateTime* _tmp13_ = NULL;
				JournalSingleDayView** _tmp14_;
				gint _tmp14__length1;
				gint _tmp15_;
				JournalApp* _tmp16_;
				GDateTime* _tmp17_;
				JournalSingleDayView* _tmp18_;
				JournalSingleDayView* _tmp19_;
				JournalSingleDayView* _tmp20_;
				_tmp8_ = _tmp7_;
				if (!_tmp8_) {
					gint _tmp9_;
					_tmp9_ = i;
					i = _tmp9_ + 1;
				}
				_tmp7_ = FALSE;
				_tmp10_ = i;
				_tmp11_ = self->priv->num_days;
				if (!(_tmp10_ < _tmp11_)) {
					break;
				}
				_tmp12_ = day;
				_tmp13_ = g_date_time_add_days (_tmp12_, -1);
				_g_date_time_unref0 (day);
				day = _tmp13_;
				_tmp14_ = self->priv->day_views;
				_tmp14__length1 = self->priv->day_views_length1;
				_tmp15_ = i;
				_tmp16_ = self->priv->app;
				_tmp17_ = day;
				_tmp18_ = journal_single_day_view_new (_tmp16_, _tmp17_);
				_tmp19_ = g_object_ref_sink (_tmp18_);
				_g_object_unref0 (_tmp14_[_tmp15_]);
				_tmp14_[_tmp15_] = _tmp19_;
				_tmp20_ = _tmp14_[_tmp15_];
			}
		}
	}
	{
		gint i;
		i = 0;
		{
			gboolean _tmp21_;
			_tmp21_ = TRUE;
			while (TRUE) {
				gboolean _tmp22_;
				gint _tmp24_;
				gint _tmp25_;
				JournalSingleDayView** _tmp26_;
				gint _tmp26__length1;
				gint _tmp27_;
				JournalSingleDayView* _tmp28_;
				_tmp22_ = _tmp21_;
				if (!_tmp22_) {
					gint _tmp23_;
					_tmp23_ = i;
					i = _tmp23_ + 1;
				}
				_tmp21_ = FALSE;
				_tmp24_ = i;
				_tmp25_ = self->priv->num_days;
				if (!(_tmp24_ < _tmp25_)) {
					break;
				}
				_tmp26_ = self->priv->day_views;
				_tmp26__length1 = self->priv->day_views_length1;
				_tmp27_ = i;
				_tmp28_ = _tmp26_[_tmp27_];
				gtk_box_pack_end ((GtkBox*) self, (GtkWidget*) _tmp28_, TRUE, TRUE, (guint) 2);
			}
		}
	}
	_g_date_time_unref0 (day);
}


void journal_day_view_load_events (JournalDayView* self) {
	g_return_if_fail (self != NULL);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_;
				gint _tmp3_;
				gint _tmp4_;
				JournalSingleDayView** _tmp5_;
				gint _tmp5__length1;
				gint _tmp6_;
				JournalSingleDayView* _tmp7_;
				gchar* _tmp8_ = NULL;
				gchar* key;
				JournalSingleDayView** _tmp9_;
				gint _tmp9__length1;
				gint _tmp10_;
				JournalSingleDayView* _tmp11_;
				JournalApp* _tmp12_;
				JournalZeitgeistBackend* _tmp13_;
				JournalZeitgeistBackend* _tmp14_;
				const gchar* _tmp15_;
				GeeArrayList* _tmp16_ = NULL;
				GeeArrayList* _tmp17_;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = self->priv->num_days;
				if (!(_tmp3_ < _tmp4_)) {
					break;
				}
				_tmp5_ = self->priv->day_views;
				_tmp5__length1 = self->priv->day_views_length1;
				_tmp6_ = i;
				_tmp7_ = _tmp5_[_tmp6_];
				_tmp8_ = journal_single_day_view_get_day_string (_tmp7_);
				key = _tmp8_;
				_tmp9_ = self->priv->day_views;
				_tmp9__length1 = self->priv->day_views_length1;
				_tmp10_ = i;
				_tmp11_ = _tmp9_[_tmp10_];
				_tmp12_ = self->priv->app;
				_tmp13_ = journal_app_get_backend (_tmp12_);
				_tmp14_ = _tmp13_;
				_tmp15_ = key;
				_tmp16_ = journal_zeitgeist_backend_get_events_for_day (_tmp14_, _tmp15_);
				_tmp17_ = _tmp16_;
				journal_single_day_view_load_events (_tmp11_, _tmp17_);
				_g_object_unref0 (_tmp17_);
				_g_free0 (key);
			}
		}
	}
}


void journal_day_view_set_selection_mode (JournalDayView* self, gboolean mode) {
	g_return_if_fail (self != NULL);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_;
				gint _tmp3_;
				gint _tmp4_;
				JournalSingleDayView** _tmp5_;
				gint _tmp5__length1;
				gint _tmp6_;
				JournalSingleDayView* _tmp7_;
				gboolean _tmp8_;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = self->priv->num_days;
				if (!(_tmp3_ < _tmp4_)) {
					break;
				}
				_tmp5_ = self->priv->day_views;
				_tmp5__length1 = self->priv->day_views_length1;
				_tmp6_ = i;
				_tmp7_ = _tmp5_[_tmp6_];
				_tmp8_ = mode;
				journal_single_day_view_set_selection_mode (_tmp7_, _tmp8_);
			}
		}
	}
}


static void journal_day_view_class_init (JournalDayViewClass * klass) {
	journal_day_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (JournalDayViewPrivate));
	G_OBJECT_CLASS (klass)->finalize = journal_day_view_finalize;
}


static void journal_day_view_instance_init (JournalDayView * self) {
	self->priv = JOURNAL_DAY_VIEW_GET_PRIVATE (self);
}


static void journal_day_view_finalize (GObject* obj) {
	JournalDayView * self;
	self = JOURNAL_DAY_VIEW (obj);
	_g_object_unref0 (self->priv->app);
	self->priv->day_views = (_vala_array_free (self->priv->day_views, self->priv->day_views_length1, (GDestroyNotify) g_object_unref), NULL);
	G_OBJECT_CLASS (journal_day_view_parent_class)->finalize (obj);
}


GType journal_day_view_get_type (void) {
	static volatile gsize journal_day_view_type_id__volatile = 0;
	if (g_once_init_enter (&journal_day_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JournalDayViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) journal_day_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JournalDayView), 0, (GInstanceInitFunc) journal_day_view_instance_init, NULL };
		GType journal_day_view_type_id;
		journal_day_view_type_id = g_type_register_static (GTK_TYPE_BOX, "JournalDayView", &g_define_type_info, 0);
		g_once_init_leave (&journal_day_view_type_id__volatile, journal_day_view_type_id);
	}
	return journal_day_view_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



