/* main.c generated by valac 0.16.0, the Vala compiler
 * generated from main.vala, do not modify */

/* This file is part of GNOME Activity Journal*/
/*private static bool version;*/
/*private const OptionEntry[] options = {*/
/*    { "version", 0, 0, OptionArg.NONE, ref version, N_("Display version number"), null },*/
/*    { null }*/
/*};*/
/*private static void parse_args (ref unowned string[] args) {*/
/*    var parameter_string = _("- A simple journal application");*/
/*    var opt_context = new OptionContext (parameter_string);*/
/*    opt_context.set_help_enabled (true);*/
/*    opt_context.set_ignore_unknown_options (true);*/
/*    opt_context.add_main_entries (options, null);*/
/*    opt_context.add_group (Gtk.get_option_group (true));*/
/*    opt_context.add_group (Clutter.get_option_group_without_init ());*/
/*    opt_context.add_group (GtkClutter.get_option_group ());*/
/*    try {*/
/*        opt_context.parse (ref args);*/
/*    } catch (OptionError.BAD_VALUE err) {*/
/*        GLib.stdout.printf (opt_context.get_help (true, null));*/
/*        exit (1);*/
/*    } catch (OptionError error) {*/
/*        warning (error.message);*/
/*    }*/
/*    if (version) {*/
/*        GLib.stdout.printf ("0.1\n");*/
/*        exit (0);*/
/*    }*/
/*}*/

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <glib/gi18n-lib.h>
#include <config.h>
#include <clutter-gtk/clutter-gtk.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

#define JOURNAL_TYPE_UTILS (journal_utils_get_type ())
#define JOURNAL_UTILS(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_UTILS, JournalUtils))
#define JOURNAL_UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_UTILS, JournalUtilsClass))
#define JOURNAL_IS_UTILS(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_UTILS))
#define JOURNAL_IS_UTILS_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_UTILS))
#define JOURNAL_UTILS_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_UTILS, JournalUtilsClass))

typedef struct _JournalUtils JournalUtils;
typedef struct _JournalUtilsClass JournalUtilsClass;

#define JOURNAL_TYPE_APP (journal_app_get_type ())
#define JOURNAL_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_APP, JournalApp))
#define JOURNAL_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_APP, JournalAppClass))
#define JOURNAL_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_APP))
#define JOURNAL_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_APP))
#define JOURNAL_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_APP, JournalAppClass))

typedef struct _JournalApp JournalApp;
typedef struct _JournalAppClass JournalAppClass;



gint _vala_main (gchar** args, int args_length1);
gchar* journal_utils_get_style (const gchar* file_name);
JournalUtils* journal_utils_new (void);
JournalUtils* journal_utils_construct (GType object_type);
GType journal_utils_get_type (void) G_GNUC_CONST;
JournalApp* journal_app_new (void);
JournalApp* journal_app_construct (GType object_type);
GType journal_app_get_type (void) G_GNUC_CONST;
gint journal_app_run (JournalApp* self);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	const gchar* _tmp0_ = NULL;
	GtkCssProvider* _tmp1_;
	GtkCssProvider* provider;
	JournalUtils* _tmp11_;
	JournalUtils* utils;
	JournalApp* _tmp12_;
	JournalApp* app;
	gint _tmp13_ = 0;
	GError * _inner_error_ = NULL;
	bindtextdomain (GETTEXT_PACKAGE, LOCALEDIR);
	bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
	textdomain (GETTEXT_PACKAGE);
	_tmp0_ = _ ("Activity Journal");
	g_set_application_name (_tmp0_);
	gtk_clutter_init (&args_length1, &args);
	gtk_window_set_default_icon_name ("Activity Journal");
	_tmp1_ = gtk_css_provider_new ();
	provider = _tmp1_;
	{
		gchar* _tmp2_ = NULL;
		gchar* sheet;
		GdkScreen* _tmp3_ = NULL;
		GdkScreen* _tmp4_;
		GdkScreen* screen;
		GdkDisplay* _tmp5_ = NULL;
		GdkDisplay* _tmp6_;
		GdkDisplay* display;
		GdkDisplay* _tmp7_;
		GdkScreen* _tmp8_;
		_tmp2_ = journal_utils_get_style ("gtk-style.css");
		sheet = _tmp2_;
		gtk_css_provider_load_from_path (provider, sheet, &_inner_error_);
		if (_inner_error_ != NULL) {
			_g_free0 (sheet);
			goto __catch5_g_error;
		}
		_tmp3_ = gdk_screen_get_default ();
		_tmp4_ = _g_object_ref0 (_tmp3_);
		screen = _tmp4_;
		_tmp5_ = gdk_display_get_default ();
		_tmp6_ = _g_object_ref0 (_tmp5_);
		display = _tmp6_;
		_tmp7_ = display;
		if (_tmp7_ == NULL) {
			g_warning ("main.vala:52: Nu");
		}
		_tmp8_ = screen;
		gtk_style_context_add_provider_for_screen (_tmp8_, (GtkStyleProvider*) provider, (guint) GTK_STYLE_PROVIDER_PRIORITY_USER);
		_g_object_unref0 (display);
		_g_object_unref0 (screen);
		_g_free0 (sheet);
	}
	goto __finally5;
	__catch5_g_error:
	{
		GError* _error_ = NULL;
		GError* _tmp9_;
		const gchar* _tmp10_;
		_error_ = _inner_error_;
		_inner_error_ = NULL;
		_tmp9_ = _error_;
		_tmp10_ = _tmp9_->message;
		g_warning ("main.vala:57: %s", _tmp10_);
		_g_error_free0 (_error_);
	}
	__finally5:
	if (_inner_error_ != NULL) {
		_g_object_unref0 (provider);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
		g_clear_error (&_inner_error_);
		return 0;
	}
	_tmp11_ = journal_utils_new ();
	utils = _tmp11_;
	_tmp12_ = journal_app_new ();
	app = _tmp12_;
	_tmp13_ = journal_app_run (app);
	result = _tmp13_;
	_g_object_unref0 (app);
	_g_object_unref0 (utils);
	_g_object_unref0 (provider);
	return result;
}


int main (int argc, char ** argv) {
	g_type_init ();
	return _vala_main (argv, argc);
}



