/* reminderview.c generated by valac 0.16.0, the Vala compiler
 * generated from reminderview.vala, do not modify */

/* This file is part of GNOME Activity Journal.*/

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gd-main-view.h>


#define JOURNAL_TYPE_SINGLE_REMINDER_VIEW (journal_single_reminder_view_get_type ())
#define JOURNAL_SINGLE_REMINDER_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_SINGLE_REMINDER_VIEW, JournalSingleReminderView))
#define JOURNAL_SINGLE_REMINDER_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_SINGLE_REMINDER_VIEW, JournalSingleReminderViewClass))
#define JOURNAL_IS_SINGLE_REMINDER_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_SINGLE_REMINDER_VIEW))
#define JOURNAL_IS_SINGLE_REMINDER_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_SINGLE_REMINDER_VIEW))
#define JOURNAL_SINGLE_REMINDER_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_SINGLE_REMINDER_VIEW, JournalSingleReminderViewClass))

typedef struct _JournalSingleReminderView JournalSingleReminderView;
typedef struct _JournalSingleReminderViewClass JournalSingleReminderViewClass;
typedef struct _JournalSingleReminderViewPrivate JournalSingleReminderViewPrivate;

#define JOURNAL_TYPE_APP (journal_app_get_type ())
#define JOURNAL_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_APP, JournalApp))
#define JOURNAL_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_APP, JournalAppClass))
#define JOURNAL_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_APP))
#define JOURNAL_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_APP))
#define JOURNAL_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_APP, JournalAppClass))

typedef struct _JournalApp JournalApp;
typedef struct _JournalAppClass JournalAppClass;

#define JOURNAL_TYPE_ACTIVITY_MODEL (journal_activity_model_get_type ())
#define JOURNAL_ACTIVITY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_ACTIVITY_MODEL, JournalActivityModel))
#define JOURNAL_ACTIVITY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_ACTIVITY_MODEL, JournalActivityModelClass))
#define JOURNAL_IS_ACTIVITY_MODEL(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_ACTIVITY_MODEL))
#define JOURNAL_IS_ACTIVITY_MODEL_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_ACTIVITY_MODEL))
#define JOURNAL_ACTIVITY_MODEL_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_ACTIVITY_MODEL, JournalActivityModelClass))

typedef struct _JournalActivityModel JournalActivityModel;
typedef struct _JournalActivityModelClass JournalActivityModelClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define JOURNAL_TYPE_REMINDER_VIEW (journal_reminder_view_get_type ())
#define JOURNAL_REMINDER_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_REMINDER_VIEW, JournalReminderView))
#define JOURNAL_REMINDER_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_REMINDER_VIEW, JournalReminderViewClass))
#define JOURNAL_IS_REMINDER_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_REMINDER_VIEW))
#define JOURNAL_IS_REMINDER_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_REMINDER_VIEW))
#define JOURNAL_REMINDER_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_REMINDER_VIEW, JournalReminderViewClass))

typedef struct _JournalReminderView JournalReminderView;
typedef struct _JournalReminderViewClass JournalReminderViewClass;
typedef struct _JournalReminderViewPrivate JournalReminderViewPrivate;

#define JOURNAL_TYPE_ZEITGEIST_BACKEND (journal_zeitgeist_backend_get_type ())
#define JOURNAL_ZEITGEIST_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackend))
#define JOURNAL_ZEITGEIST_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackendClass))
#define JOURNAL_IS_ZEITGEIST_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND))
#define JOURNAL_IS_ZEITGEIST_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_ZEITGEIST_BACKEND))
#define JOURNAL_ZEITGEIST_BACKEND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackendClass))

typedef struct _JournalZeitgeistBackend JournalZeitgeistBackend;
typedef struct _JournalZeitgeistBackendClass JournalZeitgeistBackendClass;

struct _JournalSingleReminderView {
	GtkBox parent_instance;
	JournalSingleReminderViewPrivate * priv;
};

struct _JournalSingleReminderViewClass {
	GtkBoxClass parent_class;
};

struct _JournalSingleReminderViewPrivate {
	JournalApp* app;
	GdMainView* view;
	JournalActivityModel* model;
	GtkScrolledWindow* scrolled_window;
};

struct _JournalReminderView {
	GtkBox parent_instance;
	JournalReminderViewPrivate * priv;
};

struct _JournalReminderViewClass {
	GtkBoxClass parent_class;
};

struct _JournalReminderViewPrivate {
	JournalApp* app;
	JournalSingleReminderView** reminder_views;
	gint reminder_views_length1;
	gint _reminder_views_size_;
	gint num_days;
};


static gpointer journal_single_reminder_view_parent_class = NULL;
static gpointer journal_reminder_view_parent_class = NULL;

GType journal_single_reminder_view_get_type (void) G_GNUC_CONST;
GType journal_app_get_type (void) G_GNUC_CONST;
GType journal_activity_model_get_type (void) G_GNUC_CONST;
#define JOURNAL_SINGLE_REMINDER_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JOURNAL_TYPE_SINGLE_REMINDER_VIEW, JournalSingleReminderViewPrivate))
enum  {
	JOURNAL_SINGLE_REMINDER_VIEW_DUMMY_PROPERTY
};
JournalSingleReminderView* journal_single_reminder_view_new (JournalApp* app);
JournalSingleReminderView* journal_single_reminder_view_construct (GType object_type, JournalApp* app);
JournalActivityModel* journal_activity_model_new (void);
JournalActivityModel* journal_activity_model_construct (GType object_type);
GtkListStore* journal_activity_model_get_model (JournalActivityModel* self);
static void journal_single_reminder_view_finalize (GObject* obj);
GType journal_reminder_view_get_type (void) G_GNUC_CONST;
#define JOURNAL_REMINDER_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JOURNAL_TYPE_REMINDER_VIEW, JournalReminderViewPrivate))
enum  {
	JOURNAL_REMINDER_VIEW_DUMMY_PROPERTY
};
JournalReminderView* journal_reminder_view_new (JournalApp* app);
JournalReminderView* journal_reminder_view_construct (GType object_type, JournalApp* app);
static void journal_reminder_view_setup_ui (JournalReminderView* self);
GType journal_zeitgeist_backend_get_type (void) G_GNUC_CONST;
JournalZeitgeistBackend* journal_app_get_backend (JournalApp* self);
static void __lambda15_ (JournalReminderView* self);
static void ___lambda15__journal_zeitgeist_backend_events_loaded (JournalZeitgeistBackend* _sender, gpointer self);
static void journal_reminder_view_finalize (GObject* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


JournalSingleReminderView* journal_single_reminder_view_construct (GType object_type, JournalApp* app) {
	JournalSingleReminderView * self = NULL;
	JournalApp* _tmp0_;
	JournalApp* _tmp1_;
	GdMainView* _tmp2_;
	GdMainView* _tmp3_;
	JournalActivityModel* _tmp4_;
	GdMainView* _tmp5_;
	JournalActivityModel* _tmp6_;
	GtkListStore* _tmp7_ = NULL;
	GtkListStore* _tmp8_;
	GtkScrolledWindow* _tmp9_;
	GtkScrolledWindow* _tmp10_;
	GtkScrolledWindow* _tmp11_;
	GtkScrolledWindow* _tmp12_;
	GdMainView* _tmp13_;
	GtkButton* _tmp14_;
	GtkButton* _tmp15_;
	GtkButton* box;
	GtkWidget* _tmp16_ = NULL;
	GtkStyleContext* _tmp17_ = NULL;
	GtkScrolledWindow* _tmp18_;
	g_return_val_if_fail (app != NULL, NULL);
	self = (JournalSingleReminderView*) g_object_new (object_type, "orientation", GTK_ORIENTATION_VERTICAL, "spacing", 0, NULL);
	_tmp0_ = app;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->app);
	self->priv->app = _tmp1_;
	_tmp2_ = gd_main_view_new (GD_MAIN_VIEW_ICON);
	_tmp3_ = g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->view);
	self->priv->view = _tmp3_;
	_tmp4_ = journal_activity_model_new ();
	_g_object_unref0 (self->priv->model);
	self->priv->model = _tmp4_;
	_tmp5_ = self->priv->view;
	_tmp6_ = self->priv->model;
	_tmp7_ = journal_activity_model_get_model (_tmp6_);
	_tmp8_ = _tmp7_;
	gd_main_view_set_model (_tmp5_, (GtkTreeModel*) _tmp8_);
	_g_object_unref0 (_tmp8_);
	_tmp9_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	_tmp10_ = g_object_ref_sink (_tmp9_);
	_g_object_unref0 (self->priv->scrolled_window);
	self->priv->scrolled_window = _tmp10_;
	_tmp11_ = self->priv->scrolled_window;
	gtk_scrolled_window_set_policy (_tmp11_, GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);
	_tmp12_ = self->priv->scrolled_window;
	_tmp13_ = self->priv->view;
	gtk_scrolled_window_add_with_viewport (_tmp12_, (GtkWidget*) _tmp13_);
	_tmp14_ = (GtkButton*) gtk_button_new_with_label ("Test");
	_tmp15_ = g_object_ref_sink (_tmp14_);
	box = _tmp15_;
	gtk_widget_set_sensitive ((GtkWidget*) box, FALSE);
	gtk_widget_set_name ((GtkWidget*) box, "box-label");
	_tmp16_ = gtk_bin_get_child ((GtkBin*) box);
	_tmp17_ = gtk_widget_get_style_context (_tmp16_);
	gtk_style_context_add_class (_tmp17_, "day-label");
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) box, FALSE, FALSE, (guint) 0);
	_tmp18_ = self->priv->scrolled_window;
	gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp18_, TRUE, TRUE, (guint) 0);
	_g_object_unref0 (box);
	return self;
}


JournalSingleReminderView* journal_single_reminder_view_new (JournalApp* app) {
	return journal_single_reminder_view_construct (JOURNAL_TYPE_SINGLE_REMINDER_VIEW, app);
}


static void journal_single_reminder_view_class_init (JournalSingleReminderViewClass * klass) {
	journal_single_reminder_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (JournalSingleReminderViewPrivate));
	G_OBJECT_CLASS (klass)->finalize = journal_single_reminder_view_finalize;
}


static void journal_single_reminder_view_instance_init (JournalSingleReminderView * self) {
	self->priv = JOURNAL_SINGLE_REMINDER_VIEW_GET_PRIVATE (self);
}


static void journal_single_reminder_view_finalize (GObject* obj) {
	JournalSingleReminderView * self;
	self = JOURNAL_SINGLE_REMINDER_VIEW (obj);
	_g_object_unref0 (self->priv->app);
	_g_object_unref0 (self->priv->view);
	_g_object_unref0 (self->priv->model);
	_g_object_unref0 (self->priv->scrolled_window);
	G_OBJECT_CLASS (journal_single_reminder_view_parent_class)->finalize (obj);
}


GType journal_single_reminder_view_get_type (void) {
	static volatile gsize journal_single_reminder_view_type_id__volatile = 0;
	if (g_once_init_enter (&journal_single_reminder_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JournalSingleReminderViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) journal_single_reminder_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JournalSingleReminderView), 0, (GInstanceInitFunc) journal_single_reminder_view_instance_init, NULL };
		GType journal_single_reminder_view_type_id;
		journal_single_reminder_view_type_id = g_type_register_static (GTK_TYPE_BOX, "JournalSingleReminderView", &g_define_type_info, 0);
		g_once_init_leave (&journal_single_reminder_view_type_id__volatile, journal_single_reminder_view_type_id);
	}
	return journal_single_reminder_view_type_id__volatile;
}


static void __lambda15_ (JournalReminderView* self) {
}


static void ___lambda15__journal_zeitgeist_backend_events_loaded (JournalZeitgeistBackend* _sender, gpointer self) {
	__lambda15_ (self);
}


JournalReminderView* journal_reminder_view_construct (GType object_type, JournalApp* app) {
	JournalReminderView * self = NULL;
	JournalApp* _tmp0_;
	JournalApp* _tmp1_;
	gint _tmp2_;
	JournalSingleReminderView** _tmp3_ = NULL;
	JournalApp* _tmp4_;
	JournalZeitgeistBackend* _tmp5_;
	JournalZeitgeistBackend* _tmp6_;
	g_return_val_if_fail (app != NULL, NULL);
	self = (JournalReminderView*) g_object_new (object_type, "orientation", GTK_ORIENTATION_VERTICAL, "spacing", 0, NULL);
	_tmp0_ = app;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->app);
	self->priv->app = _tmp1_;
	_tmp2_ = self->priv->num_days;
	_tmp3_ = g_new0 (JournalSingleReminderView*, _tmp2_ + 1);
	self->priv->reminder_views = (_vala_array_free (self->priv->reminder_views, self->priv->reminder_views_length1, (GDestroyNotify) g_object_unref), NULL);
	self->priv->reminder_views = _tmp3_;
	self->priv->reminder_views_length1 = _tmp2_;
	self->priv->_reminder_views_size_ = self->priv->reminder_views_length1;
	self->priv->num_days = 3;
	journal_reminder_view_setup_ui (self);
	_tmp4_ = app;
	_tmp5_ = journal_app_get_backend (_tmp4_);
	_tmp6_ = _tmp5_;
	g_signal_connect_object (_tmp6_, "events-loaded", (GCallback) ___lambda15__journal_zeitgeist_backend_events_loaded, self, 0);
	return self;
}


JournalReminderView* journal_reminder_view_new (JournalApp* app) {
	return journal_reminder_view_construct (JOURNAL_TYPE_REMINDER_VIEW, app);
}


static void journal_reminder_view_setup_ui (JournalReminderView* self) {
	g_return_if_fail (self != NULL);
	{
		gint i;
		i = 0;
		{
			gboolean _tmp0_;
			_tmp0_ = TRUE;
			while (TRUE) {
				gboolean _tmp1_;
				gint _tmp3_;
				gint _tmp4_;
				JournalSingleReminderView** _tmp5_;
				gint _tmp5__length1;
				gint _tmp6_;
				JournalApp* _tmp7_;
				JournalSingleReminderView* _tmp8_;
				JournalSingleReminderView* _tmp9_;
				JournalSingleReminderView* _tmp10_;
				_tmp1_ = _tmp0_;
				if (!_tmp1_) {
					gint _tmp2_;
					_tmp2_ = i;
					i = _tmp2_ + 1;
				}
				_tmp0_ = FALSE;
				_tmp3_ = i;
				_tmp4_ = self->priv->num_days;
				if (!(_tmp3_ < _tmp4_)) {
					break;
				}
				_tmp5_ = self->priv->reminder_views;
				_tmp5__length1 = self->priv->reminder_views_length1;
				_tmp6_ = i;
				_tmp7_ = self->priv->app;
				_tmp8_ = journal_single_reminder_view_new (_tmp7_);
				_tmp9_ = g_object_ref_sink (_tmp8_);
				_g_object_unref0 (_tmp5_[_tmp6_]);
				_tmp5_[_tmp6_] = _tmp9_;
				_tmp10_ = _tmp5_[_tmp6_];
			}
		}
	}
	{
		gint i;
		i = 0;
		{
			gboolean _tmp11_;
			_tmp11_ = TRUE;
			while (TRUE) {
				gboolean _tmp12_;
				gint _tmp14_;
				gint _tmp15_;
				JournalSingleReminderView** _tmp16_;
				gint _tmp16__length1;
				gint _tmp17_;
				JournalSingleReminderView* _tmp18_;
				_tmp12_ = _tmp11_;
				if (!_tmp12_) {
					gint _tmp13_;
					_tmp13_ = i;
					i = _tmp13_ + 1;
				}
				_tmp11_ = FALSE;
				_tmp14_ = i;
				_tmp15_ = self->priv->num_days;
				if (!(_tmp14_ < _tmp15_)) {
					break;
				}
				_tmp16_ = self->priv->reminder_views;
				_tmp16__length1 = self->priv->reminder_views_length1;
				_tmp17_ = i;
				_tmp18_ = _tmp16_[_tmp17_];
				gtk_box_pack_start ((GtkBox*) self, (GtkWidget*) _tmp18_, TRUE, TRUE, (guint) 2);
			}
		}
	}
}


static void journal_reminder_view_class_init (JournalReminderViewClass * klass) {
	journal_reminder_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (JournalReminderViewPrivate));
	G_OBJECT_CLASS (klass)->finalize = journal_reminder_view_finalize;
}


static void journal_reminder_view_instance_init (JournalReminderView * self) {
	self->priv = JOURNAL_REMINDER_VIEW_GET_PRIVATE (self);
}


static void journal_reminder_view_finalize (GObject* obj) {
	JournalReminderView * self;
	self = JOURNAL_REMINDER_VIEW (obj);
	_g_object_unref0 (self->priv->app);
	self->priv->reminder_views = (_vala_array_free (self->priv->reminder_views, self->priv->reminder_views_length1, (GDestroyNotify) g_object_unref), NULL);
	G_OBJECT_CLASS (journal_reminder_view_parent_class)->finalize (obj);
}


GType journal_reminder_view_get_type (void) {
	static volatile gsize journal_reminder_view_type_id__volatile = 0;
	if (g_once_init_enter (&journal_reminder_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JournalReminderViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) journal_reminder_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JournalReminderView), 0, (GInstanceInitFunc) journal_reminder_view_instance_init, NULL };
		GType journal_reminder_view_type_id;
		journal_reminder_view_type_id = g_type_register_static (GTK_TYPE_BOX, "JournalReminderView", &g_define_type_info, 0);
		g_once_init_leave (&journal_reminder_view_type_id__volatile, journal_reminder_view_type_id);
	}
	return journal_reminder_view_type_id__volatile;
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



