/* revealer.c generated by valac 0.16.0, the Vala compiler
 * generated from revealer.vala, do not modify */

/* -*- Mode: vala; indent-tabs-mode: t; c-basic-offset: 2; tab-width: 8 -*- */
/*
 * Copyright (C) 2011 Alexander Larsson <alexl@redhat.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <gdk/gdk.h>
#include <float.h>
#include <math.h>
#include <stdio.h>


#define JOURNAL_TYPE_REVEALER (journal_revealer_get_type ())
#define JOURNAL_REVEALER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_REVEALER, JournalRevealer))
#define JOURNAL_REVEALER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_REVEALER, JournalRevealerClass))
#define JOURNAL_IS_REVEALER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_REVEALER))
#define JOURNAL_IS_REVEALER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_REVEALER))
#define JOURNAL_REVEALER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_REVEALER, JournalRevealerClass))

typedef struct _JournalRevealer JournalRevealer;
typedef struct _JournalRevealerClass JournalRevealerClass;
typedef struct _JournalRevealerPrivate JournalRevealerPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _JournalRevealer {
	GtkViewport parent_instance;
	JournalRevealerPrivate * priv;
	GdkWindow* bin_window;
	GdkWindow* view_window;
	GtkAdjustment* vadjustment;
	gdouble amount_visible;
	gdouble target_amount;
};

struct _JournalRevealerClass {
	GtkViewportClass parent_class;
};

struct _JournalRevealerPrivate {
	guint timeout;
};


static gpointer journal_revealer_parent_class = NULL;

GType journal_revealer_get_type (void) G_GNUC_CONST;
#define JOURNAL_REVEALER_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JOURNAL_TYPE_REVEALER, JournalRevealerPrivate))
enum  {
	JOURNAL_REVEALER_DUMMY_PROPERTY
};
#define JOURNAL_REVEALER_animation_time 200
#define JOURNAL_REVEALER_animation_n_steps 8
JournalRevealer* journal_revealer_new (void);
JournalRevealer* journal_revealer_construct (GType object_type);
static gboolean journal_revealer_real_enter_notify_event (GtkWidget* base, GdkEventCrossing* event);
static gboolean journal_revealer_real_leave_notify_event (GtkWidget* base, GdkEventCrossing* event);
static void journal_revealer_ensure_timer (JournalRevealer* self);
static gboolean journal_revealer_animate_cb (JournalRevealer* self);
static gboolean _journal_revealer_animate_cb_gsource_func (gpointer self);
static void journal_revealer_real_show (GtkWidget* base);
void journal_revealer_reveal (JournalRevealer* self);
static void journal_revealer_real_hide (GtkWidget* base);
void journal_revealer_unreveal (JournalRevealer* self);
static void journal_revealer_real_get_preferred_width (GtkWidget* base, gint* minimum_width, gint* natural_width);
static void journal_revealer_real_get_preferred_width_for_height (GtkWidget* base, gint height, gint* minimum_width, gint* natural_width);
static void journal_revealer_real_size_allocate (GtkWidget* base, GtkAllocation* allocation);
static void journal_revealer_finalize (GObject* obj);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


JournalRevealer* journal_revealer_construct (GType object_type) {
	JournalRevealer * self = NULL;
	gdouble _tmp0_;
	GtkAdjustment* _tmp1_ = NULL;
	GtkAdjustment* _tmp2_;
	self = (JournalRevealer*) g_object_new (object_type, NULL);
	gtk_widget_add_events ((GtkWidget*) self, (gint) (GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK));
	gtk_viewport_set_shadow_type ((GtkViewport*) self, GTK_SHADOW_NONE);
	self->amount_visible = 0.0;
	_tmp0_ = self->amount_visible;
	self->target_amount = _tmp0_;
	_tmp1_ = gtk_viewport_get_vadjustment ((GtkViewport*) self);
	_tmp2_ = _g_object_ref0 (_tmp1_);
	_g_object_unref0 (self->vadjustment);
	self->vadjustment = _tmp2_;
	return self;
}


JournalRevealer* journal_revealer_new (void) {
	return journal_revealer_construct (JOURNAL_TYPE_REVEALER);
}


static gboolean journal_revealer_real_enter_notify_event (GtkWidget* base, GdkEventCrossing* event) {
	JournalRevealer * self;
	gboolean result = FALSE;
	FILE* _tmp0_;
	self = (JournalRevealer*) base;
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "entro");
	result = FALSE;
	return result;
}


static gboolean journal_revealer_real_leave_notify_event (GtkWidget* base, GdkEventCrossing* event) {
	JournalRevealer * self;
	gboolean result = FALSE;
	FILE* _tmp0_;
	self = (JournalRevealer*) base;
	g_return_val_if_fail (event != NULL, FALSE);
	_tmp0_ = stdout;
	fprintf (_tmp0_, "esco");
	result = FALSE;
	return result;
}


static gboolean _journal_revealer_animate_cb_gsource_func (gpointer self) {
	gboolean result;
	result = journal_revealer_animate_cb (self);
	return result;
}


static void journal_revealer_ensure_timer (JournalRevealer* self) {
	guint _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->timeout;
	if (_tmp0_ == ((guint) 0)) {
		gdouble _tmp1_;
		gdouble _tmp2_;
		guint _tmp3_ = 0U;
		_tmp1_ = self->amount_visible;
		_tmp2_ = self->target_amount;
		if (_tmp1_ == _tmp2_) {
			return;
		}
		_tmp3_ = gdk_threads_add_timeout ((guint) (JOURNAL_REVEALER_animation_time / JOURNAL_REVEALER_animation_n_steps), _journal_revealer_animate_cb_gsource_func, self);
		self->priv->timeout = _tmp3_;
	}
}


static void journal_revealer_real_show (GtkWidget* base) {
	JournalRevealer * self;
	gdouble _tmp0_;
	self = (JournalRevealer*) base;
	GTK_WIDGET_CLASS (journal_revealer_parent_class)->show ((GtkWidget*) GTK_VIEWPORT (self));
	_tmp0_ = self->target_amount;
	if (_tmp0_ != 1.0) {
		journal_revealer_reveal (self);
	}
}


static void journal_revealer_real_hide (GtkWidget* base) {
	JournalRevealer * self;
	guint _tmp0_;
	self = (JournalRevealer*) base;
	GTK_WIDGET_CLASS (journal_revealer_parent_class)->hide ((GtkWidget*) GTK_VIEWPORT (self));
	self->target_amount = (gdouble) 0;
	self->amount_visible = (gdouble) 0;
	_tmp0_ = self->priv->timeout;
	if (_tmp0_ != ((guint) 0)) {
		guint _tmp1_;
		_tmp1_ = self->priv->timeout;
		g_source_remove (_tmp1_);
		self->priv->timeout = (guint) 0;
	}
}


void journal_revealer_reveal (JournalRevealer* self) {
	g_return_if_fail (self != NULL);
	self->target_amount = 1.0;
	gtk_widget_show ((GtkWidget*) self);
	journal_revealer_ensure_timer (self);
}


void journal_revealer_unreveal (JournalRevealer* self) {
	g_return_if_fail (self != NULL);
	self->target_amount = 0.0;
	journal_revealer_ensure_timer (self);
}


static gboolean journal_revealer_animate_cb (JournalRevealer* self) {
	gboolean result = FALSE;
	gdouble delta;
	gdouble _tmp0_;
	gdouble _tmp1_;
	gdouble _tmp10_;
	gdouble _tmp11_;
	g_return_val_if_fail (self != NULL, FALSE);
	delta = 1.0 / JOURNAL_REVEALER_animation_n_steps;
	_tmp0_ = self->amount_visible;
	_tmp1_ = self->target_amount;
	if (_tmp0_ < _tmp1_) {
		gdouble _tmp2_;
		gdouble _tmp3_;
		gdouble _tmp4_;
		gdouble _tmp5_ = 0.0;
		_tmp2_ = self->target_amount;
		_tmp3_ = self->amount_visible;
		_tmp4_ = delta;
		_tmp5_ = MIN (_tmp2_, _tmp3_ + _tmp4_);
		self->amount_visible = _tmp5_;
	} else {
		gdouble _tmp6_;
		gdouble _tmp7_;
		gdouble _tmp8_;
		gdouble _tmp9_ = 0.0;
		_tmp6_ = self->target_amount;
		_tmp7_ = self->amount_visible;
		_tmp8_ = delta;
		_tmp9_ = MAX (_tmp6_, _tmp7_ - _tmp8_);
		self->amount_visible = _tmp9_;
	}
	gtk_widget_queue_resize ((GtkWidget*) self);
	_tmp10_ = self->amount_visible;
	_tmp11_ = self->target_amount;
	if (_tmp10_ == _tmp11_) {
		gdouble _tmp12_;
		self->priv->timeout = (guint) 0;
		_tmp12_ = self->amount_visible;
		if (_tmp12_ == ((gdouble) 0)) {
			gtk_widget_hide ((GtkWidget*) self);
		}
		result = FALSE;
		return result;
	}
	result = TRUE;
	return result;
}


static void journal_revealer_real_get_preferred_width (GtkWidget* base, gint* minimum_width, gint* natural_width) {
	JournalRevealer * self;
	gint _vala_minimum_width = 0;
	gint _vala_natural_width = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	gint _tmp2_;
	gdouble _tmp3_;
	gint _tmp4_;
	gdouble _tmp5_;
	self = (JournalRevealer*) base;
	GTK_WIDGET_CLASS (journal_revealer_parent_class)->get_preferred_height ((GtkWidget*) GTK_VIEWPORT (self), &_tmp0_, &_tmp1_);
	_vala_minimum_width = _tmp0_;
	_vala_natural_width = _tmp1_;
	_tmp2_ = _vala_minimum_width;
	_tmp3_ = self->amount_visible;
	_vala_minimum_width = (gint) (_tmp2_ * _tmp3_);
	_tmp4_ = _vala_natural_width;
	_tmp5_ = self->amount_visible;
	_vala_natural_width = (gint) (_tmp4_ * _tmp5_);
	if (minimum_width) {
		*minimum_width = _vala_minimum_width;
	}
	if (natural_width) {
		*natural_width = _vala_natural_width;
	}
}


static void journal_revealer_real_get_preferred_width_for_height (GtkWidget* base, gint height, gint* minimum_width, gint* natural_width) {
	JournalRevealer * self;
	gint _vala_minimum_width = 0;
	gint _vala_natural_width = 0;
	gint _tmp0_;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	gint _tmp3_;
	gdouble _tmp4_;
	gint _tmp5_;
	gdouble _tmp6_;
	self = (JournalRevealer*) base;
	_tmp0_ = height;
	GTK_WIDGET_CLASS (journal_revealer_parent_class)->get_preferred_width_for_height ((GtkWidget*) GTK_VIEWPORT (self), _tmp0_, &_tmp1_, &_tmp2_);
	_vala_minimum_width = _tmp1_;
	_vala_natural_width = _tmp2_;
	_tmp3_ = _vala_minimum_width;
	_tmp4_ = self->amount_visible;
	_vala_minimum_width = (gint) (_tmp3_ * _tmp4_);
	_tmp5_ = _vala_natural_width;
	_tmp6_ = self->amount_visible;
	_vala_natural_width = (gint) (_tmp5_ * _tmp6_);
	if (minimum_width) {
		*minimum_width = _vala_minimum_width;
	}
	if (natural_width) {
		*natural_width = _vala_natural_width;
	}
}


static void journal_revealer_real_size_allocate (GtkWidget* base, GtkAllocation* allocation) {
	JournalRevealer * self;
	GtkAllocation _tmp0_;
	GtkAdjustment* _tmp1_;
	GtkAdjustment* _tmp2_;
	gdouble _tmp3_ = 0.0;
	gdouble upper;
	GtkAdjustment* _tmp4_;
	GtkAdjustment* _tmp5_;
	GtkAllocation _tmp6_;
	gint _tmp7_;
	self = (JournalRevealer*) base;
	g_return_if_fail (allocation != NULL);
	_tmp0_ = *allocation;
	GTK_WIDGET_CLASS (journal_revealer_parent_class)->size_allocate ((GtkWidget*) GTK_VIEWPORT (self), &_tmp0_);
	_tmp1_ = gtk_scrollable_get_hadjustment ((GtkScrollable*) self);
	_tmp2_ = _tmp1_;
	_tmp3_ = gtk_adjustment_get_upper (_tmp2_);
	upper = _tmp3_;
	_tmp4_ = gtk_scrollable_get_hadjustment ((GtkScrollable*) self);
	_tmp5_ = _tmp4_;
	_tmp6_ = *allocation;
	_tmp7_ = _tmp6_.width;
	gtk_adjustment_set_value (_tmp5_, upper - _tmp7_);
}


static void journal_revealer_class_init (JournalRevealerClass * klass) {
	journal_revealer_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (JournalRevealerPrivate));
	GTK_WIDGET_CLASS (klass)->enter_notify_event = journal_revealer_real_enter_notify_event;
	GTK_WIDGET_CLASS (klass)->leave_notify_event = journal_revealer_real_leave_notify_event;
	GTK_WIDGET_CLASS (klass)->show = journal_revealer_real_show;
	GTK_WIDGET_CLASS (klass)->hide = journal_revealer_real_hide;
	GTK_WIDGET_CLASS (klass)->get_preferred_width = journal_revealer_real_get_preferred_width;
	GTK_WIDGET_CLASS (klass)->get_preferred_width_for_height = journal_revealer_real_get_preferred_width_for_height;
	GTK_WIDGET_CLASS (klass)->size_allocate = journal_revealer_real_size_allocate;
	G_OBJECT_CLASS (klass)->finalize = journal_revealer_finalize;
}


static void journal_revealer_instance_init (JournalRevealer * self) {
	self->priv = JOURNAL_REVEALER_GET_PRIVATE (self);
}


static void journal_revealer_finalize (GObject* obj) {
	JournalRevealer * self;
	self = JOURNAL_REVEALER (obj);
	_g_object_unref0 (self->bin_window);
	_g_object_unref0 (self->view_window);
	_g_object_unref0 (self->vadjustment);
	G_OBJECT_CLASS (journal_revealer_parent_class)->finalize (obj);
}


GType journal_revealer_get_type (void) {
	static volatile gsize journal_revealer_type_id__volatile = 0;
	if (g_once_init_enter (&journal_revealer_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JournalRevealerClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) journal_revealer_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JournalRevealer), 0, (GInstanceInitFunc) journal_revealer_instance_init, NULL };
		GType journal_revealer_type_id;
		journal_revealer_type_id = g_type_register_static (GTK_TYPE_VIEWPORT, "JournalRevealer", &g_define_type_info, 0);
		g_once_init_leave (&journal_revealer_type_id__volatile, journal_revealer_type_id);
	}
	return journal_revealer_type_id__volatile;
}



