/* selectionbar.c generated by valac 0.16.0, the Vala compiler
 * generated from selectionbar.vala, do not modify */

/* This file is part of GNOME Activity Journal.*/

#include <glib.h>
#include <glib-object.h>
#include <clutter-gtk/clutter-gtk.h>
#include <gtk/gtk.h>
#include <float.h>
#include <math.h>
#include <clutter/clutter.h>
#include <gio/gio.h>


#define JOURNAL_TYPE_SELECTIONBAR (journal_selectionbar_get_type ())
#define JOURNAL_SELECTIONBAR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_SELECTIONBAR, JournalSelectionbar))
#define JOURNAL_SELECTIONBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_SELECTIONBAR, JournalSelectionbarClass))
#define JOURNAL_IS_SELECTIONBAR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_SELECTIONBAR))
#define JOURNAL_IS_SELECTIONBAR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_SELECTIONBAR))
#define JOURNAL_SELECTIONBAR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_SELECTIONBAR, JournalSelectionbarClass))

typedef struct _JournalSelectionbar JournalSelectionbar;
typedef struct _JournalSelectionbarClass JournalSelectionbarClass;
typedef struct _JournalSelectionbarPrivate JournalSelectionbarPrivate;

#define JOURNAL_TYPE_APP (journal_app_get_type ())
#define JOURNAL_APP(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_APP, JournalApp))
#define JOURNAL_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_APP, JournalAppClass))
#define JOURNAL_IS_APP(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_APP))
#define JOURNAL_IS_APP_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_APP))
#define JOURNAL_APP_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_APP, JournalAppClass))

typedef struct _JournalApp JournalApp;
typedef struct _JournalAppClass JournalAppClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
typedef struct _JournalAppPrivate JournalAppPrivate;

struct _JournalSelectionbar {
	GObject parent_instance;
	JournalSelectionbarPrivate * priv;
};

struct _JournalSelectionbarClass {
	GObjectClass parent_class;
};

struct _JournalSelectionbarPrivate {
	JournalApp* app;
	GtkClutterActor* gtk_actor;
	GtkToolbar* toolbar;
	GtkToggleToolButton* favorite_btn;
	GtkToggleToolButton* remove_btn;
	gboolean _visible;
};

struct _JournalApp {
	GObject parent_instance;
	JournalAppPrivate * priv;
	GtkApplicationWindow* window;
	GtkNotebook* notebook;
	GtkBox* main_box;
	GtkClutterEmbed* embed;
	ClutterStage* stage;
	ClutterActor* box;
	GSimpleAction* action_fullscreen;
	guint duration;
};

struct _JournalAppClass {
	GObjectClass parent_class;
};


static gpointer journal_selectionbar_parent_class = NULL;

GType journal_selectionbar_get_type (void) G_GNUC_CONST;
GType journal_app_get_type (void) G_GNUC_CONST;
#define JOURNAL_SELECTIONBAR_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JOURNAL_TYPE_SELECTIONBAR, JournalSelectionbarPrivate))
enum  {
	JOURNAL_SELECTIONBAR_DUMMY_PROPERTY,
	JOURNAL_SELECTIONBAR_ACTOR
};
#define JOURNAL_SELECTIONBAR_spacing 60.0f
JournalSelectionbar* journal_selectionbar_new (JournalApp* app);
JournalSelectionbar* journal_selectionbar_construct (GType object_type, JournalApp* app);
ClutterActor* journal_selectionbar_get_actor (JournalSelectionbar* self);
static void __lambda24_ (JournalSelectionbar* self);
void journal_selectionbar_toggle_visible (JournalSelectionbar* self);
static void ___lambda24__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self);
static gboolean journal_selectionbar_get_visible (JournalSelectionbar* self);
static void journal_selectionbar_set_visible (JournalSelectionbar* self, gboolean value);
static void journal_selectionbar_show (JournalSelectionbar* self);
static void journal_selectionbar_hide (JournalSelectionbar* self);
static void __lambda25_ (JournalSelectionbar* self);
static void ___lambda25__clutter_animation_completed (ClutterAnimation* _sender, gpointer self);
static void journal_selectionbar_finalize (GObject* obj);
static void _vala_journal_selectionbar_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);
static void _vala_journal_selectionbar_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec);


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void __lambda24_ (JournalSelectionbar* self) {
	journal_selectionbar_toggle_visible (self);
}


static void ___lambda24__g_object_notify (GObject* _sender, GParamSpec* pspec, gpointer self) {
	__lambda24_ (self);
}


JournalSelectionbar* journal_selectionbar_construct (GType object_type, JournalApp* app) {
	JournalSelectionbar * self = NULL;
	JournalApp* _tmp0_;
	JournalApp* _tmp1_;
	GtkToolbar* _tmp2_;
	GtkToolbar* _tmp3_;
	GtkToolbar* _tmp4_;
	GtkToolbar* _tmp5_;
	GtkToolbar* _tmp6_;
	GtkClutterActor* _tmp7_;
	GtkClutterActor* _tmp8_;
	GtkClutterActor* _tmp9_;
	GtkClutterActor* _tmp10_;
	GtkWidget* _tmp11_ = NULL;
	GtkStyleContext* _tmp12_ = NULL;
	GtkToggleToolButton* _tmp13_;
	GtkToggleToolButton* _tmp14_;
	GtkToolbar* _tmp15_;
	GtkToggleToolButton* _tmp16_;
	GtkToggleToolButton* _tmp17_;
	GtkSeparatorToolItem* _tmp18_;
	GtkSeparatorToolItem* _tmp19_;
	GtkSeparatorToolItem* separator;
	GtkToolbar* _tmp20_;
	GtkToggleToolButton* _tmp21_;
	GtkToggleToolButton* _tmp22_;
	GtkToolbar* _tmp23_;
	GtkToggleToolButton* _tmp24_;
	GtkToggleToolButton* _tmp25_;
	GtkToolbar* _tmp26_;
	ClutterActor* _tmp27_;
	ClutterActor* _tmp28_;
	ClutterActor* _tmp29_;
	ClutterActor* _tmp30_;
	JournalApp* _tmp31_;
	JournalApp* _tmp32_;
	ClutterStage* _tmp33_;
	ClutterActor* _tmp34_;
	ClutterActor* _tmp35_;
	g_return_val_if_fail (app != NULL, NULL);
	self = (JournalSelectionbar*) g_object_new (object_type, NULL);
	_tmp0_ = app;
	_tmp1_ = _g_object_ref0 (_tmp0_);
	_g_object_unref0 (self->priv->app);
	self->priv->app = _tmp1_;
	self->priv->_visible = FALSE;
	_tmp2_ = (GtkToolbar*) gtk_toolbar_new ();
	_tmp3_ = g_object_ref_sink (_tmp2_);
	_g_object_unref0 (self->priv->toolbar);
	self->priv->toolbar = _tmp3_;
	_tmp4_ = self->priv->toolbar;
	gtk_toolbar_set_show_arrow (_tmp4_, FALSE);
	_tmp5_ = self->priv->toolbar;
	gtk_toolbar_set_icon_size (_tmp5_, (gint) GTK_ICON_SIZE_LARGE_TOOLBAR);
	_tmp6_ = self->priv->toolbar;
	_tmp7_ = (GtkClutterActor*) gtk_clutter_actor_new_with_contents ((GtkWidget*) _tmp6_);
	_tmp8_ = g_object_ref_sink (_tmp7_);
	_g_object_unref0 (self->priv->gtk_actor);
	self->priv->gtk_actor = _tmp8_;
	_tmp9_ = self->priv->gtk_actor;
	clutter_actor_set_opacity ((ClutterActor*) _tmp9_, (guint) 0);
	_tmp10_ = self->priv->gtk_actor;
	_tmp11_ = gtk_clutter_actor_get_widget (_tmp10_);
	_tmp12_ = gtk_widget_get_style_context (_tmp11_);
	gtk_style_context_add_class (_tmp12_, "osd");
	_tmp13_ = (GtkToggleToolButton*) gtk_toggle_tool_button_new ();
	_tmp14_ = g_object_ref_sink (_tmp13_);
	_g_object_unref0 (self->priv->favorite_btn);
	self->priv->favorite_btn = _tmp14_;
	_tmp15_ = self->priv->toolbar;
	_tmp16_ = self->priv->favorite_btn;
	gtk_toolbar_insert (_tmp15_, (GtkToolItem*) _tmp16_, 0);
	_tmp17_ = self->priv->favorite_btn;
	gtk_tool_button_set_icon_name ((GtkToolButton*) _tmp17_, "emblem-favorite-symbolic");
	_tmp18_ = (GtkSeparatorToolItem*) gtk_separator_tool_item_new ();
	_tmp19_ = g_object_ref_sink (_tmp18_);
	separator = _tmp19_;
	_tmp20_ = self->priv->toolbar;
	gtk_toolbar_insert (_tmp20_, (GtkToolItem*) separator, 1);
	_tmp21_ = (GtkToggleToolButton*) gtk_toggle_tool_button_new ();
	_tmp22_ = g_object_ref_sink (_tmp21_);
	_g_object_unref0 (self->priv->remove_btn);
	self->priv->remove_btn = _tmp22_;
	_tmp23_ = self->priv->toolbar;
	_tmp24_ = self->priv->remove_btn;
	gtk_toolbar_insert (_tmp23_, (GtkToolItem*) _tmp24_, 2);
	_tmp25_ = self->priv->remove_btn;
	gtk_tool_button_set_icon_name ((GtkToolButton*) _tmp25_, "edit-delete-symbolic");
	_tmp26_ = self->priv->toolbar;
	gtk_widget_show_all ((GtkWidget*) _tmp26_);
	_tmp27_ = journal_selectionbar_get_actor (self);
	_tmp28_ = _tmp27_;
	clutter_actor_set_reactive (_tmp28_, TRUE);
	_tmp29_ = journal_selectionbar_get_actor (self);
	_tmp30_ = _tmp29_;
	clutter_actor_hide (_tmp30_);
	_tmp31_ = app;
	g_signal_connect_object ((GObject*) _tmp31_, "notify::selection-mode", (GCallback) ___lambda24__g_object_notify, self, 0);
	_tmp32_ = app;
	_tmp33_ = _tmp32_->stage;
	_tmp34_ = journal_selectionbar_get_actor (self);
	_tmp35_ = _tmp34_;
	clutter_container_add_actor ((ClutterContainer*) _tmp33_, _tmp35_);
	_g_object_unref0 (separator);
	return self;
}


JournalSelectionbar* journal_selectionbar_new (JournalApp* app) {
	return journal_selectionbar_construct (JOURNAL_TYPE_SELECTIONBAR, app);
}


void journal_selectionbar_toggle_visible (JournalSelectionbar* self) {
	gboolean _tmp0_;
	gboolean _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = journal_selectionbar_get_visible (self);
	_tmp1_ = _tmp0_;
	journal_selectionbar_set_visible (self, !_tmp1_);
}


static void journal_selectionbar_show (JournalSelectionbar* self) {
	ClutterActor* _tmp0_;
	ClutterActor* _tmp1_;
	ClutterActor* _tmp2_;
	ClutterActor* _tmp3_;
	ClutterActor* _tmp4_;
	ClutterActor* _tmp5_;
	JournalApp* _tmp6_;
	guint _tmp7_;
	g_return_if_fail (self != NULL);
	_tmp0_ = journal_selectionbar_get_actor (self);
	_tmp1_ = _tmp0_;
	clutter_actor_show (_tmp1_);
	_tmp2_ = journal_selectionbar_get_actor (self);
	_tmp3_ = _tmp2_;
	clutter_actor_queue_redraw (_tmp3_);
	_tmp4_ = journal_selectionbar_get_actor (self);
	_tmp5_ = _tmp4_;
	_tmp6_ = self->priv->app;
	_tmp7_ = _tmp6_->duration;
	clutter_actor_animate (_tmp5_, (gulong) CLUTTER_LINEAR, _tmp7_, "opacity", 255, NULL);
}


static void __lambda25_ (JournalSelectionbar* self) {
	ClutterActor* _tmp0_;
	ClutterActor* _tmp1_;
	_tmp0_ = journal_selectionbar_get_actor (self);
	_tmp1_ = _tmp0_;
	clutter_actor_hide (_tmp1_);
}


static void ___lambda25__clutter_animation_completed (ClutterAnimation* _sender, gpointer self) {
	__lambda25_ (self);
}


static void journal_selectionbar_hide (JournalSelectionbar* self) {
	ClutterActor* _tmp0_;
	ClutterActor* _tmp1_;
	JournalApp* _tmp2_;
	guint _tmp3_;
	ClutterAnimation* _tmp4_ = NULL;
	ClutterAnimation* _tmp5_;
	ClutterAnimation* anim;
	g_return_if_fail (self != NULL);
	_tmp0_ = journal_selectionbar_get_actor (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = self->priv->app;
	_tmp3_ = _tmp2_->duration;
	_tmp4_ = clutter_actor_animate (_tmp1_, (gulong) CLUTTER_LINEAR, _tmp3_, "opacity", 0, NULL);
	_tmp5_ = _g_object_ref0 (_tmp4_);
	anim = _tmp5_;
	g_signal_connect_object (anim, "completed", (GCallback) ___lambda25__clutter_animation_completed, self, 0);
	_g_object_unref0 (anim);
}


ClutterActor* journal_selectionbar_get_actor (JournalSelectionbar* self) {
	ClutterActor* result;
	GtkClutterActor* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->gtk_actor;
	result = (ClutterActor*) _tmp0_;
	return result;
}


static gboolean journal_selectionbar_get_visible (JournalSelectionbar* self) {
	gboolean result;
	gboolean _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_visible;
	result = _tmp0_;
	return result;
}


static void journal_selectionbar_set_visible (JournalSelectionbar* self, gboolean value) {
	gboolean _tmp0_;
	gboolean _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_visible = _tmp0_;
	_tmp1_ = value;
	if (_tmp1_) {
		journal_selectionbar_show (self);
	} else {
		journal_selectionbar_hide (self);
	}
}


static void journal_selectionbar_class_init (JournalSelectionbarClass * klass) {
	journal_selectionbar_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (JournalSelectionbarPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_journal_selectionbar_get_property;
	G_OBJECT_CLASS (klass)->set_property = _vala_journal_selectionbar_set_property;
	G_OBJECT_CLASS (klass)->finalize = journal_selectionbar_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_SELECTIONBAR_ACTOR, g_param_spec_object ("actor", "actor", "actor", clutter_actor_get_type (), G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void journal_selectionbar_instance_init (JournalSelectionbar * self) {
	self->priv = JOURNAL_SELECTIONBAR_GET_PRIVATE (self);
}


static void journal_selectionbar_finalize (GObject* obj) {
	JournalSelectionbar * self;
	self = JOURNAL_SELECTIONBAR (obj);
	_g_object_unref0 (self->priv->app);
	_g_object_unref0 (self->priv->gtk_actor);
	_g_object_unref0 (self->priv->toolbar);
	_g_object_unref0 (self->priv->favorite_btn);
	_g_object_unref0 (self->priv->remove_btn);
	G_OBJECT_CLASS (journal_selectionbar_parent_class)->finalize (obj);
}


GType journal_selectionbar_get_type (void) {
	static volatile gsize journal_selectionbar_type_id__volatile = 0;
	if (g_once_init_enter (&journal_selectionbar_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JournalSelectionbarClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) journal_selectionbar_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JournalSelectionbar), 0, (GInstanceInitFunc) journal_selectionbar_instance_init, NULL };
		GType journal_selectionbar_type_id;
		journal_selectionbar_type_id = g_type_register_static (G_TYPE_OBJECT, "JournalSelectionbar", &g_define_type_info, 0);
		g_once_init_leave (&journal_selectionbar_type_id__volatile, journal_selectionbar_type_id);
	}
	return journal_selectionbar_type_id__volatile;
}


static void _vala_journal_selectionbar_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	JournalSelectionbar * self;
	self = JOURNAL_SELECTIONBAR (object);
	switch (property_id) {
		case JOURNAL_SELECTIONBAR_ACTOR:
		g_value_set_object (value, journal_selectionbar_get_actor (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}


static void _vala_journal_selectionbar_set_property (GObject * object, guint property_id, const GValue * value, GParamSpec * pspec) {
	JournalSelectionbar * self;
	self = JOURNAL_SELECTIONBAR (object);
	switch (property_id) {
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



