/* zg-backend.c generated by valac 0.16.0, the Vala compiler
 * generated from zg-backend.vala, do not modify */

/*Taken from lp:synapse-project*/

#include <glib.h>
#include <glib-object.h>
#include <zeitgeist.h>
#include <gee.h>
#include <stdlib.h>
#include <string.h>
#include <gio/gio.h>


#define JOURNAL_TYPE_ZEITGEIST_BACKEND (journal_zeitgeist_backend_get_type ())
#define JOURNAL_ZEITGEIST_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackend))
#define JOURNAL_ZEITGEIST_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackendClass))
#define JOURNAL_IS_ZEITGEIST_BACKEND(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND))
#define JOURNAL_IS_ZEITGEIST_BACKEND_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), JOURNAL_TYPE_ZEITGEIST_BACKEND))
#define JOURNAL_ZEITGEIST_BACKEND_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackendClass))

typedef struct _JournalZeitgeistBackend JournalZeitgeistBackend;
typedef struct _JournalZeitgeistBackendClass JournalZeitgeistBackendClass;
typedef struct _JournalZeitgeistBackendPrivate JournalZeitgeistBackendPrivate;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_ptr_array_free0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_free (var, TRUE), NULL)))
typedef struct _JournalZeitgeistBackendLoadApplicationEventsData JournalZeitgeistBackendLoadApplicationEventsData;
typedef struct _JournalZeitgeistBackendLoadUriEventsData JournalZeitgeistBackendLoadUriEventsData;
#define _g_date_time_unref0(var) ((var == NULL) ? NULL : (var = (g_date_time_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _JournalZeitgeistBackendFillDaysMapData JournalZeitgeistBackendFillDaysMapData;

struct _JournalZeitgeistBackend {
	GObject parent_instance;
	JournalZeitgeistBackendPrivate * priv;
};

struct _JournalZeitgeistBackendClass {
	GObjectClass parent_class;
};

struct _JournalZeitgeistBackendPrivate {
	ZeitgeistLog* zg_log;
	GeeArrayList* all_events;
	GeeArrayList* all_app_events;
	GeeMap* days_map;
};

struct _JournalZeitgeistBackendLoadApplicationEventsData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	JournalZeitgeistBackend* self;
	gint64 start;
	gint64 end;
	gint64 _tmp0_;
	gint64 _tmp1_;
	ZeitgeistTimeRange* _tmp2_;
	ZeitgeistTimeRange* _tmp3_;
	ZeitgeistTimeRange* tr;
	ZeitgeistEvent* _tmp4_;
	ZeitgeistEvent* _tmp5_;
	ZeitgeistEvent* event;
	ZeitgeistEvent* _tmp6_;
	ZeitgeistSubject* _tmp7_;
	ZeitgeistSubject* _tmp8_;
	ZeitgeistSubject* subject;
	ZeitgeistSubject* _tmp9_;
	ZeitgeistSubject* _tmp10_;
	ZeitgeistEvent* _tmp11_;
	ZeitgeistSubject* _tmp12_;
	GPtrArray* _tmp13_;
	GPtrArray* ptr_arr;
	GPtrArray* _tmp14_;
	ZeitgeistEvent* _tmp15_;
	ZeitgeistResultSet* rs;
	ZeitgeistLog* _tmp16_;
	ZeitgeistTimeRange* _tmp17_;
	GPtrArray* _tmp18_;
	ZeitgeistResultSet* _tmp19_;
	ZeitgeistResultSet* _tmp20_;
	ZeitgeistResultSet* _tmp21_;
	ZeitgeistResultSet* _tmp22_;
	ZeitgeistResultSet* _e_it;
	ZeitgeistEvent* e;
	ZeitgeistResultSet* _tmp23_;
	ZeitgeistEvent* _tmp24_;
	ZeitgeistEvent* _tmp25_;
	ZeitgeistEvent* _tmp26_;
	ZeitgeistEvent* _tmp27_;
	gint _tmp28_;
	GeeArrayList* _tmp29_;
	ZeitgeistEvent* _tmp30_;
	GError* err;
	GError* _tmp31_;
	const gchar* _tmp32_;
	GError * _inner_error_;
};

struct _JournalZeitgeistBackendLoadUriEventsData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	JournalZeitgeistBackend* self;
	gint64 start;
	gint64 end;
	gint64 _tmp0_;
	gint64 _tmp1_;
	ZeitgeistTimeRange* _tmp2_;
	ZeitgeistTimeRange* _tmp3_;
	ZeitgeistTimeRange* tr;
	ZeitgeistEvent* _tmp4_;
	ZeitgeistEvent* _tmp5_;
	ZeitgeistEvent* event;
	ZeitgeistEvent* _tmp6_;
	ZeitgeistSubject* _tmp7_;
	ZeitgeistSubject* _tmp8_;
	ZeitgeistSubject* subject;
	ZeitgeistSubject* _tmp9_;
	ZeitgeistSubject* _tmp10_;
	ZeitgeistEvent* _tmp11_;
	ZeitgeistSubject* _tmp12_;
	GPtrArray* _tmp13_;
	GPtrArray* ptr_arr;
	GPtrArray* _tmp14_;
	ZeitgeistEvent* _tmp15_;
	ZeitgeistResultSet* rs;
	ZeitgeistLog* _tmp16_;
	ZeitgeistTimeRange* _tmp17_;
	GPtrArray* _tmp18_;
	ZeitgeistResultSet* _tmp19_;
	ZeitgeistResultSet* _tmp20_;
	ZeitgeistResultSet* _tmp21_;
	ZeitgeistResultSet* _tmp22_;
	ZeitgeistResultSet* _e1_it;
	ZeitgeistEvent* e1;
	ZeitgeistResultSet* _tmp23_;
	ZeitgeistEvent* _tmp24_;
	ZeitgeistEvent* _tmp25_;
	ZeitgeistEvent* _tmp26_;
	ZeitgeistEvent* _tmp27_;
	gint _tmp28_;
	GeeArrayList* _tmp29_;
	ZeitgeistEvent* _tmp30_;
	ZeitgeistSubject* _tmp31_;
	ZeitgeistSubject* _tmp32_;
	GPtrArray* _tmp33_;
	GPtrArray* _tmp34_;
	ZeitgeistEvent* _tmp35_;
	ZeitgeistLog* _tmp36_;
	ZeitgeistTimeRange* _tmp37_;
	GPtrArray* _tmp38_;
	ZeitgeistResultSet* _tmp39_;
	ZeitgeistResultSet* _tmp40_;
	ZeitgeistResultSet* _tmp41_;
	ZeitgeistResultSet* _tmp42_;
	ZeitgeistResultSet* _e2_it;
	ZeitgeistEvent* e2;
	ZeitgeistResultSet* _tmp43_;
	ZeitgeistEvent* _tmp44_;
	ZeitgeistEvent* _tmp45_;
	ZeitgeistEvent* _tmp46_;
	ZeitgeistEvent* _tmp47_;
	gint _tmp48_;
	GeeArrayList* _tmp49_;
	ZeitgeistEvent* _tmp50_;
	GError* err;
	GError* _tmp51_;
	const gchar* _tmp52_;
	GError * _inner_error_;
};

struct _JournalZeitgeistBackendFillDaysMapData {
	int _state_;
	GObject* _source_object_;
	GAsyncResult* _res_;
	GSimpleAsyncResult* _async_result;
	JournalZeitgeistBackend* self;
	GeeArrayList* _tmp0_;
	GeeArrayList* _tmp1_;
	GeeArrayList* _e1_list;
	GeeArrayList* _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	gint _e1_size;
	gint _e1_index;
	gint _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	GeeArrayList* _tmp8_;
	gint _tmp9_;
	gpointer _tmp10_;
	ZeitgeistEvent* e1;
	ZeitgeistEvent* _tmp11_;
	gint _tmp12_;
	ZeitgeistEvent* _tmp13_;
	gint64 _tmp14_;
	gint64 timestamp;
	gint64 _tmp15_;
	GDateTime* _tmp16_;
	GDateTime* _tmp17_;
	GDateTime* _tmp18_;
	GDateTime* _tmp19_;
	GDateTime* date;
	GDateTime* _tmp20_;
	gchar* _tmp21_;
	gchar* key;
	GeeMap* _tmp22_;
	const gchar* _tmp23_;
	gboolean _tmp24_;
	GeeMap* _tmp25_;
	const gchar* _tmp26_;
	GeeArrayList* _tmp27_;
	GeeArrayList* _tmp28_;
	GeeMap* _tmp29_;
	const gchar* _tmp30_;
	gpointer _tmp31_;
	GeeArrayList* _tmp32_;
	ZeitgeistEvent* _tmp33_;
};


static gpointer journal_zeitgeist_backend_parent_class = NULL;

GType journal_zeitgeist_backend_get_type (void) G_GNUC_CONST;
#define JOURNAL_ZEITGEIST_BACKEND_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), JOURNAL_TYPE_ZEITGEIST_BACKEND, JournalZeitgeistBackendPrivate))
enum  {
	JOURNAL_ZEITGEIST_BACKEND_DUMMY_PROPERTY,
	JOURNAL_ZEITGEIST_BACKEND_ALL_ACTIVITIES
};
static gboolean journal_zeitgeist_backend_load_events (JournalZeitgeistBackend* self);
static void journal_zeitgeist_backend_load_uri_events (JournalZeitgeistBackend* self, gint64 start, gint64 end, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void journal_zeitgeist_backend_load_uri_events_finish (JournalZeitgeistBackend* self, GAsyncResult* _res_);
static void journal_zeitgeist_backend_load_application_events (JournalZeitgeistBackend* self, gint64 start, gint64 end, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void journal_zeitgeist_backend_load_application_events_finish (JournalZeitgeistBackend* self, GAsyncResult* _res_);
static void journal_zeitgeist_backend_load_application_events_data_free (gpointer _data);
static gboolean journal_zeitgeist_backend_load_application_events_co (JournalZeitgeistBackendLoadApplicationEventsData* _data_);
static gboolean _journal_zeitgeist_backend_load_application_events_co_gsource_func (gpointer self);
static void journal_zeitgeist_backend_load_application_events_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void journal_zeitgeist_backend_load_uri_events_data_free (gpointer _data);
static gboolean journal_zeitgeist_backend_load_uri_events_co (JournalZeitgeistBackendLoadUriEventsData* _data_);
static gboolean _journal_zeitgeist_backend_load_uri_events_co_gsource_func (gpointer self);
static void journal_zeitgeist_backend_load_uri_events_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_);
static void journal_zeitgeist_backend_fill_days_map (JournalZeitgeistBackend* self, GAsyncReadyCallback _callback_, gpointer _user_data_);
static void journal_zeitgeist_backend_fill_days_map_finish (JournalZeitgeistBackend* self, GAsyncResult* _res_);
static void journal_zeitgeist_backend_fill_days_map_data_free (gpointer _data);
static gboolean journal_zeitgeist_backend_fill_days_map_co (JournalZeitgeistBackendFillDaysMapData* _data_);
static gboolean _journal_zeitgeist_backend_fill_days_map_co_gsource_func (gpointer self);
GeeArrayList* journal_zeitgeist_backend_get_events_for_day (JournalZeitgeistBackend* self, const gchar* ymd);
JournalZeitgeistBackend* journal_zeitgeist_backend_new (void);
JournalZeitgeistBackend* journal_zeitgeist_backend_construct (GType object_type);
GeeArrayList* journal_zeitgeist_backend_get_all_activities (JournalZeitgeistBackend* self);
static GObject * journal_zeitgeist_backend_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties);
static void journal_zeitgeist_backend_finalize (GObject* obj);
static void _vala_journal_zeitgeist_backend_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);


static gboolean journal_zeitgeist_backend_load_events (JournalZeitgeistBackend* self) {
	gboolean result = FALSE;
	gint64 _tmp0_ = 0LL;
	gint64 end;
	gint64 _tmp1_;
	gint64 start;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = zeitgeist_timestamp_for_now ();
	end = _tmp0_;
	_tmp1_ = ZEITGEIST_TIMESTAMP_DAY;
	start = end - (_tmp1_ * 6);
	journal_zeitgeist_backend_load_uri_events (self, start, end, NULL, NULL);
	journal_zeitgeist_backend_load_application_events (self, start, end, NULL, NULL);
	result = TRUE;
	return result;
}


static void journal_zeitgeist_backend_load_application_events_data_free (gpointer _data) {
	JournalZeitgeistBackendLoadApplicationEventsData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (JournalZeitgeistBackendLoadApplicationEventsData, _data_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void journal_zeitgeist_backend_load_application_events (JournalZeitgeistBackend* self, gint64 start, gint64 end, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	JournalZeitgeistBackendLoadApplicationEventsData* _data_;
	JournalZeitgeistBackend* _tmp0_;
	gint64 _tmp1_;
	gint64 _tmp2_;
	_data_ = g_slice_new0 (JournalZeitgeistBackendLoadApplicationEventsData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, journal_zeitgeist_backend_load_application_events);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, journal_zeitgeist_backend_load_application_events_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = start;
	_data_->start = _tmp1_;
	_tmp2_ = end;
	_data_->end = _tmp2_;
	journal_zeitgeist_backend_load_application_events_co (_data_);
}


static void journal_zeitgeist_backend_load_application_events_finish (JournalZeitgeistBackend* self, GAsyncResult* _res_) {
	JournalZeitgeistBackendLoadApplicationEventsData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gboolean _journal_zeitgeist_backend_load_application_events_co_gsource_func (gpointer self) {
	gboolean result;
	result = journal_zeitgeist_backend_load_application_events_co (self);
	return result;
}


static void journal_zeitgeist_backend_load_application_events_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	JournalZeitgeistBackendLoadApplicationEventsData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	journal_zeitgeist_backend_load_application_events_co (_data_);
}


static gboolean journal_zeitgeist_backend_load_application_events_co (JournalZeitgeistBackendLoadApplicationEventsData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		case 2:
		goto _state_2;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	g_idle_add_full (G_PRIORITY_LOW, _journal_zeitgeist_backend_load_application_events_co_gsource_func, _data_, NULL);
	_data_->_state_ = 1;
	return FALSE;
	_state_1:
	;
	_data_->_tmp0_ = _data_->start;
	_data_->_tmp1_ = _data_->end;
	_data_->_tmp2_ = zeitgeist_time_range_new (_data_->_tmp0_, _data_->_tmp1_);
	_data_->_tmp3_ = g_object_ref_sink (_data_->_tmp2_);
	_data_->tr = _data_->_tmp3_;
	_data_->_tmp4_ = zeitgeist_event_new ();
	_data_->_tmp5_ = g_object_ref_sink (_data_->_tmp4_);
	_data_->event = _data_->_tmp5_;
	_data_->_tmp6_ = _data_->event;
	zeitgeist_event_set_interpretation (_data_->_tmp6_, "!" ZEITGEIST_ZG_LEAVE_EVENT);
	_data_->_tmp7_ = zeitgeist_subject_new ();
	_data_->_tmp8_ = g_object_ref_sink (_data_->_tmp7_);
	_data_->subject = _data_->_tmp8_;
	_data_->_tmp9_ = _data_->subject;
	zeitgeist_subject_set_interpretation (_data_->_tmp9_, ZEITGEIST_NFO_SOFTWARE);
	_data_->_tmp10_ = _data_->subject;
	zeitgeist_subject_set_uri (_data_->_tmp10_, "application://*");
	_data_->_tmp11_ = _data_->event;
	_data_->_tmp12_ = _data_->subject;
	zeitgeist_event_add_subject (_data_->_tmp11_, _data_->_tmp12_);
	_data_->_tmp13_ = g_ptr_array_new ();
	_data_->ptr_arr = _data_->_tmp13_;
	_data_->_tmp14_ = _data_->ptr_arr;
	_data_->_tmp15_ = _data_->event;
	g_ptr_array_add (_data_->_tmp14_, _data_->_tmp15_);
	{
		_data_->_tmp16_ = _data_->self->priv->zg_log;
		_data_->_tmp17_ = _data_->tr;
		_data_->_tmp18_ = _data_->ptr_arr;
		_data_->ptr_arr = NULL;
		_data_->_state_ = 2;
		zeitgeist_log_find_events (_data_->_tmp16_, _data_->_tmp17_, _data_->_tmp18_, ZEITGEIST_STORAGE_STATE_ANY, (guint32) 256, ZEITGEIST_RESULT_TYPE_MOST_POPULAR_SUBJECTS, NULL, journal_zeitgeist_backend_load_application_events_ready, _data_);
		return FALSE;
		_state_2:
		_data_->_tmp19_ = NULL;
		_data_->_tmp19_ = zeitgeist_log_find_events_finish (_data_->_tmp16_, _data_->_res_, &_data_->_inner_error_);
		_data_->_tmp20_ = _data_->_tmp19_;
		if (_data_->_inner_error_ != NULL) {
			goto __catch7_g_error;
		}
		_g_object_unref0 (_data_->rs);
		_data_->rs = _data_->_tmp20_;
		{
			_data_->_tmp21_ = _data_->rs;
			_data_->_tmp22_ = NULL;
			_data_->_tmp22_ = _vala_zeitgeist_result_set_iterator (_data_->_tmp21_);
			_data_->_e_it = _data_->_tmp22_;
			while (TRUE) {
				_data_->_tmp23_ = _data_->_e_it;
				_data_->_tmp24_ = NULL;
				_data_->_tmp24_ = _vala_zeitgeist_result_set_next_value (_data_->_tmp23_);
				_data_->_tmp25_ = _g_object_ref0 (_data_->_tmp24_);
				_g_object_unref0 (_data_->e);
				_data_->e = _data_->_tmp25_;
				_data_->_tmp26_ = _data_->e;
				if (!(_data_->_tmp26_ != NULL)) {
					break;
				}
				_data_->_tmp27_ = _data_->e;
				_data_->_tmp28_ = 0;
				_data_->_tmp28_ = zeitgeist_event_num_subjects (_data_->_tmp27_);
				if (_data_->_tmp28_ <= 0) {
					continue;
				}
				_data_->_tmp29_ = _data_->self->priv->all_app_events;
				_data_->_tmp30_ = _data_->e;
				gee_abstract_collection_add ((GeeAbstractCollection*) _data_->_tmp29_, _data_->_tmp30_);
			}
			_g_object_unref0 (_data_->e);
			_g_object_unref0 (_data_->_e_it);
		}
	}
	goto __finally7;
	__catch7_g_error:
	{
		_data_->err = _data_->_inner_error_;
		_data_->_inner_error_ = NULL;
		_data_->_tmp31_ = _data_->err;
		_data_->_tmp32_ = _data_->_tmp31_->message;
		g_warning ("zg-backend.vala:72: %s", _data_->_tmp32_);
		_g_error_free0 (_data_->err);
		_g_object_unref0 (_data_->rs);
		_g_ptr_array_free0 (_data_->ptr_arr);
		_g_object_unref0 (_data_->subject);
		_g_object_unref0 (_data_->event);
		_g_object_unref0 (_data_->tr);
		if (_data_->_state_ == 0) {
			g_simple_async_result_complete_in_idle (_data_->_async_result);
		} else {
			g_simple_async_result_complete (_data_->_async_result);
		}
		g_object_unref (_data_->_async_result);
		return FALSE;
	}
	__finally7:
	if (_data_->_inner_error_ != NULL) {
		_g_object_unref0 (_data_->rs);
		_g_ptr_array_free0 (_data_->ptr_arr);
		_g_object_unref0 (_data_->subject);
		_g_object_unref0 (_data_->event);
		_g_object_unref0 (_data_->tr);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
		g_clear_error (&_data_->_inner_error_);
		return FALSE;
	}
	_g_object_unref0 (_data_->rs);
	_g_ptr_array_free0 (_data_->ptr_arr);
	_g_object_unref0 (_data_->subject);
	_g_object_unref0 (_data_->event);
	_g_object_unref0 (_data_->tr);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void journal_zeitgeist_backend_load_uri_events_data_free (gpointer _data) {
	JournalZeitgeistBackendLoadUriEventsData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (JournalZeitgeistBackendLoadUriEventsData, _data_);
}


static void journal_zeitgeist_backend_load_uri_events (JournalZeitgeistBackend* self, gint64 start, gint64 end, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	JournalZeitgeistBackendLoadUriEventsData* _data_;
	JournalZeitgeistBackend* _tmp0_;
	gint64 _tmp1_;
	gint64 _tmp2_;
	_data_ = g_slice_new0 (JournalZeitgeistBackendLoadUriEventsData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, journal_zeitgeist_backend_load_uri_events);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, journal_zeitgeist_backend_load_uri_events_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	_tmp1_ = start;
	_data_->start = _tmp1_;
	_tmp2_ = end;
	_data_->end = _tmp2_;
	journal_zeitgeist_backend_load_uri_events_co (_data_);
}


static void journal_zeitgeist_backend_load_uri_events_finish (JournalZeitgeistBackend* self, GAsyncResult* _res_) {
	JournalZeitgeistBackendLoadUriEventsData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gboolean _journal_zeitgeist_backend_load_uri_events_co_gsource_func (gpointer self) {
	gboolean result;
	result = journal_zeitgeist_backend_load_uri_events_co (self);
	return result;
}


static void journal_zeitgeist_backend_load_uri_events_ready (GObject* source_object, GAsyncResult* _res_, gpointer _user_data_) {
	JournalZeitgeistBackendLoadUriEventsData* _data_;
	_data_ = _user_data_;
	_data_->_source_object_ = source_object;
	_data_->_res_ = _res_;
	journal_zeitgeist_backend_load_uri_events_co (_data_);
}


static gboolean journal_zeitgeist_backend_load_uri_events_co (JournalZeitgeistBackendLoadUriEventsData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		case 2:
		goto _state_2;
		case 3:
		goto _state_3;
		case 4:
		goto _state_4;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _journal_zeitgeist_backend_load_uri_events_co_gsource_func, _data_, NULL);
	_data_->_state_ = 1;
	return FALSE;
	_state_1:
	;
	_data_->_tmp0_ = _data_->start;
	_data_->_tmp1_ = _data_->end;
	_data_->_tmp2_ = zeitgeist_time_range_new (_data_->_tmp0_, _data_->_tmp1_);
	_data_->_tmp3_ = g_object_ref_sink (_data_->_tmp2_);
	_data_->tr = _data_->_tmp3_;
	_data_->_tmp4_ = zeitgeist_event_new ();
	_data_->_tmp5_ = g_object_ref_sink (_data_->_tmp4_);
	_data_->event = _data_->_tmp5_;
	_data_->_tmp6_ = _data_->event;
	zeitgeist_event_set_interpretation (_data_->_tmp6_, "!" ZEITGEIST_ZG_LEAVE_EVENT);
	_data_->_tmp7_ = zeitgeist_subject_new ();
	_data_->_tmp8_ = g_object_ref_sink (_data_->_tmp7_);
	_data_->subject = _data_->_tmp8_;
	_data_->_tmp9_ = _data_->subject;
	zeitgeist_subject_set_interpretation (_data_->_tmp9_, "!" ZEITGEIST_NFO_SOFTWARE);
	_data_->_tmp10_ = _data_->subject;
	zeitgeist_subject_set_uri (_data_->_tmp10_, "file://*");
	_data_->_tmp11_ = _data_->event;
	_data_->_tmp12_ = _data_->subject;
	zeitgeist_event_add_subject (_data_->_tmp11_, _data_->_tmp12_);
	_data_->_tmp13_ = g_ptr_array_new ();
	_data_->ptr_arr = _data_->_tmp13_;
	_data_->_tmp14_ = _data_->ptr_arr;
	_data_->_tmp15_ = _data_->event;
	g_ptr_array_add (_data_->_tmp14_, _data_->_tmp15_);
	{
		_data_->_tmp16_ = _data_->self->priv->zg_log;
		_data_->_tmp17_ = _data_->tr;
		_data_->_tmp18_ = _data_->ptr_arr;
		_data_->ptr_arr = NULL;
		_data_->_state_ = 2;
		zeitgeist_log_find_events (_data_->_tmp16_, _data_->_tmp17_, _data_->_tmp18_, ZEITGEIST_STORAGE_STATE_ANY, (guint32) 256, ZEITGEIST_RESULT_TYPE_MOST_POPULAR_SUBJECTS, NULL, journal_zeitgeist_backend_load_uri_events_ready, _data_);
		return FALSE;
		_state_2:
		_data_->_tmp19_ = NULL;
		_data_->_tmp19_ = zeitgeist_log_find_events_finish (_data_->_tmp16_, _data_->_res_, &_data_->_inner_error_);
		_data_->_tmp20_ = _data_->_tmp19_;
		if (_data_->_inner_error_ != NULL) {
			goto __catch8_g_error;
		}
		_g_object_unref0 (_data_->rs);
		_data_->rs = _data_->_tmp20_;
		{
			_data_->_tmp21_ = _data_->rs;
			_data_->_tmp22_ = NULL;
			_data_->_tmp22_ = _vala_zeitgeist_result_set_iterator (_data_->_tmp21_);
			_data_->_e1_it = _data_->_tmp22_;
			while (TRUE) {
				_data_->_tmp23_ = _data_->_e1_it;
				_data_->_tmp24_ = NULL;
				_data_->_tmp24_ = _vala_zeitgeist_result_set_next_value (_data_->_tmp23_);
				_data_->_tmp25_ = _g_object_ref0 (_data_->_tmp24_);
				_g_object_unref0 (_data_->e1);
				_data_->e1 = _data_->_tmp25_;
				_data_->_tmp26_ = _data_->e1;
				if (!(_data_->_tmp26_ != NULL)) {
					break;
				}
				_data_->_tmp27_ = _data_->e1;
				_data_->_tmp28_ = 0;
				_data_->_tmp28_ = zeitgeist_event_num_subjects (_data_->_tmp27_);
				if (_data_->_tmp28_ <= 0) {
					continue;
				}
				_data_->_tmp29_ = _data_->self->priv->all_events;
				_data_->_tmp30_ = _data_->e1;
				gee_abstract_collection_add ((GeeAbstractCollection*) _data_->_tmp29_, _data_->_tmp30_);
			}
			_g_object_unref0 (_data_->e1);
			_g_object_unref0 (_data_->_e1_it);
		}
		_data_->_tmp31_ = _data_->subject;
		zeitgeist_subject_set_interpretation (_data_->_tmp31_, ZEITGEIST_NFO_WEBSITE);
		_data_->_tmp32_ = _data_->subject;
		zeitgeist_subject_set_uri (_data_->_tmp32_, "");
		_data_->_tmp33_ = g_ptr_array_new ();
		_g_ptr_array_free0 (_data_->ptr_arr);
		_data_->ptr_arr = _data_->_tmp33_;
		_data_->_tmp34_ = _data_->ptr_arr;
		_data_->_tmp35_ = _data_->event;
		g_ptr_array_add (_data_->_tmp34_, _data_->_tmp35_);
		_data_->_tmp36_ = _data_->self->priv->zg_log;
		_data_->_tmp37_ = _data_->tr;
		_data_->_tmp38_ = _data_->ptr_arr;
		_data_->ptr_arr = NULL;
		_data_->_state_ = 3;
		zeitgeist_log_find_events (_data_->_tmp36_, _data_->_tmp37_, _data_->_tmp38_, ZEITGEIST_STORAGE_STATE_ANY, (guint32) 128, ZEITGEIST_RESULT_TYPE_MOST_POPULAR_SUBJECTS, NULL, journal_zeitgeist_backend_load_uri_events_ready, _data_);
		return FALSE;
		_state_3:
		_data_->_tmp39_ = NULL;
		_data_->_tmp39_ = zeitgeist_log_find_events_finish (_data_->_tmp36_, _data_->_res_, &_data_->_inner_error_);
		_data_->_tmp40_ = _data_->_tmp39_;
		if (_data_->_inner_error_ != NULL) {
			goto __catch8_g_error;
		}
		_g_object_unref0 (_data_->rs);
		_data_->rs = _data_->_tmp40_;
		{
			_data_->_tmp41_ = _data_->rs;
			_data_->_tmp42_ = NULL;
			_data_->_tmp42_ = _vala_zeitgeist_result_set_iterator (_data_->_tmp41_);
			_data_->_e2_it = _data_->_tmp42_;
			while (TRUE) {
				_data_->_tmp43_ = _data_->_e2_it;
				_data_->_tmp44_ = NULL;
				_data_->_tmp44_ = _vala_zeitgeist_result_set_next_value (_data_->_tmp43_);
				_data_->_tmp45_ = _g_object_ref0 (_data_->_tmp44_);
				_g_object_unref0 (_data_->e2);
				_data_->e2 = _data_->_tmp45_;
				_data_->_tmp46_ = _data_->e2;
				if (!(_data_->_tmp46_ != NULL)) {
					break;
				}
				_data_->_tmp47_ = _data_->e2;
				_data_->_tmp48_ = 0;
				_data_->_tmp48_ = zeitgeist_event_num_subjects (_data_->_tmp47_);
				if (_data_->_tmp48_ <= 0) {
					continue;
				}
				_data_->_tmp49_ = _data_->self->priv->all_events;
				_data_->_tmp50_ = _data_->e2;
				gee_abstract_collection_add ((GeeAbstractCollection*) _data_->_tmp49_, _data_->_tmp50_);
			}
			_g_object_unref0 (_data_->e2);
			_g_object_unref0 (_data_->_e2_it);
		}
	}
	goto __finally8;
	__catch8_g_error:
	{
		_data_->err = _data_->_inner_error_;
		_data_->_inner_error_ = NULL;
		_data_->_tmp51_ = _data_->err;
		_data_->_tmp52_ = _data_->_tmp51_->message;
		g_warning ("zg-backend.vala:131: %s", _data_->_tmp52_);
		_g_error_free0 (_data_->err);
	}
	__finally8:
	if (_data_->_inner_error_ != NULL) {
		_g_object_unref0 (_data_->rs);
		_g_ptr_array_free0 (_data_->ptr_arr);
		_g_object_unref0 (_data_->subject);
		_g_object_unref0 (_data_->event);
		_g_object_unref0 (_data_->tr);
		g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _data_->_inner_error_->message, g_quark_to_string (_data_->_inner_error_->domain), _data_->_inner_error_->code);
		g_clear_error (&_data_->_inner_error_);
		return FALSE;
	}
	_data_->_state_ = 4;
	journal_zeitgeist_backend_fill_days_map (_data_->self, journal_zeitgeist_backend_load_uri_events_ready, _data_);
	return FALSE;
	_state_4:
	journal_zeitgeist_backend_fill_days_map_finish (_data_->self, _data_->_res_);
	_g_object_unref0 (_data_->rs);
	_g_ptr_array_free0 (_data_->ptr_arr);
	_g_object_unref0 (_data_->subject);
	_g_object_unref0 (_data_->event);
	_g_object_unref0 (_data_->tr);
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


static void journal_zeitgeist_backend_fill_days_map_data_free (gpointer _data) {
	JournalZeitgeistBackendFillDaysMapData* _data_;
	_data_ = _data;
	_g_object_unref0 (_data_->self);
	g_slice_free (JournalZeitgeistBackendFillDaysMapData, _data_);
}


static void journal_zeitgeist_backend_fill_days_map (JournalZeitgeistBackend* self, GAsyncReadyCallback _callback_, gpointer _user_data_) {
	JournalZeitgeistBackendFillDaysMapData* _data_;
	JournalZeitgeistBackend* _tmp0_;
	_data_ = g_slice_new0 (JournalZeitgeistBackendFillDaysMapData);
	_data_->_async_result = g_simple_async_result_new (G_OBJECT (self), _callback_, _user_data_, journal_zeitgeist_backend_fill_days_map);
	g_simple_async_result_set_op_res_gpointer (_data_->_async_result, _data_, journal_zeitgeist_backend_fill_days_map_data_free);
	_tmp0_ = _g_object_ref0 (self);
	_data_->self = _tmp0_;
	journal_zeitgeist_backend_fill_days_map_co (_data_);
}


static void journal_zeitgeist_backend_fill_days_map_finish (JournalZeitgeistBackend* self, GAsyncResult* _res_) {
	JournalZeitgeistBackendFillDaysMapData* _data_;
	_data_ = g_simple_async_result_get_op_res_gpointer (G_SIMPLE_ASYNC_RESULT (_res_));
}


static gboolean _journal_zeitgeist_backend_fill_days_map_co_gsource_func (gpointer self) {
	gboolean result;
	result = journal_zeitgeist_backend_fill_days_map_co (self);
	return result;
}


static gboolean journal_zeitgeist_backend_fill_days_map_co (JournalZeitgeistBackendFillDaysMapData* _data_) {
	switch (_data_->_state_) {
		case 0:
		goto _state_0;
		case 1:
		goto _state_1;
		default:
		g_assert_not_reached ();
	}
	_state_0:
	g_idle_add_full (G_PRIORITY_DEFAULT_IDLE, _journal_zeitgeist_backend_fill_days_map_co_gsource_func, _data_, NULL);
	_data_->_state_ = 1;
	return FALSE;
	_state_1:
	;
	{
		_data_->_tmp0_ = _data_->self->priv->all_events;
		_data_->_tmp1_ = _g_object_ref0 (_data_->_tmp0_);
		_data_->_e1_list = _data_->_tmp1_;
		_data_->_tmp2_ = _data_->_e1_list;
		_data_->_tmp3_ = gee_abstract_collection_get_size ((GeeCollection*) _data_->_tmp2_);
		_data_->_tmp4_ = _data_->_tmp3_;
		_data_->_e1_size = _data_->_tmp4_;
		_data_->_e1_index = -1;
		while (TRUE) {
			_data_->_tmp5_ = _data_->_e1_index;
			_data_->_e1_index = _data_->_tmp5_ + 1;
			_data_->_tmp6_ = _data_->_e1_index;
			_data_->_tmp7_ = _data_->_e1_size;
			if (!(_data_->_tmp6_ < _data_->_tmp7_)) {
				break;
			}
			_data_->_tmp8_ = _data_->_e1_list;
			_data_->_tmp9_ = _data_->_e1_index;
			_data_->_tmp10_ = NULL;
			_data_->_tmp10_ = gee_abstract_list_get ((GeeAbstractList*) _data_->_tmp8_, _data_->_tmp9_);
			_data_->e1 = (ZeitgeistEvent*) _data_->_tmp10_;
			_data_->_tmp11_ = _data_->e1;
			_data_->_tmp12_ = 0;
			_data_->_tmp12_ = zeitgeist_event_num_subjects (_data_->_tmp11_);
			if (_data_->_tmp12_ <= 0) {
				_g_object_unref0 (_data_->e1);
				continue;
			}
			_data_->_tmp13_ = _data_->e1;
			_data_->_tmp14_ = 0LL;
			_data_->_tmp14_ = zeitgeist_event_get_timestamp (_data_->_tmp13_);
			_data_->timestamp = _data_->_tmp14_ / 1000;
			_data_->_tmp15_ = _data_->timestamp;
			_data_->_tmp16_ = g_date_time_new_from_unix_utc (_data_->_tmp15_);
			_data_->_tmp17_ = _data_->_tmp16_;
			_data_->_tmp18_ = NULL;
			_data_->_tmp18_ = g_date_time_to_local (_data_->_tmp17_);
			_data_->_tmp19_ = _data_->_tmp18_;
			_g_date_time_unref0 (_data_->_tmp17_);
			_data_->date = _data_->_tmp19_;
			_data_->_tmp20_ = _data_->date;
			_data_->_tmp21_ = NULL;
			_data_->_tmp21_ = g_date_time_format (_data_->_tmp20_, "%Y-%m-%d");
			_data_->key = _data_->_tmp21_;
			_data_->_tmp22_ = _data_->self->priv->days_map;
			_data_->_tmp23_ = _data_->key;
			_data_->_tmp24_ = FALSE;
			_data_->_tmp24_ = gee_map_has_key (_data_->_tmp22_, _data_->_tmp23_);
			if (!_data_->_tmp24_) {
				_data_->_tmp25_ = _data_->self->priv->days_map;
				_data_->_tmp26_ = _data_->key;
				_data_->_tmp27_ = gee_array_list_new (ZEITGEIST_TYPE_EVENT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
				_data_->_tmp28_ = _data_->_tmp27_;
				gee_map_set (_data_->_tmp25_, _data_->_tmp26_, _data_->_tmp28_);
				_g_object_unref0 (_data_->_tmp28_);
			}
			_data_->_tmp29_ = _data_->self->priv->days_map;
			_data_->_tmp30_ = _data_->key;
			_data_->_tmp31_ = NULL;
			_data_->_tmp31_ = gee_map_get (_data_->_tmp29_, _data_->_tmp30_);
			_data_->_tmp32_ = (GeeArrayList*) _data_->_tmp31_;
			_data_->_tmp33_ = _data_->e1;
			gee_abstract_collection_add ((GeeAbstractCollection*) _data_->_tmp32_, _data_->_tmp33_);
			_g_object_unref0 (_data_->_tmp32_);
			_g_free0 (_data_->key);
			_g_date_time_unref0 (_data_->date);
			_g_object_unref0 (_data_->e1);
		}
		_g_object_unref0 (_data_->_e1_list);
	}
	g_signal_emit_by_name (_data_->self, "events-loaded");
	if (_data_->_state_ == 0) {
		g_simple_async_result_complete_in_idle (_data_->_async_result);
	} else {
		g_simple_async_result_complete (_data_->_async_result);
	}
	g_object_unref (_data_->_async_result);
	return FALSE;
}


GeeArrayList* journal_zeitgeist_backend_get_events_for_day (JournalZeitgeistBackend* self, const gchar* ymd) {
	GeeArrayList* result = NULL;
	GeeMap* _tmp0_;
	const gchar* _tmp1_;
	gboolean _tmp2_ = FALSE;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (ymd != NULL, NULL);
	_tmp0_ = self->priv->days_map;
	_tmp1_ = ymd;
	_tmp2_ = gee_map_has_key (_tmp0_, _tmp1_);
	if (_tmp2_) {
		GeeMap* _tmp3_;
		const gchar* _tmp4_;
		gpointer _tmp5_ = NULL;
		_tmp3_ = self->priv->days_map;
		_tmp4_ = ymd;
		_tmp5_ = gee_map_get (_tmp3_, _tmp4_);
		result = (GeeArrayList*) _tmp5_;
		return result;
	}
	result = NULL;
	return result;
}


JournalZeitgeistBackend* journal_zeitgeist_backend_construct (GType object_type) {
	JournalZeitgeistBackend * self = NULL;
	self = (JournalZeitgeistBackend*) g_object_new (object_type, NULL);
	return self;
}


JournalZeitgeistBackend* journal_zeitgeist_backend_new (void) {
	return journal_zeitgeist_backend_construct (JOURNAL_TYPE_ZEITGEIST_BACKEND);
}


GeeArrayList* journal_zeitgeist_backend_get_all_activities (JournalZeitgeistBackend* self) {
	GeeArrayList* result;
	GeeArrayList* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->all_events;
	result = _tmp0_;
	return result;
}


static GObject * journal_zeitgeist_backend_constructor (GType type, guint n_construct_properties, GObjectConstructParam * construct_properties) {
	GObject * obj;
	GObjectClass * parent_class;
	JournalZeitgeistBackend * self;
	ZeitgeistLog* _tmp0_;
	GeeArrayList* _tmp1_;
	GeeArrayList* _tmp2_;
	GeeHashMap* _tmp3_;
	parent_class = G_OBJECT_CLASS (journal_zeitgeist_backend_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = JOURNAL_ZEITGEIST_BACKEND (obj);
	_tmp0_ = zeitgeist_log_new ();
	_g_object_unref0 (self->priv->zg_log);
	self->priv->zg_log = _tmp0_;
	_tmp1_ = gee_array_list_new (ZEITGEIST_TYPE_EVENT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->all_events);
	self->priv->all_events = _tmp1_;
	_tmp2_ = gee_array_list_new (ZEITGEIST_TYPE_EVENT, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->all_app_events);
	self->priv->all_app_events = _tmp2_;
	_tmp3_ = gee_hash_map_new (G_TYPE_STRING, (GBoxedCopyFunc) g_strdup, g_free, GEE_TYPE_ARRAY_LIST, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
	_g_object_unref0 (self->priv->days_map);
	self->priv->days_map = (GeeMap*) _tmp3_;
	journal_zeitgeist_backend_load_events (self);
	return obj;
}


static void journal_zeitgeist_backend_class_init (JournalZeitgeistBackendClass * klass) {
	journal_zeitgeist_backend_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (JournalZeitgeistBackendPrivate));
	G_OBJECT_CLASS (klass)->get_property = _vala_journal_zeitgeist_backend_get_property;
	G_OBJECT_CLASS (klass)->constructor = journal_zeitgeist_backend_constructor;
	G_OBJECT_CLASS (klass)->finalize = journal_zeitgeist_backend_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), JOURNAL_ZEITGEIST_BACKEND_ALL_ACTIVITIES, g_param_spec_object ("all-activities", "all-activities", "all-activities", GEE_TYPE_ARRAY_LIST, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
	g_signal_new ("events_loaded", JOURNAL_TYPE_ZEITGEIST_BACKEND, G_SIGNAL_RUN_LAST, 0, NULL, NULL, g_cclosure_marshal_VOID__VOID, G_TYPE_NONE, 0);
}


static void journal_zeitgeist_backend_instance_init (JournalZeitgeistBackend * self) {
	self->priv = JOURNAL_ZEITGEIST_BACKEND_GET_PRIVATE (self);
}


static void journal_zeitgeist_backend_finalize (GObject* obj) {
	JournalZeitgeistBackend * self;
	self = JOURNAL_ZEITGEIST_BACKEND (obj);
	_g_object_unref0 (self->priv->zg_log);
	_g_object_unref0 (self->priv->all_events);
	_g_object_unref0 (self->priv->all_app_events);
	_g_object_unref0 (self->priv->days_map);
	G_OBJECT_CLASS (journal_zeitgeist_backend_parent_class)->finalize (obj);
}


GType journal_zeitgeist_backend_get_type (void) {
	static volatile gsize journal_zeitgeist_backend_type_id__volatile = 0;
	if (g_once_init_enter (&journal_zeitgeist_backend_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (JournalZeitgeistBackendClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) journal_zeitgeist_backend_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (JournalZeitgeistBackend), 0, (GInstanceInitFunc) journal_zeitgeist_backend_instance_init, NULL };
		GType journal_zeitgeist_backend_type_id;
		journal_zeitgeist_backend_type_id = g_type_register_static (G_TYPE_OBJECT, "JournalZeitgeistBackend", &g_define_type_info, 0);
		g_once_init_leave (&journal_zeitgeist_backend_type_id__volatile, journal_zeitgeist_backend_type_id);
	}
	return journal_zeitgeist_backend_type_id__volatile;
}


static void _vala_journal_zeitgeist_backend_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	JournalZeitgeistBackend * self;
	self = JOURNAL_ZEITGEIST_BACKEND (object);
	switch (property_id) {
		case JOURNAL_ZEITGEIST_BACKEND_ALL_ACTIVITIES:
		g_value_set_object (value, journal_zeitgeist_backend_get_all_activities (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



